CREATE TABLE ANAG_MIGR.ANPR_COMUNI
(
  ID                       NUMBER,
  DATAISTITUZIONE          DATE,
  DATACESSAZIONE           DATE,
  CODISTAT                 CHAR(6 BYTE),
  CODCATASTALE             VARCHAR2(20 BYTE),
  DENOMINAZIONE_IT         VARCHAR2(200 BYTE),
  DENOMTRASLITTERATA       VARCHAR2(300 BYTE),
  ALTRADENOMINAZIONE       VARCHAR2(300 BYTE),
  ALTRADENOMTRASLITTERATA  VARCHAR2(300 BYTE),
  IDPROVINCIA              NUMBER,
  IDREGIONE                VARCHAR2(20 BYTE),
  IDPREFETTURA             VARCHAR2(20 BYTE),
  STATO                    VARCHAR2(20 BYTE),
  SIGLAPROVINCIA           VARCHAR2(20 BYTE),
  FONTE                    VARCHAR2(20 BYTE),
  DATAULTIMOAGG            DATE,
  COD_DENOM                VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE ANAG_MIGR.RID_DEC_STATO_CIVILE
(
  FLG_STATO_CIVILE         CHAR(1 BYTE),
  SESSO                    CHAR(1 BYTE),
  DESCRIZIONE_SESSO        VARCHAR2(20 BYTE),
  DESCRIZIONE_SENZA_SESSO  VARCHAR2(20 BYTE),
  FLG_1                    CHAR(1 BYTE),
  FLG_2                    CHAR(1 BYTE),
  FLG_3                    CHAR(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE ANAG_MIGR.RID_DEC_COD_TIP_IND
(
  COD_TIP_IND  CHAR(1 BYTE),
  DESCRIZIONE  VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE ANAG_MIGR.TBL_TERRIT_NAZION
(
  SIG_NAZ                   VARCHAR2(50 BYTE),
  DEN_NAZ                   VARCHAR2(200 BYTE),
  COD_NAZ_ISTAT             VARCHAR2(5 BYTE),
  COD_NAZ_MMII              VARCHAR2(5 BYTE),
  COD_NAZ_IMCTC             VARCHAR2(20 BYTE),
  DESCRIZIONE_CITTADINANZA  VARCHAR2(200 BYTE),
  COD_GEO                   VARCHAR2(5 BYTE),
  FLG_CEE                   VARCHAR2(1 BYTE),
  FLG_LIB_LAV               VARCHAR2(1 BYTE),
  COD_BEL                   VARCHAR2(4 BYTE),
  FLG_INT                   VARCHAR2(1 BYTE),
  UTE_OPE                   VARCHAR2(200 BYTE),
  PGM_OPE                   VARCHAR2(200 BYTE),
  DTA_OPE                   VARCHAR2(8 BYTE),
  ORA_OPE                   VARCHAR2(6 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE ANAG_MIGR.TBL_TERRIT_PROVIN
(
  SIGLA_PROVINCIA  VARCHAR2(5 BYTE),
  DENOMINAZIONE    VARCHAR2(200 BYTE),
  DEN_REGIONE      VARCHAR2(200 BYTE),
  FLG_CAP_REG      VARCHAR2(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE ANAG_MIGR.TBL_TERRIT_COMUNI
(
  COD_COM           VARCHAR2(5 BYTE),
  TIP_COD_COM       VARCHAR2(1 BYTE),
  FLG_COM_ANN       VARCHAR2(1 BYTE),
  DATA_INI_VAL_COM  VARCHAR2(8 BYTE),
  DATA_FIN_VAL_COM  VARCHAR2(8 BYTE),
  DEN_COM           VARCHAR2(200 BYTE),
  SIG_NAZ           VARCHAR2(5 BYTE),
  SIG_PRO           VARCHAR2(5 BYTE),
  COD_COM_ISTAT     VARCHAR2(10 BYTE),
  CAP               VARCHAR2(5 BYTE),
  COD_TRI           VARCHAR2(5 BYTE),
  DEN_COM_BRE       VARCHAR2(200 BYTE),
  COD_BEL           VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE ANAG_MIGR.RIC_DEC_STATUS_CDOM
(
  STATUS       VARCHAR2(2 BYTE),
  DESCRIZIONE  VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
