CREATE TABLE INC_USR.DIM_COND
(
  ID_TIPO_CONDUCENTE  CHAR(1 BYTE)              NOT NULL,
  TIPO_CONDUCENTE     CHAR(100 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_COND_PK ON INC_USR.DIM_COND
(ID_TIPO_CONDUCENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_COND ADD (
  CONSTRAINT DIM_COND_PK
  PRIMARY KEY
  (ID_TIPO_CONDUCENTE)
  USING INDEX INC_USR.DIM_COND_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_CONMET
(
  ID_CONDIZIONI_METEO  NCHAR(1)                 NOT NULL,
  CONDIZIONI_METEO     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_CON_MET_PK ON INC_USR.DIM_CONMET
(ID_CONDIZIONI_METEO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_CONMET ADD (
  CONSTRAINT DIM_CON_MET_PK
  PRIMARY KEY
  (ID_CONDIZIONI_METEO)
  USING INDEX INC_USR.DIM_CON_MET_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_DENSTR
(
  ID_DENOMINAZIONE_STRADA  VARCHAR2(3 BYTE)     NOT NULL,
  DENIMINAZIONE_STRADA     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_DEN_STR_PK ON INC_USR.DIM_DENSTR
(ID_DENOMINAZIONE_STRADA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_DENSTR ADD (
  CONSTRAINT DIM_DEN_STR_PK
  PRIMARY KEY
  (ID_DENOMINAZIONE_STRADA)
  USING INDEX INC_USR.DIM_DEN_STR_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_ESITO
(
  ID_ESITO      CHAR(1 BYTE)                    NOT NULL,
  ESITO         VARCHAR2(50 BYTE),
  CLASSE_ESITO  VARCHAR2(10 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_ESITO_PK ON INC_USR.DIM_ESITO
(ID_ESITO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_ESITO ADD (
  CONSTRAINT DIM_ESITO_PK
  PRIMARY KEY
  (ID_ESITO)
  USING INDEX INC_USR.DIM_ESITO_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_ETA
(
  ETA              VARCHAR2(2 BYTE)             NOT NULL,
  FASCE_ETA        VARCHAR2(50 BYTE),
  FASCE_ETA_NUOVA  VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_ETA_PK ON INC_USR.DIM_ETA
(ETA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_ETA ADD (
  CONSTRAINT DIM_ETA_PK
  PRIMARY KEY
  (ETA)
  USING INDEX INC_USR.DIM_ETA_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_FONSTRA
(
  ID_FONDO_STRADA  CHAR(1 BYTE)                 NOT NULL,
  FONDO_STRADA     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_FON_STRA_PK ON INC_USR.DIM_FONSTRA
(ID_FONDO_STRADA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_FONSTRA ADD (
  CONSTRAINT DIM_FON_STRA_PK
  PRIMARY KEY
  (ID_FONDO_STRADA)
  USING INDEX INC_USR.DIM_FON_STRA_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_INTERS
(
  ID_INTERS     CHAR(2 BYTE)                    NOT NULL,
  INTERSEZIONE  VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_INTERS_PK ON INC_USR.DIM_INTERS
(ID_INTERS)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_INTERS ADD (
  CONSTRAINT DIM_INTERS_PK
  PRIMARY KEY
  (ID_INTERS)
  USING INDEX INC_USR.DIM_INTERS_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_LOCINC
(
  ID_LOCALIZZAZIONE_INCIDENTE  CHAR(1 BYTE)     NOT NULL,
  LOCALIZZAZIONE_INCIDENTE     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_LOCINC_PK ON INC_USR.DIM_LOCINC
(ID_LOCALIZZAZIONE_INCIDENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_LOCINC ADD (
  CONSTRAINT DIM_LOCINC_PK
  PRIMARY KEY
  (ID_LOCALIZZAZIONE_INCIDENTE)
  USING INDEX INC_USR.DIM_LOCINC_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_MUNICIPIO
(
  ID_MUNICIPIO  NCHAR(2)                        NOT NULL,
  MUNICIPIO     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_MUNICIPIO_PK ON INC_USR.DIM_MUNICIPIO
(ID_MUNICIPIO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_MUNICIPIO ADD (
  CONSTRAINT DIM_MUNICIPIO_PK
  PRIMARY KEY
  (ID_MUNICIPIO)
  USING INDEX INC_USR.DIM_MUNICIPIO_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_NATINC
(
  ID_NATURA_INCIDENTE  CHAR(2 BYTE)             NOT NULL,
  NATURA_INCIDENTE     VARCHAR2(50 BYTE),
  CATEGORIA_VEICOLO    VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_NATINC_PK ON INC_USR.DIM_NATINC
(ID_NATURA_INCIDENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_NATINC ADD (
  CONSTRAINT DIM_NATINC_PK
  PRIMARY KEY
  (ID_NATURA_INCIDENTE)
  USING INDEX INC_USR.DIM_NATINC_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_ORA
(
  ORA         VARCHAR2(2 BYTE)                  NOT NULL,
  FASCIA_ORA  VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_ORA_PK ON INC_USR.DIM_ORA
(ORA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_ORA ADD (
  CONSTRAINT DIM_ORA_PK
  PRIMARY KEY
  (ORA)
  USING INDEX INC_USR.DIM_ORA_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_ORGCOOR
(
  ID_ORGANO_COORDINATORE  CHAR(1 BYTE)          NOT NULL,
  ORGANO_COORDINATORE     VARCHAR2(100 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_ORGCOOR_PK ON INC_USR.DIM_ORGCOOR
(ID_ORGANO_COORDINATORE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_ORGCOOR ADD (
  CONSTRAINT DIM_ORGCOOR_PK
  PRIMARY KEY
  (ID_ORGANO_COORDINATORE)
  USING INDEX INC_USR.DIM_ORGCOOR_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_ORGRIL
(
  ID_ORGANO_RILEVAZIONE  CHAR(1 BYTE)           NOT NULL,
  ORGANO_RILEVAZIONE     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE INC_USR.DIM_PAT
(
  ID_TIPO_PATENTE  CHAR(1 BYTE)                 NOT NULL,
  TIPO_PATENTE     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_PAT_PK ON INC_USR.DIM_PAT
(ID_TIPO_PATENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_PAT ADD (
  CONSTRAINT DIM_PAT_PK
  PRIMARY KEY
  (ID_TIPO_PATENTE)
  USING INDEX INC_USR.DIM_PAT_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_PAV
(
  ID_PAVIMENTAZIONE  NCHAR(1)                   NOT NULL,
  PAVIMENTAZIONE     VARCHAR2(50 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_PAV_PK ON INC_USR.DIM_PAV
(ID_PAVIMENTAZIONE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_PAV ADD (
  CONSTRAINT DIM_PAV_PK
  PRIMARY KEY
  (ID_PAVIMENTAZIONE)
  USING INDEX INC_USR.DIM_PAV_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_PERSONA
(
  ID_PERSONA       INTEGER,
  TIPO_PERSONA     VARCHAR2(1 BYTE),
  ETA              VARCHAR2(2 BYTE),
  SESSO            VARCHAR2(1 BYTE),
  ESITO            VARCHAR2(1 BYTE),
  TIPO_PATENTE     VARCHAR2(1 BYTE),
  ANNO_PATENTE     VARCHAR2(2 BYTE),
  TIPO_CONDUCENTE  VARCHAR2(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_PERSONA_PK ON INC_USR.DIM_PERSONA
(ID_PERSONA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INC_USR.IDX_LOAD_PERSONA ON INC_USR.DIM_PERSONA
(TIPO_PERSONA, ETA, SESSO, ESITO, TIPO_PATENTE, 
ANNO_PATENTE, TIPO_CONDUCENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_PERSONA ADD (
  CONSTRAINT DIM_PERSONA_PK
  PRIMARY KEY
  (ID_PERSONA)
  USING INDEX INC_USR.DIM_PERSONA_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_PRGVEICOLO
(
  ID_PRG_VEICOLO  VARCHAR2(1 BYTE)              NOT NULL,
  "_VEICOLO"      VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_PRGVEICOLO_PK ON INC_USR.DIM_PRGVEICOLO
(ID_PRG_VEICOLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_PRGVEICOLO ADD (
  CONSTRAINT DIM_PRGVEICOLO_PK
  PRIMARY KEY
  (ID_PRG_VEICOLO)
  USING INDEX INC_USR.DIM_PRGVEICOLO_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_SEGN
(
  ID_SEGNALETICA  NCHAR(1)                      NOT NULL,
  SEGNALETICA     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_SEGN_PK ON INC_USR.DIM_SEGN
(ID_SEGNALETICA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_SEGN ADD (
  CONSTRAINT DIM_SEGN_PK
  PRIMARY KEY
  (ID_SEGNALETICA)
  USING INDEX INC_USR.DIM_SEGN_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_SESSO
(
  ID_SESSO  CHAR(1 BYTE)                        NOT NULL,
  SESSO     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_SESSO_PK ON INC_USR.DIM_SESSO
(ID_SESSO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_SESSO ADD (
  CONSTRAINT DIM_SESSO_PK
  PRIMARY KEY
  (ID_SESSO)
  USING INDEX INC_USR.DIM_SESSO_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_STRADA
(
  ID_STRADA  VARCHAR2(2 BYTE)                   NOT NULL,
  STRADA     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_STRADA_PK ON INC_USR.DIM_STRADA
(ID_STRADA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_STRADA ADD (
  CONSTRAINT DIM_STRADA_PK
  PRIMARY KEY
  (ID_STRADA)
  USING INDEX INC_USR.DIM_STRADA_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_TEMPO
(
  DATA_CODE     VARCHAR2(8 BYTE)                NOT NULL,
  ANNO          NUMBER(38),
  NUM_SEMESTRE  NUMBER(38),
  NUM_MESE      NUMBER(38),
  MESE          VARCHAR2(10 BYTE),
  DATA_FORMAT   DATE
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.PK_DIM_TEMPO ON INC_USR.DIM_TEMPO
(DATA_CODE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
CREATE TABLE INC_USR.DIM_TIPOPERSONA
(
  ID_TIPO_PERSONA  VARCHAR2(1 BYTE)             NOT NULL,
  TIPO_PERSONA     VARCHAR2(50 BYTE),
  CLASSE           VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_TIPOPERSONA_PK ON INC_USR.DIM_TIPOPERSONA
(ID_TIPO_PERSONA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_TIPOPERSONA ADD (
  CONSTRAINT DIM_TIPOPERSONA_PK
  PRIMARY KEY
  (ID_TIPO_PERSONA)
  USING INDEX INC_USR.DIM_TIPOPERSONA_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_TIPOVEICOLO
(
  ID_TIPO_VEICOLO  CHAR(2 BYTE)                 NOT NULL,
  TIPO_VEICOLO     VARCHAR2(50 BYTE),
  CAT_VEICOLO      VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_VEICOLO_PK ON INC_USR.DIM_TIPOVEICOLO
(ID_TIPO_VEICOLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_TIPOVEICOLO ADD (
  CONSTRAINT DIM_TIPOVEICOLO_PK
  PRIMARY KEY
  (ID_TIPO_VEICOLO)
  USING INDEX INC_USR.DIM_VEICOLO_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_TIPSTR
(
  ID_TIPO_STRADA  CHAR(1 BYTE)                  NOT NULL,
  TIPO_STRADA     VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_TIPSTR_PK ON INC_USR.DIM_TIPSTR
(ID_TIPO_STRADA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_TIPSTR ADD (
  CONSTRAINT DIM_TIPSTR_PK
  PRIMARY KEY
  (ID_TIPO_STRADA)
  USING INDEX INC_USR.DIM_TIPSTR_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_VEICOLO
(
  ID_VEICOLO              INTEGER               NOT NULL,
  TIPO_VEICOLO            VARCHAR2(2 BYTE),
  PESO_VEICOLO            VARCHAR2(4 BYTE),
  TARGA                   VARCHAR2(8 BYTE),
  SIGLA                   VARCHAR2(3 BYTE),
  ANNO_IMMATRICOLAZIONE   VARCHAR2(2 BYTE),
  FLAG_PRIMI_DUE_VEICOLI  VARCHAR2(1 BYTE),
  PRG_VEICOLO             VARCHAR2(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX INC_USR.DIM_VEICOLO_IDX1 ON INC_USR.DIM_VEICOLO
(TIPO_VEICOLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INC_USR.DIM_VEICOLO_IDX2 ON INC_USR.DIM_VEICOLO
(ID_VEICOLO, TIPO_VEICOLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INC_USR.DIM_VEICOLO_PKI ON INC_USR.DIM_VEICOLO
(ID_VEICOLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INC_USR.IDX_LOAD_VEICOLO ON INC_USR.DIM_VEICOLO
(TIPO_VEICOLO, PESO_VEICOLO, TARGA, SIGLA, ANNO_IMMATRICOLAZIONE, 
FLAG_PRIMI_DUE_VEICOLI, PRG_VEICOLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_VEICOLO ADD (
  CONSTRAINT DIM_VEICOLO_PKI
  PRIMARY KEY
  (ID_VEICOLO)
  USING INDEX INC_USR.DIM_VEICOLO_IDX2
  ENABLE VALIDATE);
CREATE TABLE INC_USR.F_INCIDENTE
(
  ID_INCIDENTE                    INTEGER       NOT NULL,
  ID_VEICOLO                      INTEGER,
  ID_PERSONA                      INTEGER,
  COD_INCIDENTE                   VARCHAR2(12 BYTE),
  DATA                            DATE,
  PROVINCIA                       VARCHAR2(3 BYTE),
  COMUNE                          VARCHAR2(3 BYTE),
  NUMERO_ORDINE                   VARCHAR2(5 BYTE),
  ORA                             VARCHAR2(2 BYTE),
  ORGANO_RILEVAZIONE              VARCHAR2(1 BYTE),
  ORGANO_COORDINATORE             VARCHAR2(1 BYTE),
  LOCALIZZAZIONE_INCIDENTE        VARCHAR2(1 BYTE),
  DENOMINAZIONE_STRADA            VARCHAR2(3 BYTE),
  STRADA                          VARCHAR2(2 BYTE),
  TIPO_STRADA                     VARCHAR2(1 BYTE),
  PAVIMENTAZIONE                  NCHAR(1),
  INTERSEZIONE_NON_INTERSEZIONE   VARCHAR2(2 BYTE),
  FONDO_STRADALE                  VARCHAR2(1 BYTE),
  SEGNALETICA                     VARCHAR2(1 BYTE),
  CONDIZIONI_METEOROLOGICHE       VARCHAR2(1 BYTE),
  NATURA_INCIDENTE                VARCHAR2(2 BYTE),
  CIRCOSTANZE_INCONVENIENTI_CIRC  VARCHAR2(3 BYTE),
  CIRCOSTANZE_DIFETTI_VEICOLO     VARCHAR2(3 BYTE),
  CIRCOSTANZE_STATO_GUIDATORE     VARCHAR2(3 BYTE),
  NOME_STRADA                     VARCHAR2(101 BYTE),
  NUMERO_INCIDENTI                INTEGER,
  NUMERO_MORTI                    INTEGER,
  NUMERO_FERITI                   INTEGER,
  NUMERO_VEICOLI                  INTEGER,
  MUNICIPIO                       VARCHAR2(2 BYTE),
  PROT_INC                        VARCHAR2(6 BYTE),
  STRADA1                         VARCHAR2(7 BYTE),
  STRADA2                         VARCHAR2(7 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX INC_USR.F_INCIDENTE_INDEX1_1 ON INC_USR.F_INCIDENTE
(COD_INCIDENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INC_USR.F_INCIDENTE_PK_1 ON INC_USR.F_INCIDENTE
(ID_INCIDENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.F_INCIDENTE ADD (
  CONSTRAINT F_INCIDENTE_PK_1
  PRIMARY KEY
  (ID_INCIDENTE)
  USING INDEX INC_USR.F_INCIDENTE_PK_1
  ENABLE VALIDATE);
CREATE TABLE INC_USR.F_INCIDENTE_TMP
(
  ID_INCIDENTE                    INTEGER       NOT NULL,
  ID_VEICOLO                      INTEGER,
  ID_PERSONA                      INTEGER,
  COD_INCIDENTE                   VARCHAR2(12 BYTE),
  DATA                            DATE,
  PROVINCIA                       VARCHAR2(3 BYTE),
  COMUNE                          VARCHAR2(3 BYTE),
  NUMERO_ORDINE                   VARCHAR2(5 BYTE),
  ORA                             VARCHAR2(2 BYTE),
  ORGANO_RILEVAZIONE              VARCHAR2(1 BYTE),
  ORGANO_COORDINATORE             VARCHAR2(1 BYTE),
  LOCALIZZAZIONE_INCIDENTE        VARCHAR2(1 BYTE),
  DENOMINAZIONE_STRADA            VARCHAR2(3 BYTE),
  STRADA                          VARCHAR2(2 BYTE),
  TIPO_STRADA                     VARCHAR2(1 BYTE),
  PAVIMENTAZIONE                  NCHAR(1),
  INTERSEZIONE_NON_INTERSEZIONE   VARCHAR2(2 BYTE),
  FONDO_STRADALE                  VARCHAR2(1 BYTE),
  SEGNALETICA                     VARCHAR2(1 BYTE),
  CONDIZIONI_METEOROLOGICHE       VARCHAR2(1 BYTE),
  NATURA_INCIDENTE                VARCHAR2(2 BYTE),
  CIRCOSTANZE_INCONVENIENTI_CIRC  VARCHAR2(3 BYTE),
  CIRCOSTANZE_DIFETTI_VEICOLO     VARCHAR2(3 BYTE),
  CIRCOSTANZE_STATO_GUIDATORE     VARCHAR2(3 BYTE),
  NOME_STRADA                     VARCHAR2(101 BYTE),
  NUMERO_INCIDENTI                INTEGER,
  NUMERO_MORTI                    INTEGER,
  NUMERO_FERITI                   INTEGER,
  NUMERO_VEICOLI                  INTEGER,
  MUNICIPIO                       VARCHAR2(2 BYTE),
  PROT_INC                        VARCHAR2(6 BYTE),
  STRADA1                         VARCHAR2(7 BYTE),
  STRADA2                         VARCHAR2(7 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX INC_USR.F_INCIDENTE_TMP_IDX ON INC_USR.F_INCIDENTE_TMP
("DATA" DESC)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INC_USR.F_INCIDENTE_TMP_PK ON INC_USR.F_INCIDENTE_TMP
(ID_INCIDENTE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.F_INCIDENTE_TMP ADD (
  CONSTRAINT F_INCIDENTE_TMP_PK
  PRIMARY KEY
  (ID_INCIDENTE)
  USING INDEX INC_USR.F_INCIDENTE_TMP_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_COMUNI
(
  ID_COMUNE           VARCHAR2(3 BYTE)          NOT NULL,
  DESCRIZIONE_COMUNE  VARCHAR2(50 BYTE),
  CODICE_ISTAT        VARCHAR2(6 BYTE),
  LUOGO               VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_COMUNI_PK ON INC_USR.DIM_COMUNI
(ID_COMUNE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_COMUNI ADD (
  CONSTRAINT DIM_COMUNI_PK
  PRIMARY KEY
  (ID_COMUNE)
  USING INDEX INC_USR.DIM_COMUNI_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.DIM_CODICIINCIDENTI
(
  ID_CODICE      VARCHAR2(3 BYTE)               NOT NULL,
  DESCRIZIONE    VARCHAR2(100 BYTE),
  AGGREGAZIONE   VARCHAR2(100 BYTE),
  AGG_REPORTING  VARCHAR2(50 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INC_USR.DIM_CODICIINCIDENTI_PK ON INC_USR.DIM_CODICIINCIDENTI
(ID_CODICE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.DIM_CODICIINCIDENTI ADD (
  CONSTRAINT DIM_CODICIINCIDENTI_PK
  PRIMARY KEY
  (ID_CODICE)
  USING INDEX INC_USR.DIM_CODICIINCIDENTI_PK
  ENABLE VALIDATE);
CREATE TABLE INC_USR.LOAD_INCIDENTI
(
  NOME_FILE                  VARCHAR2(50 BYTE),
  DATA_FILE                  DATE,
  ANNO_INC                   VARCHAR2(2 BYTE),
  MESE_INC                   VARCHAR2(2 BYTE),
  PROVINCIA                  VARCHAR2(3 BYTE),
  COMUNE                     VARCHAR2(3 BYTE),
  NUM_ORDINE                 VARCHAR2(5 BYTE),
  GIORNO_INC                 VARCHAR2(2 BYTE),
  ORGANO_RIL                 VARCHAR2(1 BYTE),
  ORGANO_COOR                VARCHAR2(1 BYTE),
  LOC_INC                    VARCHAR2(1 BYTE),
  DENOM_STRA                 VARCHAR2(3 BYTE),
  STRADA                     VARCHAR2(2 BYTE),
  TIPO_STRADA                VARCHAR2(1 BYTE),
  PAVIMENTAZIONE             VARCHAR2(1 BYTE),
  INTERSEZIONE               VARCHAR2(2 BYTE),
  FONDO_STRADALE             VARCHAR2(1 BYTE),
  SEGNALETICA                VARCHAR2(1 BYTE),
  CONDIZIONI_METEO           VARCHAR2(1 BYTE),
  NATURA_INC                 VARCHAR2(2 BYTE),
  TIPO_VEIC_A                VARCHAR2(2 BYTE),
  TIPO_VEIC_B                VARCHAR2(2 BYTE),
  TIPO_VEIC_C                VARCHAR2(2 BYTE),
  PESO_VEIC_A                VARCHAR2(4 BYTE),
  PESO_VEIC_B                VARCHAR2(4 BYTE),
  PESO_VEIC_C                VARCHAR2(4 BYTE),
  CIRC_VEIC_A_CIRC           VARCHAR2(2 BYTE),
  CIRC_VEIC_A_DIF            VARCHAR2(2 BYTE),
  CIRC_VEIC_A_PSIC           VARCHAR2(2 BYTE),
  CIRC_VEIC_B_CIRC           VARCHAR2(2 BYTE),
  CIRC_VEIC_B_DIF            VARCHAR2(2 BYTE),
  CIRC_VEIC_B_PSIC           VARCHAR2(2 BYTE),
  TARGA_VEIC_A               VARCHAR2(8 BYTE),
  SIGLA_VEIC_A               VARCHAR2(3 BYTE),
  IMM_VEIC_A                 VARCHAR2(2 BYTE),
  TARGA_VEIC_B               VARCHAR2(8 BYTE),
  SIGLA_VEIC_B               VARCHAR2(3 BYTE),
  IMM_VEIC_B                 VARCHAR2(2 BYTE),
  TARGA_VEIC_C               VARCHAR2(8 BYTE),
  SIGLA_VEIC_C               VARCHAR2(3 BYTE),
  IMM_VEIC_C                 VARCHAR2(2 BYTE),
  ETA_COND_A                 VARCHAR2(2 BYTE),
  SESSO_COND_A               VARCHAR2(1 BYTE),
  ESITO_COND_A               VARCHAR2(1 BYTE),
  PAT_COND_A                 VARCHAR2(1 BYTE),
  ANNO_PAT_A                 VARCHAR2(2 BYTE),
  TIPO_COND_A                VARCHAR2(1 BYTE),
  ESITO_PASS_ANT_A           VARCHAR2(1 BYTE),
  ETA_PASS_ANT_A             VARCHAR2(2 BYTE),
  SESSO_PASS_ANT_A           VARCHAR2(1 BYTE),
  ESITO_PASS_POST_A          VARCHAR2(1 BYTE),
  ETA_PASS_POST_A            VARCHAR2(2 BYTE),
  SESSO_PASS_POST_A          VARCHAR2(1 BYTE),
  ESITO_PASS_POST_A1         VARCHAR2(1 BYTE),
  ETA_PASS_POST_A1           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_A1         VARCHAR2(1 BYTE),
  ESITO_PASS_POST_A2         VARCHAR2(1 BYTE),
  ETA_PASS_POST_A2           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_A2         VARCHAR2(1 BYTE),
  MASCHI_MORTI_A             VARCHAR2(2 BYTE),
  FEMMINE_MORTE_A            VARCHAR2(2 BYTE),
  MASCHI_FERITI_A            VARCHAR2(2 BYTE),
  FEMMINE_FERITE_A           VARCHAR2(2 BYTE),
  ETA_COND_B                 VARCHAR2(2 BYTE),
  SESSO_COND_B               VARCHAR2(1 BYTE),
  ESITO_COND_B               VARCHAR2(1 BYTE),
  PAT_COND_B                 VARCHAR2(1 BYTE),
  ANNO_PAT_B                 VARCHAR2(2 BYTE),
  TIPO_COND_B                VARCHAR2(1 BYTE),
  ESITO_PASS_ANT_B           VARCHAR2(1 BYTE),
  ETA_PASS_ANT_B             VARCHAR2(2 BYTE),
  SESSO_PASS_ANT_B           VARCHAR2(1 BYTE),
  ESITO_PASS_POST_B          VARCHAR2(1 BYTE),
  ETA_PASS_POST_B            VARCHAR2(2 BYTE),
  SESSO_PASS_POST_B          VARCHAR2(1 BYTE),
  ESITO_PASS_POST_B1         VARCHAR2(1 BYTE),
  ETA_PASS_POST_B1           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_B1         VARCHAR2(1 BYTE),
  ESITO_PASS_POST_B2         VARCHAR2(1 BYTE),
  ETA_PASS_POST_B2           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_B2         VARCHAR2(1 BYTE),
  MASCHI_MORTI_B             VARCHAR2(2 BYTE),
  FEMMINE_MORTE_B            VARCHAR2(2 BYTE),
  MASCHI_FERITI_B            VARCHAR2(2 BYTE),
  FEMMINE_FERITE_B           VARCHAR2(2 BYTE),
  ETA_COND_C                 VARCHAR2(2 BYTE),
  SESSO_COND_C               VARCHAR2(1 BYTE),
  ESITO_COND_C               VARCHAR2(1 BYTE),
  PAT_COND_C                 VARCHAR2(1 BYTE),
  ANNO_PAT_C                 VARCHAR2(2 BYTE),
  TIPO_COND_C                VARCHAR2(1 BYTE),
  ESITO_PASS_ANT_C           VARCHAR2(1 BYTE),
  ETA_PASS_ANT_C             VARCHAR2(2 BYTE),
  SESSO_PASS_ANT_C           VARCHAR2(1 BYTE),
  ESITO_PASS_POST_C          VARCHAR2(1 BYTE),
  ETA_PASS_POST_C            VARCHAR2(2 BYTE),
  SESSO_PASS_POST_C          VARCHAR2(1 BYTE),
  ESITO_PASS_POST_C1         VARCHAR2(1 BYTE),
  ETA_PASS_POST_C1           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_C1         VARCHAR2(1 BYTE),
  ESITO_PASS_POST_C2         VARCHAR2(1 BYTE),
  ETA_PASS_POST_C2           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_C2         VARCHAR2(1 BYTE),
  MASCHI_MORTI_C             VARCHAR2(2 BYTE),
  FEMMINE_MORTE_C            VARCHAR2(2 BYTE),
  MASCHI_FERITI_C            VARCHAR2(2 BYTE),
  FEMMINE_FERITE_C           VARCHAR2(2 BYTE),
  SESSO_1_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_1_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_1_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_1_PED_FERITO           VARCHAR2(2 BYTE),
  SESSO_2_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_2_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_2_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_2_PED_FERITO           VARCHAR2(2 BYTE),
  SESSO_3_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_3_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_3_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_3_PED_FERITO           VARCHAR2(2 BYTE),
  SESSO_4_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_4_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_4_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_4_PED_FERITO           VARCHAR2(2 BYTE),
  ALTRI_VEIC                 VARCHAR2(2 BYTE),
  MORTI_MASCHI_ALTRI_VEIC    VARCHAR2(2 BYTE),
  MORTI_FEMMINE_ALTRI_VEIC   VARCHAR2(2 BYTE),
  FERITI_MASCHI_ALTRI_VEIC   VARCHAR2(2 BYTE),
  FERITI_FEMMINE_ALTRI_VEIC  VARCHAR2(2 BYTE),
  TOT_MORTI_H24              VARCHAR2(2 BYTE),
  TOT_MORTI_2_30_GIORNI      VARCHAR2(2 BYTE),
  TOT_FERITI                 VARCHAR2(2 BYTE),
  NOME_STRADA                VARCHAR2(101 BYTE),
  NOME_1_MORTO               VARCHAR2(30 BYTE),
  COGNOME_1_MORTO            VARCHAR2(30 BYTE),
  NOME_2_MORTO               VARCHAR2(30 BYTE),
  COGNOME_2_MORTO            VARCHAR2(30 BYTE),
  NOME_3_MORTO               VARCHAR2(30 BYTE),
  COGNOME_3_MORTO            VARCHAR2(30 BYTE),
  NOME_4_MORTO               VARCHAR2(30 BYTE),
  COGNOME_4_MORTO            VARCHAR2(30 BYTE),
  NOME_1_FERITO              VARCHAR2(30 BYTE),
  COGNOME_1_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_1_FERITO          VARCHAR2(30 BYTE),
  NOME_2_FERITO              VARCHAR2(30 BYTE),
  COGNOME_2_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_2_FERITO          VARCHAR2(30 BYTE),
  NOME_3_FERITO              VARCHAR2(30 BYTE),
  COGNOME_3_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_3_FERITO          VARCHAR2(30 BYTE),
  NOME_4_FERITO              VARCHAR2(30 BYTE),
  COGNOME_4_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_4_FERITO          VARCHAR2(30 BYTE),
  NOME_5_FERITO              VARCHAR2(30 BYTE),
  COGNOME_5_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_5_FERITO          VARCHAR2(30 BYTE),
  NOME_6_FERITO              VARCHAR2(30 BYTE),
  COGNOME_6_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_6_FERITO          VARCHAR2(30 BYTE),
  NOME_7_FERITO              VARCHAR2(30 BYTE),
  COGNOME_7_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_7_FERITO          VARCHAR2(30 BYTE),
  NOME_8_FERITO              VARCHAR2(30 BYTE),
  COGNOME_8_FERITO           VARCHAR2(30 BYTE),
  OSPEDALE_8_FERITO          VARCHAR2(30 BYTE),
  TIPO_COORDINATA            VARCHAR2(1 BYTE),
  SISTEMA_PROIEZIONE         VARCHAR2(1 BYTE),
  X_LAT                      VARCHAR2(50 BYTE),
  Y_LON                      VARCHAR2(50 BYTE),
  ORA_INC                    VARCHAR2(2 BYTE),
  MIN_INC                    VARCHAR2(2 BYTE),
  COD_CARAB                  VARCHAR2(30 BYTE),
  PROG_KIL                   VARCHAR2(4 BYTE),
  ETTOMETRICA                VARCHAR2(3 BYTE),
  CILINDRATA_A               VARCHAR2(5 BYTE),
  CILINDRATA_B               VARCHAR2(5 BYTE),
  CILINDRATA_C               VARCHAR2(5 BYTE),
  COD_ENTE                   VARCHAR2(40 BYTE),
  MUNICIPIO                  VARCHAR2(2 BYTE),
  PROT_INC                   VARCHAR2(6 BYTE),
  STRADA1                    VARCHAR2(7 BYTE),
  STRADA2                    VARCHAR2(7 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX INC_USR.IDX_ETA_COND_B ON INC_USR.LOAD_INCIDENTI
(ETA_COND_B)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INC_USR.IDX_ETA_COND_C ON INC_USR.LOAD_INCIDENTI
(ETA_COND_C)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INC_USR.IDX_ETA_PASS_ANT_A ON INC_USR.LOAD_INCIDENTI
(ETA_PASS_ANT_A)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
CREATE TABLE INC_USR.LOAD_INCIDENTI_FILE_COMP
(
  ANNO_INC                   VARCHAR2(2 BYTE),
  MESE_INC                   VARCHAR2(2 BYTE),
  PROVINCIA                  VARCHAR2(3 BYTE),
  COMUNE                     VARCHAR2(3 BYTE),
  NUM_ORDINE                 VARCHAR2(5 BYTE),
  GIORNO_INC                 VARCHAR2(2 BYTE),
  ORA                        VARCHAR2(2 BYTE),
  ORGANO_RIL                 VARCHAR2(1 BYTE),
  NUM_PROG_ANNO              VARCHAR2(5 BYTE),
  ORGANO_COOR                VARCHAR2(1 BYTE),
  LOC_INC                    VARCHAR2(1 BYTE),
  DENOM_STRA                 VARCHAR2(3 BYTE),
  PROGRESSIVA_KM             VARCHAR2(3 BYTE),
  TRONCO_STRADA              VARCHAR2(2 BYTE),
  TIPO_STRADA                VARCHAR2(1 BYTE),
  PAVIMENTAZIONE             VARCHAR2(1 BYTE),
  INTERSEZIONE               VARCHAR2(2 BYTE),
  FONDO_STRADALE             VARCHAR2(1 BYTE),
  SEGNALETICA                VARCHAR2(1 BYTE),
  CONDIZIONI_METEO           VARCHAR2(1 BYTE),
  NATURA_INC                 VARCHAR2(2 BYTE),
  TIPO_VEIC_A                VARCHAR2(2 BYTE),
  TIPO_VEIC_B                VARCHAR2(2 BYTE),
  TIPO_VEIC_C                VARCHAR2(2 BYTE),
  CILINDRATA_VEIC_A          VARCHAR2(4 BYTE),
  CILINDRATA_VEIC_B          VARCHAR2(4 BYTE),
  CILINDRATA_VEIC_C          VARCHAR2(4 BYTE),
  PESO_VEIC_A                VARCHAR2(4 BYTE),
  PESO_VEIC_B                VARCHAR2(4 BYTE),
  PESO_VEIC_C                VARCHAR2(4 BYTE),
  CIRC_VEIC_A_CIRC           VARCHAR2(2 BYTE),
  CIRC_VEIC_A_DIF            VARCHAR2(2 BYTE),
  CIRC_VEIC_A_PSIC           VARCHAR2(2 BYTE),
  CIRC_VEIC_B_CIRC           VARCHAR2(2 BYTE),
  CIRC_VEIC_B_DIF            VARCHAR2(2 BYTE),
  CIRC_VEIC_B_PSIC           VARCHAR2(2 BYTE),
  TARGA_VEIC_A               VARCHAR2(8 BYTE),
  SIGLA_VEIC_A               VARCHAR2(3 BYTE),
  IMM_VEIC_A                 VARCHAR2(2 BYTE),
  ULT_REV_A                  VARCHAR2(2 BYTE),
  KM_VEIC_A                  VARCHAR2(3 BYTE),
  TARGA_VEIC_B               VARCHAR2(8 BYTE),
  SIGLA_VEIC_B               VARCHAR2(3 BYTE),
  IMM_VEIC_B                 VARCHAR2(2 BYTE),
  ULT_REV_B                  VARCHAR2(2 BYTE),
  KM_VEIC_B                  VARCHAR2(3 BYTE),
  TARGA_VEIC_C               VARCHAR2(8 BYTE),
  SIGLA_VEIC_C               VARCHAR2(3 BYTE),
  IMM_VEIC_C                 VARCHAR2(2 BYTE),
  ULT_REV_C                  VARCHAR2(2 BYTE),
  KM_VEIC_C                  VARCHAR2(3 BYTE),
  ETA_COND_A                 VARCHAR2(2 BYTE),
  SESSO_COND_A               VARCHAR2(1 BYTE),
  ESITO_COND_A               VARCHAR2(1 BYTE),
  PAT_COND_A                 VARCHAR2(1 BYTE),
  ANNO_PAT_A                 VARCHAR2(2 BYTE),
  TIPO_COND_A                VARCHAR2(1 BYTE),
  ESITO_PASS_ANT_A           VARCHAR2(1 BYTE),
  ETA_PASS_ANT_A             VARCHAR2(2 BYTE),
  SESSO_PASS_ANT_A           VARCHAR2(1 BYTE),
  ESITO_PASS_POST_A          VARCHAR2(1 BYTE),
  ETA_PASS_POST_A            VARCHAR2(2 BYTE),
  SESSO_PASS_POST_A          VARCHAR2(1 BYTE),
  ESITO_PASS_POST_A1         VARCHAR2(1 BYTE),
  ETA_PASS_POST_A1           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_A1         VARCHAR2(1 BYTE),
  ESITO_PASS_POST_A2         VARCHAR2(1 BYTE),
  ETA_PASS_POST_A2           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_A2         VARCHAR2(1 BYTE),
  MASCHI_MORTI_A             VARCHAR2(2 BYTE),
  FEMMINE_MORTE_A            VARCHAR2(2 BYTE),
  MASCHI_FERITI_A            VARCHAR2(2 BYTE),
  FEMMINE_FERITE_A           VARCHAR2(2 BYTE),
  ETA_COND_B                 VARCHAR2(2 BYTE),
  SESSO_COND_B               VARCHAR2(1 BYTE),
  ESITO_COND_B               VARCHAR2(1 BYTE),
  PAT_COND_B                 VARCHAR2(1 BYTE),
  ANNO_PAT_B                 VARCHAR2(2 BYTE),
  TIPO_COND_B                VARCHAR2(1 BYTE),
  ESITO_PASS_ANT_B           VARCHAR2(1 BYTE),
  ETA_PASS_ANT_B             VARCHAR2(2 BYTE),
  SESSO_PASS_ANT_B           VARCHAR2(1 BYTE),
  ESITO_PASS_POST_B          VARCHAR2(1 BYTE),
  ETA_PASS_POST_B            VARCHAR2(2 BYTE),
  SESSO_PASS_POST_B          VARCHAR2(1 BYTE),
  ESITO_PASS_POST_B1         VARCHAR2(1 BYTE),
  ETA_PASS_POST_B1           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_B1         VARCHAR2(1 BYTE),
  ESITO_PASS_POST_B2         VARCHAR2(1 BYTE),
  ETA_PASS_POST_B2           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_B2         VARCHAR2(1 BYTE),
  MASCHI_MORTI_B             VARCHAR2(2 BYTE),
  FEMMINE_MORTE_B            VARCHAR2(2 BYTE),
  MASCHI_FERITI_B            VARCHAR2(2 BYTE),
  FEMMINE_FERITE_B           VARCHAR2(2 BYTE),
  ETA_COND_C                 VARCHAR2(2 BYTE),
  SESSO_COND_C               VARCHAR2(1 BYTE),
  ESITO_COND_C               VARCHAR2(1 BYTE),
  PAT_COND_C                 VARCHAR2(1 BYTE),
  ANNO_PAT_C                 VARCHAR2(2 BYTE),
  TIPO_COND_C                VARCHAR2(1 BYTE),
  ESITO_PASS_ANT_C           VARCHAR2(1 BYTE),
  ETA_PASS_ANT_C             VARCHAR2(2 BYTE),
  SESSO_PASS_ANT_C           VARCHAR2(1 BYTE),
  ESITO_PASS_POST_C          VARCHAR2(1 BYTE),
  ETA_PASS_POST_C            VARCHAR2(2 BYTE),
  SESSO_PASS_POST_C          VARCHAR2(1 BYTE),
  ESITO_PASS_POST_C1         VARCHAR2(1 BYTE),
  ETA_PASS_POST_C1           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_C1         VARCHAR2(1 BYTE),
  ESITO_PASS_POST_C2         VARCHAR2(1 BYTE),
  ETA_PASS_POST_C2           VARCHAR2(2 BYTE),
  SESSO_PASS_POST_C2         VARCHAR2(1 BYTE),
  MASCHI_MORTI_C             VARCHAR2(2 BYTE),
  FEMMINE_MORTE_C            VARCHAR2(2 BYTE),
  MASCHI_FERITI_C            VARCHAR2(2 BYTE),
  FEMMINE_FERITE_C           VARCHAR2(2 BYTE),
  SESSO_1_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_1_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_1_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_1_PED_FERITO           VARCHAR2(2 BYTE),
  SESSO_2_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_2_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_2_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_2_PED_FERITO           VARCHAR2(2 BYTE),
  SESSO_3_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_3_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_3_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_3_PED_FERITO           VARCHAR2(2 BYTE),
  SESSO_4_PED_MORTO          VARCHAR2(1 BYTE),
  ETA_4_PED_MORTO            VARCHAR2(2 BYTE),
  SESSO_4_PED_FERITO         VARCHAR2(1 BYTE),
  ETA_4_PED_FERITO           VARCHAR2(2 BYTE),
  ALTRI_VEIC                 VARCHAR2(2 BYTE),
  MORTI_MASCHI_ALTRI_VEIC    VARCHAR2(2 BYTE),
  MORTI_FEMMINE_ALTRI_VEIC   VARCHAR2(2 BYTE),
  FERITI_MASCHI_ALTRI_VEIC   VARCHAR2(2 BYTE),
  FERITI_FEMMINE_ALTRI_VEIC  VARCHAR2(2 BYTE),
  TOT_MORTI_H24              VARCHAR2(2 BYTE),
  TOT_MORTI_2_30_GIORNI      VARCHAR2(2 BYTE),
  TOT_FERITI                 VARCHAR2(2 BYTE),
  NOME_STRADA                VARCHAR2(101 BYTE),
  CODICI_CONCORD             VARCHAR2(50 BYTE),
  NUMERO                     VARCHAR2(6 BYTE),
  ALTRI_CODICI               VARCHAR2(30 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE INC_USR.CONF_REP_LOG
(
  FLUSSO       VARCHAR2(50 BYTE),
  N_LOG        NUMBER,
  DESCRIZIONE  VARCHAR2(200 BYTE),
  ATTIVO       VARCHAR2(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN INC_USR.CONF_REP_LOG.FLUSSO IS 'Nome identificativo  del flusso';

COMMENT ON COLUMN INC_USR.CONF_REP_LOG.N_LOG IS 'Livello Log da 0  a 4';

COMMENT ON COLUMN INC_USR.CONF_REP_LOG.DESCRIZIONE IS 'descrizione livello log';

COMMENT ON COLUMN INC_USR.CONF_REP_LOG.ATTIVO IS 'Flag attivo Y or N';
CREATE TABLE INC_USR.LOG_REP_ERR
(
  ID              NUMBER(38),
  STATUS          VARCHAR2(250 BYTE),
  PROCEDURE_NAME  VARCHAR2(250 BYTE),
  ERROR_MESSAGE   VARCHAR2(4000 BYTE),
  NOTE            VARCHAR2(4000 BYTE),
  TYPE            VARCHAR2(250 BYTE),
  FLUSSO          VARCHAR2(250 BYTE),
  ESITO           VARCHAR2(250 BYTE),
  STEP_PROC       NUMBER(10,2),
  DATA_INSERT     DATE                          DEFAULT SYSDATE,
  ID_SESSIONE     NUMBER(38)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.ID IS 'Identificativo del record';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.PROCEDURE_NAME IS 'Nome  della procedura';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.ERROR_MESSAGE IS 'descrizione errore';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.NOTE IS 'Note';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.FLUSSO IS 'Identificativo flusso';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.STEP_PROC IS 'step della procedura';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.DATA_INSERT IS 'data inserimento record';

COMMENT ON COLUMN INC_USR.LOG_REP_ERR.ID_SESSIONE IS 'identificativo della sessione';
CREATE TABLE INC_USR.RUN_ESITO
(
  ID                   NUMBER                   DEFAULT "INC_USR"."REP_LOG_SEQ"."NEXTVAL",
  PROCEDURE_NAME       VARCHAR2(200 BYTE),
  FLUSSO               VARCHAR2(50 BYTE),
  ID_SESSIONE          NUMBER(38),
  ESITO                VARCHAR2(50 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  NOTE                 VARCHAR2(4000 BYTE),
  INIZIO_ELABORAZIONE  TIMESTAMP(6),
  FINE_ELABORAZIONE    TIMESTAMP(6)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE INC_USR.RUN_ESITO IS 'Tabella  equivalente alla REPORT_ESITO con tracciature agiguntive delle sotto componenti (SP) )di generazione del report.
Riportati anche parametri di input per l''invocazione del REPORT.';

COMMENT ON COLUMN INC_USR.RUN_ESITO.ID IS 'Identificativo del record';

COMMENT ON COLUMN INC_USR.RUN_ESITO.PROCEDURE_NAME IS 'nome della procedura';

COMMENT ON COLUMN INC_USR.RUN_ESITO.FLUSSO IS 'Nome identificativo del flusso';

COMMENT ON COLUMN INC_USR.RUN_ESITO.ID_SESSIONE IS 'Identificativo della sessione';

COMMENT ON COLUMN INC_USR.RUN_ESITO.ESITO IS 'Esito OK or KO';

COMMENT ON COLUMN INC_USR.RUN_ESITO.ERROR_MESSAGE IS 'Error';

COMMENT ON COLUMN INC_USR.RUN_ESITO.NOTE IS 'Note';

COMMENT ON COLUMN INC_USR.RUN_ESITO.INIZIO_ELABORAZIONE IS 'Data inizio flusso';

COMMENT ON COLUMN INC_USR.RUN_ESITO.FINE_ELABORAZIONE IS 'Data fine flusso';
CREATE TABLE INC_USR.LOAD_ESITO
(
  ID                   NUMBER                   DEFAULT "INC_USR"."LOAD_ESITO_SEQ"."NEXTVAL",
  FILE_NAME            VARCHAR2(100 BYTE)       NOT NULL,
  STATO                VARCHAR2(30 BYTE)        NOT NULL,
  ERROR_MESSAGE        VARCHAR2(100 BYTE),
  INIZIO_ELABORAZIONE  DATE                     DEFAULT SYSDATE,
  FINE_ELABORAZIONE    DATE,
  UTENTE               VARCHAR2(100 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE INC_USR.LOAD_ESITO ADD (
  CONSTRAINT LOAD_ESITO_C1
  CHECK (STATO IN ('CARICATO', 'IN_ELABORAZIONE','ELABORATO', 'ERRORE' ))
  ENABLE VALIDATE);
CREATE TABLE INC_USR.LOG_REP
(
  ID              NUMBER(38)                    NOT NULL,
  STATUS          VARCHAR2(50 BYTE)             NOT NULL,
  PROCEDURE_NAME  VARCHAR2(50 BYTE)             NOT NULL,
  ERROR_MESSAGE   VARCHAR2(4000 BYTE),
  NOTE            VARCHAR2(4000 BYTE),
  NOTE_C          CLOB,
  TYPE            VARCHAR2(30 BYTE)             NOT NULL,
  FLUSSO          VARCHAR2(50 BYTE)             NOT NULL,
  ESITO           VARCHAR2(50 BYTE)             NOT NULL,
  STEP_PROC       NUMBER(10,2),
  DATA_INSERT     DATE,
  ID_SESSIONE     NUMBER(38)                    NOT NULL
)
LOB (NOTE_C) STORE AS SECUREFILE (
  TABLESPACE  ANAG_USR
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN INC_USR.LOG_REP.ID IS 'Identificativo del record';

COMMENT ON COLUMN INC_USR.LOG_REP.STATUS IS 'STATUS IN (''IP'', ''INI'',''END'')';

COMMENT ON COLUMN INC_USR.LOG_REP.PROCEDURE_NAME IS 'Nome della procedura';

COMMENT ON COLUMN INC_USR.LOG_REP.ERROR_MESSAGE IS 'descrizione Errore -Warning';

COMMENT ON COLUMN INC_USR.LOG_REP.NOTE IS 'Note';

COMMENT ON COLUMN INC_USR.LOG_REP.NOTE_C IS 'Note Clob';

COMMENT ON COLUMN INC_USR.LOG_REP.TYPE IS 'TYPE IN (''ERROR GENERIC'',''ERROR'',''WARNING'',''INFO'')';

COMMENT ON COLUMN INC_USR.LOG_REP.FLUSSO IS 'Nome identificativo del flusso';

COMMENT ON COLUMN INC_USR.LOG_REP.ESITO IS 'ESITO IN (''OK'',''KO'')';

COMMENT ON COLUMN INC_USR.LOG_REP.STEP_PROC IS 'step della procedura ';

COMMENT ON COLUMN INC_USR.LOG_REP.DATA_INSERT IS 'Data inserimento record';

COMMENT ON COLUMN INC_USR.LOG_REP.ID_SESSIONE IS 'Identificativo della sessione';



CREATE INDEX INC_USR.REP_LOG_D1 ON INC_USR.LOG_REP
(ID_SESSIONE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INC_USR.REP_LOG_U1 ON INC_USR.LOG_REP
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE INC_USR.LOG_REP ADD (
  CONSTRAINT EREP_LOG_C3
  CHECK (ESITO IN ('OK','KO'))
  ENABLE VALIDATE,
  CONSTRAINT REP_LOG_C1
  CHECK (STATUS IN ('IP', 'INI','END'))
  ENABLE VALIDATE,
  CONSTRAINT REP_LOG_C2
  CHECK (TYPE IN ('ERROR GENERIC','ERROR','WARNING','INFO'))
  ENABLE VALIDATE);
CREATE TABLE INC_USR.LOAD_INCIDENTI_FILE_TMP
(
  DATA_LOAD_FILE  DATE,
  NOME_FILE       VARCHAR2(50 BYTE)             NOT NULL,
  NUM_RIGA        NUMBER                        NOT NULL,
  RECORD          VARCHAR2(4000 BYTE)           NOT NULL
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE INC_USR.LOAD_INCIDENTI_FILE
(
  DATA_LOAD_FILE  DATE                          DEFAULT SYSDATE,
  NOME_FILE       VARCHAR2(50 BYTE)             NOT NULL,
  NUM_RIGA        NUMBER,
  RECORD          VARCHAR2(4000 BYTE)           NOT NULL
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM STAT_USR.LOAD_INCIDENTI_FILE FOR INC_USR.LOAD_INCIDENTI_FILE;


GRANT DELETE, INSERT, SELECT, UPDATE ON INC_USR.LOAD_INCIDENTI_FILE TO STAT_USR;
CREATE TABLE INC_USR.REP_INCIDENTI
(
  ANNO                            VARCHAR2(4 BYTE),
  N_INCIDENTI_S1                  NUMBER(10),
  N_INDICE_S1                     NUMBER(7,2),
  N_INDICE_MORTALITA_S2           NUMBER(7,2),
  N_MORTI_S2                      NUMBER(10),
  MESE_S3                         NUMBER(2),
  N_INCIDENTI_S3                  NUMBER(8),
  N_MORTI_S3                      NUMBER(8),
  N_FERITI_S3                     NUMBER(8),
  N_PERC_INCIDETI_S3              NUMBER(7,2),
  N_PERC_MORTI_S3                 NUMBER(7,2),
  N_PERC_FERITI_S3                NUMBER(7,2),
  MESE_S4A                        NUMBER(2),
  GIORNO_SETTIMANA_S6             VARCHAR2(50 BYTE),
  N_INCIDENTI_S6                  NUMBER(8),
  N_PERC_INCIDENTI_S6             NUMBER(7,2),
  GIORNO_SETTIMANA_S7             VARCHAR2(50 BYTE),
  N_INC_FASCIA_ORARIO_0_6_S7      NUMBER(8),
  N_INC_FASCIA_ORARIO_7_9_S7      NUMBER(8),
  N_INC_FASCIA_ORARIO_10_13_S7    NUMBER(8),
  N_INC_FASCIA_ORARIO_14_17_S7    NUMBER(8),
  N_INC_FASCIA_ORARIO_18_20_S7    NUMBER(8),
  N_INC_FASCIA_ORARIO_21_24_S7    NUMBER(8),
  GIORNO_SETTIMANA_S8             VARCHAR2(50 BYTE),
  N_MORTI_FASCIA_ORARIO_0_6_S8    NUMBER(8),
  N_MORTI_FASCIA_ORARIO_7_9_S8    NUMBER(8),
  N_MORTI_FASCIA_ORARIO_10_13_S8  NUMBER(8),
  N_MORTI_FASCIA_ORARIO_14_17_S8  NUMBER(8),
  N_MORTI_FASCIA_ORARIO_18_20_S8  NUMBER(8),
  N_MORTI_FASCIA_ORARIO_21_24_S8  NUMBER(8),
  GIORNO_SETTIMANA_S9             VARCHAR2(50 BYTE),
  N_FER_FASCIA_ORARIO_0_6_S9      NUMBER(8),
  N_FER_FASCIA_ORARIO_7_9_S9      NUMBER(8),
  N_FER_FASCIA_ORARIO_10_13_S9    NUMBER(8),
  N_FER_FASCIA_ORARIO_14_17_S9    NUMBER(8),
  N_FER_FASCIA_ORARIO_18_20_S9    NUMBER(8),
  N_FER_FASCIA_ORARIO_21_24_S9    NUMBER(8),
  TIPO_VEICOLO_S10                VARCHAR2(50 BYTE),
  N_FERITI_13_S10                 NUMBER,
  N_FERITI_14_17_S10              NUMBER,
  N_FERITI_18_29_S10              NUMBER,
  N_FERITI_30_54_S10              NUMBER,
  N_FERITI_55_64_S10              NUMBER,
  N_FERITI_65_OL_S10              NUMBER,
  N_FERITI_65_NI_S10              NUMBER,
  TIPO_STRADA_S11                 VARCHAR2(50 BYTE),
  N_INCIDENTI_S11                 NUMBER(8),
  N_MORTI_S11                     NUMBER(8),
  N_FERITI_S11                    NUMBER(8),
  N_IND_MORTALITA_S11             NUMBER(7,2),
  N_IND_GRAVITA_S11               NUMBER(7,2),
  N_FER_FASCIA_ORARIO_18_20_S5A   NUMBER(8),
  TIPO_PERSONA_S5A                VARCHAR2(50 BYTE),
  N_FERITI_13_S5A                 NUMBER(8),
  N_FERITI_14_17_S5A              NUMBER(8),
  N_FERITI_18_29_S5A              NUMBER(8),
  N_FERITI_30_54_S5A              NUMBER(8),
  N_FERITI_55_64_S5A              NUMBER(8),
  N_FERITI_65_OL_S5A              NUMBER(8),
  N_FERITI_NI_S5A                 NUMBER(8),
  TIPO_PERSONA_S5B                VARCHAR2(50 BYTE),
  N_MORTI_13_S5B                  NUMBER(8),
  N_MORTI_14_17_S5B               NUMBER(8),
  N_MORTI_18_29_S5B               NUMBER(8),
  N_MORTI_30_54_S5B               NUMBER(8),
  N_MORTI_55_64_S5B               NUMBER(8),
  N_MORTI_65_OL_S5B               NUMBER(8),
  N_MORTI_NI_S5B                  NUMBER(8),
  N_INDICE_MORTALITA_S3           NUMBER GENERATED ALWAYS AS (NVL("N_MORTI_S3",0)/"N_INCIDENTI_S3"*100),
  N_INDICE_LESIVITA_S3            NUMBER GENERATED ALWAYS AS (NVL("N_FERITI_S3",0)/"N_INCIDENTI_S3"*100),
  N_INDICE_GRAVITA_S3             NUMBER GENERATED ALWAYS AS (NVL("N_MORTI_S3",0)/("N_MORTI_S3"+"N_FERITI_S3")*100),
  ID_SHEETS                       VARCHAR2(20 BYTE),
  N_INC_METEO_SERENO_S4A          NUMBER(8),
  N_INC_METEO_NEBBIA_S4A          NUMBER(8),
  N_INC_METEO_PIOGGIA_S4A         NUMBER(8),
  N_INC_METEO_GRADINE_S4A         NUMBER(8),
  N_INC_METEO_NEVE_S4A            NUMBER(8),
  N_INC_METEO_VENTO_FORTE_S4A     NUMBER(8),
  N_INC_METEO_ALTRO_S4A           NUMBER(8),
  N_INC_METEO_TOTALE_S4A          NUMBER(8),
  MESE_S4B                        NUMBER(2),
  N_MORTI_METEO_SERENO_S4B        NUMBER(8),
  N_MORTI_METEO_NEBBIA_S4B        NUMBER(8),
  N_MORTI_METEO_PIOGGIA_S4B       NUMBER(8),
  N_MORTI_METEO_GRADINE_S4B       NUMBER(8),
  N_MORTI_METEO_NEVE_S4B          NUMBER(8),
  N_MORTI_METEO_VENTO_FORTE_S4B   NUMBER(8),
  N_MORTI_METEO_ALTRO_S4B         NUMBER(8),
  N_MORTI_METEO_TOTALE_S4B        NUMBER(8),
  N_MORTI_CONDUCENTE_S5B          NUMBER,
  N_MORTI_PASSEGGERI_S5B          NUMBER,
  N_MORTI_PEDONE_S5B              NUMBER,
  N_MORTI_ALTRI_S5B               NUMBER,
  FASCE_ETA_S5B                   VARCHAR2(50 BYTE),
  N_MORTI_NON_DEFINITO_S5B        NUMBER,
  N_FERITI_CONDUCENTE_S5A         NUMBER,
  N_FERITI_PASSEGGERI_S5A         NUMBER,
  N_FERITI_PEDONE_S5A             NUMBER,
  N_FERITI_ALTRI_S5A              NUMBER,
  N_FERITI_NON_DEFINITO_S5A       NUMBER,
  FASCE_ETA_S5A                   VARCHAR2(50 BYTE),
  N_INC_METEO_NON_CENSITO_S4A     NUMBER,
  N_MORTI_METEO_NON_CENSITO_S4B   NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON INC_USR.REP_INCIDENTI TO STAT_USR;
CREATE GLOBAL TEMPORARY TABLE INC_USR.GTT_INC_MORTI
(
  TIPO_PERSONA     VARCHAR2(50 BYTE),
  CLASSE           VARCHAR2(20 BYTE),
  NUMERO_MORTI     INTEGER,
  ETA              VARCHAR2(2 BYTE),
  FASCE_ETA        VARCHAR2(50 BYTE),
  FASCE_ETA_NUOVA  VARCHAR2(50 BYTE),
  ID_INCIDENTE     INTEGER                      NOT NULL,
  ANNO             VARCHAR2(4 BYTE)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;
CREATE TABLE INC_USR.TMP_INC
(
  TIPO_PERSONA     VARCHAR2(50 BYTE),
  CLASSE           VARCHAR2(20 BYTE),
  NUMERO_MORTI     INTEGER,
  ETA              NUMBER,
  FASCE_ETA        VARCHAR2(50 BYTE),
  FASCE_ETA_NUOVA  VARCHAR2(50 BYTE),
  ID_INCIDENTE     INTEGER                      NOT NULL
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE GLOBAL TEMPORARY TABLE INC_USR.GTT_INC_FERITI
(
  ANNO             VARCHAR2(4 BYTE),
  TIPO_PERSONA     VARCHAR2(50 BYTE),
  CLASSE           VARCHAR2(20 BYTE),
  NUMERO_FERITI    INTEGER,
  ETA              VARCHAR2(2 BYTE),
  FASCE_ETA        VARCHAR2(50 BYTE),
  FASCE_ETA_NUOVA  VARCHAR2(50 BYTE),
  ID_INCIDENTE     INTEGER                      NOT NULL
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;
CREATE TABLE INC_USR.DIM_MESE
(
  MESE     VARCHAR2(2 BYTE),
  DESCRIZ  VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE INC_USR.DIM_SETTIMANA
(
  GIORNO  VARCHAR2(30 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
