CREATE TABLE MIGR_USR.ST_ATTO_EXTEND
(
  ID_ATTO       NUMBER                          NOT NULL,
  ID_EXT_FIELD  VARCHAR2(50 BYTE)               NOT NULL,
  VALUE         VARCHAR2(100 BYTE),
  DATA_UPD      DATE                            DEFAULT SYSDATE,
  MIG_ID        NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.ST_ATTO_EXTEND IS 'Tabella per estendere field della tabella master ATTO';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_EXTEND.ID_ATTO IS 'ID ATTO a cui sono correlati gli EXTENDED FIELDS';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_EXTEND.ID_EXT_FIELD IS 'ID dell''EXTENDED FIELD';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_EXTEND.VALUE IS 'Valore del campo';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_EXTEND.DATA_UPD IS 'Ultimo aggiornamento del campo';



CREATE UNIQUE INDEX MIGR_USR.ATTO_EXTEND_PK ON MIGR_USR.ST_ATTO_EXTEND
(ID_ATTO, ID_EXT_FIELD)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.ST_ATTO_EXTEND ADD (
  CONSTRAINT ATTO_EXTEND_PK
  PRIMARY KEY
  (ID_ATTO, ID_EXT_FIELD)
  USING INDEX MIGR_USR.ATTO_EXTEND_PK
  ENABLE VALIDATE);

ALTER TABLE MIGR_USR.ST_ATTO_EXTEND ADD (
  CONSTRAINT ATTO_EXTEND_FK 
  FOREIGN KEY (ID_ATTO) 
  REFERENCES MIGR_USR.ST_ATTO (ID_ATTO)
  ENABLE VALIDATE,
  CONSTRAINT ATTO_EXTEND_FK2 
  FOREIGN KEY (ID_EXT_FIELD) 
  REFERENCES MIGR_USR.M_CFG_EXTENDED_FIELDS (ID)
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.M_CFG_FT
(
  ID           NUMBER(38)                       NOT NULL,
  FLUSSO       VARCHAR2(50 BYTE)                NOT NULL,
  DATA_INIZIO  DATE                             NOT NULL,
  DATA_FINE    DATE                             NOT NULL,
  FLG_ATTIVO   VARCHAR2(1 BYTE)                 NOT NULL
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.M_CFG_FT IS 'Tabella configurazione per flussi di migrazione';

COMMENT ON COLUMN MIGR_USR.M_CFG_FT.ID IS 'Identificativo del record';

COMMENT ON COLUMN MIGR_USR.M_CFG_FT.FLUSSO IS 'Nome del FLUSSO MIGR_';

COMMENT ON COLUMN MIGR_USR.M_CFG_FT.DATA_INIZIO IS 'Data inizio estrazione del delta';

COMMENT ON COLUMN MIGR_USR.M_CFG_FT.DATA_FINE IS 'Data fine estrazione del delta';

COMMENT ON COLUMN MIGR_USR.M_CFG_FT.FLG_ATTIVO IS 'Flag attivo Y or N';



CREATE UNIQUE INDEX MIGR_USR.M_CFG_FT_U1 ON MIGR_USR.M_CFG_FT
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MIGR_USR.M_CFG_FT_U2 ON MIGR_USR.M_CFG_FT
(FLUSSO, FLG_ATTIVO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
CREATE TABLE MIGR_USR.M_CFG_LOG
(
  FLUSSO       VARCHAR2(50 BYTE),
  N_LOG        NUMBER,
  DESCRIZIONE  VARCHAR2(200 BYTE),
  ATTIVO       VARCHAR2(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.M_CFG_LOG IS 'La tabella contiene info relative ai livello di log dei flussi';

COMMENT ON COLUMN MIGR_USR.M_CFG_LOG.FLUSSO IS 'Nome identificativo  del flusso';

COMMENT ON COLUMN MIGR_USR.M_CFG_LOG.N_LOG IS 'Livello Log da 0  a 4';

COMMENT ON COLUMN MIGR_USR.M_CFG_LOG.DESCRIZIONE IS 'descrizione livello log';

COMMENT ON COLUMN MIGR_USR.M_CFG_LOG.ATTIVO IS 'Flag attivo Y or N';



CREATE UNIQUE INDEX MIGR_USR.M_CFG_LOG_U1 ON MIGR_USR.M_CFG_LOG
(FLUSSO, N_LOG)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
CREATE TABLE MIGR_USR.M_LOG
(
  ID              NUMBER(38),
  STATUS          VARCHAR2(50 BYTE)             NOT NULL,
  PROCEDURE_NAME  VARCHAR2(50 BYTE)             NOT NULL,
  ERROR_MESSAGE   VARCHAR2(4000 BYTE),
  NOTE            VARCHAR2(4000 BYTE),
  NOTE_C          CLOB,
  TYPE            VARCHAR2(30 BYTE)             NOT NULL,
  FLUSSO          VARCHAR2(50 BYTE)             NOT NULL,
  ESITO           VARCHAR2(50 BYTE)             NOT NULL,
  STEP_PROC       NUMBER(10,2),
  DATA_INSERT     DATE,
  ID_SESSIONE     NUMBER(38)                    NOT NULL,
  MIG_ID          NUMBER
)
LOB (NOTE_C) STORE AS SECUREFILE (
  TABLESPACE  ANAG_USR
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.M_LOG IS 'La tabella di log dei flussi di migrazione';

COMMENT ON COLUMN MIGR_USR.M_LOG.ID IS 'Identificativo del record';

COMMENT ON COLUMN MIGR_USR.M_LOG.STATUS IS 'STATUS IN (''IP'', ''INI'',''END'')';

COMMENT ON COLUMN MIGR_USR.M_LOG.PROCEDURE_NAME IS 'Nome della procedura';

COMMENT ON COLUMN MIGR_USR.M_LOG.ERROR_MESSAGE IS 'descrizione Errore -Warning';

COMMENT ON COLUMN MIGR_USR.M_LOG.NOTE IS 'Note';

COMMENT ON COLUMN MIGR_USR.M_LOG.NOTE_C IS 'Note Clob';

COMMENT ON COLUMN MIGR_USR.M_LOG.TYPE IS 'TYPE IN (''ERROR GENERIC'',''ERROR'',''WARNING'',''INFO'')';

COMMENT ON COLUMN MIGR_USR.M_LOG.FLUSSO IS 'Nome identificativo del flusso';

COMMENT ON COLUMN MIGR_USR.M_LOG.ESITO IS 'ESITO IN (''OK'',''KO'')';

COMMENT ON COLUMN MIGR_USR.M_LOG.STEP_PROC IS 'step della procedura ';

COMMENT ON COLUMN MIGR_USR.M_LOG.DATA_INSERT IS 'Data inserimento record';

COMMENT ON COLUMN MIGR_USR.M_LOG.ID_SESSIONE IS 'Identificativo della sessione';

COMMENT ON COLUMN MIGR_USR.M_LOG.MIG_ID IS 'Identificativo della record di migrazione';



CREATE INDEX MIGR_USR.M_LOG_D1 ON MIGR_USR.M_LOG
(ID_SESSIONE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MIGR_USR.M_LOG_U1 ON MIGR_USR.M_LOG
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.M_LOG ADD (
  CONSTRAINT M_LOG_C1
  CHECK (STATUS IN ('IP', 'INI','END'))
  ENABLE VALIDATE,
  CONSTRAINT M_LOG_C2
  CHECK (TYPE IN ('ERROR GENERIC','ERROR','WARNING','INFO'))
  ENABLE VALIDATE,
  CONSTRAINT M_LOG_C3
  CHECK (ESITO IN ('OK','KO'))
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.M_LOG_ERR
(
  ID              NUMBER(38)                    NOT NULL,
  PROCEDURE_NAME  VARCHAR2(50 BYTE)             NOT NULL,
  ERROR_MESSAGE   VARCHAR2(4000 BYTE),
  NOTE            VARCHAR2(4000 BYTE),
  FLUSSO          VARCHAR2(50 BYTE)             NOT NULL,
  STEP_PROC       NUMBER(10,2),
  DATA_INSERT     DATE,
  ID_SESSIONE     NUMBER(38)                    NOT NULL,
  MIG_ID          NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.M_LOG_ERR IS 'La tabella contiene i record scartati dall''inserimento in M_LOG dei flussi di migrazione';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.ID IS 'Identificativo del record';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.PROCEDURE_NAME IS 'Nome  della procedura';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.ERROR_MESSAGE IS 'descrizione errore';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.NOTE IS 'Note';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.FLUSSO IS 'Identificativo flusso';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.STEP_PROC IS 'step della procedura';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.DATA_INSERT IS 'data inserimento record';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.ID_SESSIONE IS 'identificativo della sessione';

COMMENT ON COLUMN MIGR_USR.M_LOG_ERR.MIG_ID IS 'Identificativo della record di migrazione';
CREATE TABLE MIGR_USR.M_RUN_ESITO
(
  ID                   NUMBER                   DEFAULT MIGR_USR.M_LOG_SEQ.NEXTVAL NOT NULL,
  PROCEDURE_NAME       VARCHAR2(200 BYTE),
  FLUSSO               VARCHAR2(50 BYTE),
  ID_SESSIONE          NUMBER(38),
  ESITO                VARCHAR2(50 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  NOTE                 VARCHAR2(4000 BYTE),
  INIZIO_ELABORAZIONE  TIMESTAMP(6),
  FINE_ELABORAZIONE    TIMESTAMP(6)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.M_RUN_ESITO IS 'Tabella esito/tempi esecuzione dei flussi di migrazione';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.ID IS 'Identificativo del record';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.PROCEDURE_NAME IS 'nome della procedura';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.FLUSSO IS 'Nome identificativo del flusso';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.ID_SESSIONE IS 'Identificativo della sessione';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.ESITO IS 'Esito OK or KO';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.ERROR_MESSAGE IS 'Error';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.NOTE IS 'Note';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.INIZIO_ELABORAZIONE IS 'Data inizio flusso';

COMMENT ON COLUMN MIGR_USR.M_RUN_ESITO.FINE_ELABORAZIONE IS 'Data fine flusso';



CREATE INDEX MIGR_USR.M_RUN_ESITO_D1 ON MIGR_USR.M_RUN_ESITO
(PROCEDURE_NAME, FLUSSO, ID_SESSIONE)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
CREATE TABLE MIGR_USR.ST_SOGGETTO
(
  ID_SOGGETTO                NUMBER             DEFAULT "MATR_USR".SEQ_ID_SOGGETTO_STATOCIVILE.nextval NOT NULL,
  NOME                       VARCHAR2(250 BYTE) NOT NULL,
  COGNOME                    VARCHAR2(250 BYTE) NOT NULL,
  SESSO                      CHAR(1 BYTE)       NOT NULL,
  CODICE_FISCALE             VARCHAR2(16 BYTE),
  CODICE_INDIVIDUALE         VARCHAR2(20 BYTE),
  NUMERO_CARTA_IDENTITA      VARCHAR2(20 BYTE),
  DATA_ULTIMO_AGGIORNAMENTO  DATE               DEFAULT SYSDATE               NOT NULL,
  DETTAGLIO_STATOCIVILE      CLOB               NOT NULL,
  DATA_NASCITA               DATE,
  DATA_INS                   TIMESTAMP(6)       DEFAULT SYSTIMESTAMP          NOT NULL,
  DATA_UPD                   TIMESTAMP(6)       DEFAULT SYSTIMESTAMP          NOT NULL,
  MIG_NUMERO_ATTO            VARCHAR2(9 BYTE),
  MIG_ANNO_ATTO              VARCHAR2(4 BYTE),
  MIG_TIPO_SOGGETTO          VARCHAR2(30 BYTE),
  MIG_ID                     NUMBER
)
LOB (DETTAGLIO_STATOCIVILE) STORE AS SECUREFILE (
  TABLESPACE  ANAG_USR
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.ID_SOGGETTO IS 'Identificativo del soggetto - autogenerato';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.NOME IS 'Nome del soggetto.
';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.COGNOME IS 'Cognome del soggetto.';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.SESSO IS 'Sesso del soggetto';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.CODICE_FISCALE IS 'Codice fiscale del soggetto.';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.CODICE_INDIVIDUALE IS 'Codice  utilizzato in APR per identificare univocamente il soggetto.';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.NUMERO_CARTA_IDENTITA IS 'Codice identificativo della carta d''identità o altro documento di riconoscimento associata al soggetto';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.DATA_ULTIMO_AGGIORNAMENTO IS 'data in cui la scheda il  soggetto ha subito l''ultimo aggiornamento nel contesto dello stato civile';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.DETTAGLIO_STATOCIVILE IS 'Conterrà tutti i dati di dettaglio anagrafici previsti come dati temporanei anagrafici
';

COMMENT ON COLUMN MIGR_USR.ST_SOGGETTO.DATA_NASCITA IS 'Data di nascita - NULLABLE per gestire casistiche Plurilingue ed altro con ETA'' al posto della data di nascita';



CREATE UNIQUE INDEX MIGR_USR.SOGGETTO_PK ON MIGR_USR.ST_SOGGETTO
(ID_SOGGETTO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.ST_SOGGETTO ADD (
  CONSTRAINT SOGGETTO_PK
  PRIMARY KEY
  (ID_SOGGETTO)
  USING INDEX MIGR_USR.SOGGETTO_PK
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.TMP
(
  ID_ATTO       NUMBER                          NOT NULL,
  ID_EXT_FIELD  VARCHAR2(50 BYTE)               NOT NULL,
  VALUE         VARCHAR2(100 BYTE),
  DATA_UPD      DATE,
  MIG_ID        NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.ST_ATTO
(
  ID_ATTO                     NUMBER            DEFAULT "MIGR_USR"."M_ATTO_NASCITA_SEQ"."NEXTVAL" NOT NULL,
  ID_COMUNE_ISCRIZIONE        NUMBER,
  NUMERO_ATTO                 VARCHAR2(20 BYTE),
  ANNO                        NUMBER(4),
  PARTE                       VARCHAR2(5 BYTE),
  SERIE                       VARCHAR2(10 BYTE),
  VOLUME                      VARCHAR2(5 BYTE),
  UFFICIO                     VARCHAR2(50 BYTE),
  TRASCRITTO                  NUMBER            NOT NULL,
  TIPO_PROTOCOLLO             VARCHAR2(10 BYTE),
  NUMERO_PROTOCOLLO           NUMBER,
  ANNO_PROTOCOLLO             NUMBER(4),
  ANNO_PRATICA                NUMBER(4),
  ID_STATO_PRATICA            NUMBER,
  ID_TIPO_ATTO                INTEGER           NOT NULL,
  CODICE_TIPO_PROTOCOLLO      VARCHAR2(10 BYTE),
  ID_COMUNE_TRASCRIZIONE      NUMBER,
  ESPONENTE                   VARCHAR2(20 BYTE),
  DATA_INS_ATTO               TIMESTAMP(6)      DEFAULT SYSTIMESTAMP          NOT NULL,
  DATA_UPD_ATTO               TIMESTAMP(6)      DEFAULT SYSTIMESTAMP          NOT NULL,
  DATA_CANCELLAZIONE_ATTO     DATE,
  DATA_ANNULLAMENTO_ATTO      DATE,
  MOTIVO_ANNULLAMENTO_ATTO    VARCHAR2(500 BYTE),
  MOTIVO_CANCELLAZIONE_ATTO   VARCHAR2(500 BYTE),
  DATA_ATTO_TRASCRIZIONE      DATE,
  DATA_RILASCIO               DATE,
  ID_USC_TRASCRIZIONE         NUMBER,
  ID_UTENTE                   NUMBER            NOT NULL,
  ID_ORGANIZZAZIONE           NUMBER            NOT NULL,
  AREA                        VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL,
  PARTE_SERIE                 VARCHAR2(15 BYTE) GENERATED ALWAYS AS ("PARTE"||"SERIE"),
  NUMESTESO_ATTO              VARCHAR2(77 BYTE) GENERATED ALWAYS AS (TO_CHAR("ANNO")||'/'||"PARTE"||"SERIE"||'/'||"NUMERO_ATTO"),
  OCCHIO_DOCUMENTO            CHAR(1 BYTE)      DEFAULT 'S'                   NOT NULL,
  ATTO_TRASCR_ANNO            NUMBER(4),
  ATTO_TRASCR_NUMEROATTO      VARCHAR2(20 BYTE),
  ATTO_TRASCR_PARTE           VARCHAR2(5 BYTE),
  ATTO_TRASCR_SERIE           VARCHAR2(10 BYTE),
  ATTO_TRASCR_DATA            DATE,
  ATTO_TRASCR_NOTA_UFFICIALE  VARCHAR2(4000 BYTE),
  DATA_PROTOCOLLO             DATE,
  ATTO_TRASCR_ESPONENTE       VARCHAR2(20 BYTE),
  DATA_PRATICA                DATE              DEFAULT SYSDATE               NOT NULL,
  NUMERO_PRATICA              VARCHAR2(20 BYTE),
  ATTO_TRASCR_DATAISCR        DATE,
  ATTO_TRASCR_DATAPROT_ISCR   DATE,
  ATTO_TRASCR_USC             VARCHAR2(100 BYTE),
  STEP_LAVORAZIONE            NUMBER            DEFAULT NULL,
  ID_LAVORAZIONE_PADRE        NUMBER,
  STEP_TABLAV                 CHAR(1 BYTE),
  FLG_RETTIFICA_INCORSO       CHAR(1 BYTE)      DEFAULT 'N',
  FLG_ATTO_TESTOLIBERO        CHAR(1 BYTE)      DEFAULT 'N',
  MIG_ID                      NUMBER,
  COLUMN2                     VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.ST_ATTO IS 'La tabella contiene le informazioni rilevanti (es. anno, parte, serie, volume, ecc.) relative ad un atto di stato civile.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_ATTO IS 'Campo che indica l''id dell''atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_COMUNE_ISCRIZIONE IS 'ATTO TRASCRITTO: Indica il comune in cui si è registratp/iscritto l''atto originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.NUMERO_ATTO IS 'Campo che indica il numero dell''atto. MAX 5 CIFRE';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ANNO IS 'Campo che indica l''anno in cui si registra l''atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.PARTE IS 'Campo che indica il numero della parte dell''atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.SERIE IS 'Campo che indica la serie dell''atto. Formato 3 CARATTERI: <LETTERA><ESPONENTE>';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.VOLUME IS 'Campo che indica il volume dove si trova l''atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.UFFICIO IS 'Campo che indica l''ufficio in cui si registra l''atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.TRASCRITTO IS 'Flag che indica se l''atto è iscritto o trascritto.
0 se iscritto (originale), 1 se trascritto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.TIPO_PROTOCOLLO IS 'Codice che identific univocamente l''ente protocollante dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.NUMERO_PROTOCOLLO IS 'Campo che indica il numero del protocollo.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ANNO_PROTOCOLLO IS 'Campo che indica l''anno del protocollo.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ANNO_PRATICA IS 'Campo che indica il l''anno della pratica.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_STATO_PRATICA IS 'Campo che indica lo stato della pratica.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_TIPO_ATTO IS 'Codice identificativo della tipologia di atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.CODICE_TIPO_PROTOCOLLO IS 'Codice identificativo dell''ente protocollante dell''atto.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_COMUNE_TRASCRIZIONE IS 'ATTO_TRASCRITTO:  NON UTILIZZARE  - Comune dove è stato trascritto. POtenzialmente inutile da riportare';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ESPONENTE IS 'Campo che indica l''esponente dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_INS_ATTO IS 'DATA INSERIMENTO PRATICA';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_UPD_ATTO IS 'Ultima data di aggiornamento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_CANCELLAZIONE_ATTO IS 'Data di cancellazione dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_ANNULLAMENTO_ATTO IS 'Data di annullamento dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.MOTIVO_ANNULLAMENTO_ATTO IS 'Motivo di annullamento dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.MOTIVO_CANCELLAZIONE_ATTO IS 'Motivo di cancellazione dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_ATTO_TRASCRIZIONE IS 'Data di trascrizione dell''ATTO';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_RILASCIO IS 'Data di rilascio/iscrizione dell''ATTO 
Data Verbale (per verbali UNIONI CIVILI)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_USC_TRASCRIZIONE IS 'Ufficiale di Stato Civile che ha trascritto l''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_UTENTE IS 'Utente di Anagrafe o Municipio che ha stipulato l''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_ORGANIZZAZIONE IS 'Organizzazione di appartenenza dell''utente che ha lavorato l''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.AREA IS 'AREA dello stato civile';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.PARTE_SERIE IS 'Campo derivato da PARTE||SERIE';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.NUMESTESO_ATTO IS 'Numero ATTO ESTESO (ANNO/PARTESERIE/NUMERO_ATTO)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.OCCHIO_DOCUMENTO IS 'Occhio del documento ATTO a [D]ESTRA o a [S]INISTRA (default).';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_ANNO IS 'ATTO TRASCRITTO: Campo che indica l''anno in cui si registra l''atto originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_NUMEROATTO IS 'ATTO TRASCRITTO: Campo che indica il numero dell''atto originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_PARTE IS 'ATTO TRASCRITTO: Campo che indica il numero della parte dell''atto originario.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_SERIE IS 'ATTO TRASCRITTO: Campo che indica la serie dell''atto originario.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_DATA IS 'OBSOLETO GIA PRESENTE ATTO_TRASCR_DATAISCR
 - 
ATTO TRASCRITTO: Data di Iscrizione dell''ATTO originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_NOTA_UFFICIALE IS 'ATTO_TRASCRITTO: Eventuale dettaglio relativo all''uffciale dell''atto iscritto/ Note su ATTO TRASCRITTO';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_PROTOCOLLO IS 'Data protocollo dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_ESPONENTE IS 'ATTO_TRASCRITTO: Eventuale Esponente relativo all''atto iscritto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.DATA_PRATICA IS 'Data prima accoglimento della Pratica/Inizio lavorazioni - differisce dalla data dell''Atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.NUMERO_PRATICA IS 'Numero pratica di lavorazione - impostata come numero incrementale per ANNO_PRATICA';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_DATAISCR IS 'ATTO TRASCRITTO: Data di Iscrizione dell''ATTO originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_DATAPROT_ISCR IS 'ATTO TRASCRITTO: Data Protocollo di Iscrizione dell''ATTO originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ATTO_TRASCR_USC IS 'ATTO TRASCRITTO: USC che ha iscritto l''ATTO originario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.STEP_LAVORAZIONE IS 'Step corrente di lavorazione di un ATTO di CITTADINANZA. Utilizzato da Gestione ATTI di CITTADINANZA per capire da dove riprendere la lavorazione interrotta.
ASSUMERA'' 0 quando tutti gli STEP si saranno conclusi sull''ATTO DI PARTENZA
ASSUMERA'' VALORE n se ATTO di PARTENZA è allo step n e quindi sono stati creati ATTI clonati per gli step 1 a n-1 (con segno negativo sul loro rispettivo STEP_LAVORAZIONE).
ASSUMERA'' VALORE -n se ATTO clonato e creato per STEP n dell''ATTO di PARTENZA. puntato da ATTO_CITTADINANZA.ID_LAVORAZIONE_PADRE
ASSUMERA'' sempre NULL per ATTI/PRATICHE ove lo step lavorazione non viene preso in considerazione...Es. Non di cittadinanza.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.ID_LAVORAZIONE_PADRE IS 'CITTADINANZE: ID_ATTO dell''ATTO di PARTENZA nel caso di lavorazioni multistep come in CITTADINANZE. L''ATTO puntato dovrebbe essere sempre con STEP_LAVORAZIONE >=0. mentre quello corrente con STEP_LAVORAZIONE <0. 
DIVORZI: NEL CASO DI DIVORZI VIENE UTILIZZATO PER CENSIRE L''ATTO PADRE DI ACCORDO NEL CASO DI CONFERMA O MANCATA CONFERMA DELL''ACCORDO.
NASCITE: PRATICA DI RICHIESTA ATTO corrispondente a quella del primogenito. registrata in fase di DEFINIZIONE/splitting degli ATTI figli per singolo gemello. Per ogni GEMELLO/FIGLIO si produrrà un ATTO clone (OGNUNO CON PROPRIO ATTO_NASCITA_SOGGETTO) - CENSITO SOLO SUI SINGOLI ATTI FIGLI (escluso primogenito)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.STEP_TABLAV IS 'Numero del TAB ove riprendere nel caso di maschere di dataentry tra il verbale e l''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.FLG_RETTIFICA_INCORSO IS 'FLAG CHE IDENTIFICA SE UN ATTO IN CORSO DI RETTIFICA O SPLITTATO PRIMA DELL''ANTEPRIMA ATTO.
RETTIFICA: LO STATO DA "DEFINITO" RITORNA A "IN LAVORAZIONE". NEL CASO DI NASCITE VIENE UTILIZZATO PER BLOCCARE COMBO SUL NUMERO DI GEMELLLI.
SPLITTING: lO SPLITTING APPLICATO SULLA RIEPILOGO ATTO/PRATICA NON E'' ROLLBACKABILE.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO.FLG_ATTO_TESTOLIBERO IS 'FLAG CHE IDENTIFICA SE L''ATTO E'' STATO GENERATO COME ATTO A TESTO LIBERO QUINDI L''ANTEPRIMA ATTO HA COMPORTAMENTO DIVERSO NELLA GENERAZIONE DEL FORMULARIO.ANCHE L''ID_TIPO_ATTO NON SARA'' SIGNIFICATIVO PER IL FORMULARIO CHE PRENDERA'' UN MODELLO DIVERSO PER L''ATTO LIBERO.';



CREATE INDEX MIGR_USR.ATTO_IX1 ON MIGR_USR.ST_ATTO
(ANNO, PARTE, SERIE, ESPONENTE, AREA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX MIGR_USR.ATTO_NUMERO_ESTESO_ATTO ON MIGR_USR.ST_ATTO
(NUMESTESO_ATTO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MIGR_USR.ATTO_PK ON MIGR_USR.ST_ATTO
(ID_ATTO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MIGR_USR.ATTO_UK1 ON MIGR_USR.ST_ATTO
(AREA, ANNO, PARTE_SERIE, NUMERO_ATTO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MIGR_USR.ATTO_UX1 ON MIGR_USR.ST_ATTO
(CODICE_TIPO_PROTOCOLLO, ANNO_PROTOCOLLO, NUMERO_PROTOCOLLO)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.ST_ATTO ADD (
  CONSTRAINT ATTO_PK
  PRIMARY KEY
  (ID_ATTO)
  USING INDEX MIGR_USR.ATTO_PK
  ENABLE VALIDATE,
  CONSTRAINT ATTO_UK1
  UNIQUE (AREA, ANNO, PARTE_SERIE, NUMERO_ATTO)
  USING INDEX MIGR_USR.ATTO_UK1
  ENABLE VALIDATE,
  CONSTRAINT ATTO_UX1
  UNIQUE (CODICE_TIPO_PROTOCOLLO, ANNO_PROTOCOLLO, NUMERO_PROTOCOLLO)
  USING INDEX MIGR_USR.ATTO_UX1
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.ST_ATTO_NASCITA
(
  ID_ATTO_NASCITA                 NUMBER        NOT NULL,
  DATA_INS                        TIMESTAMP(6)  DEFAULT SYSTIMESTAMP          NOT NULL,
  DATA_UPD                        TIMESTAMP(6)  DEFAULT SYSTIMESTAMP          NOT NULL,
  ID_SOGGETTO_GEN1                NUMBER,
  ID_SOGGETTO_GEN2                NUMBER,
  ID_SOGGETTO_DICH                NUMBER,
  MADRE_NOME                      VARCHAR2(100 BYTE),
  MADRE_COGNOME                   VARCHAR2(100 BYTE),
  MADRE_DATANASCITA               DATE,
  MADRE_SESSO                     CHAR(1 BYTE),
  PADRE_NOME                      VARCHAR2(100 BYTE),
  PADRE_COGNOME                   VARCHAR2(100 BYTE),
  PADRE_DATANASCITA               DATE,
  PADRE_SESSO                     CHAR(1 BYTE),
  ID_TIPO_PROVV_ESTERO            NUMBER,
  ID_RICONOSCIMENTO_DA            NUMBER,
  ID_ISTITUTO_PENA_RICH           NUMBER,
  FLG_ISTITUTO_PENA               CHAR(1 BYTE),
  DATA_RICEZIONE_RICHIESTA        DATE,
  IN_QUALITA_DI                   VARCHAR2(50 BYTE),
  TRASCR_DECRETO_EMESSO_DA        VARCHAR2(50 BYTE),
  TRASCR_ID_COMUNE_PREFETTO_EMIT  NUMBER,
  TRASCR_ID_RICHIESTO_DA          NUMBER,
  TRASCR_RICH_PERSFIS_AUTORITA    VARCHAR2(256 BYTE),
  TRASCR_ID_CONSOLATO             NUMBER,
  TRASCR_ID_STATO_ESTERO          NUMBER,
  DIR_ISTITUTO_COGNOME            VARCHAR2(100 BYTE),
  DIR_ISTITUTO_NOME               VARCHAR2(100 BYTE),
  ISTITUTO_NOME                   VARCHAR2(256 BYTE),
  TESTO_CAPPELLO_ATTO             VARCHAR2(4000 BYTE),
  TESTO_CHIUSURA_ATTO             VARCHAR2(4000 BYTE),
  FLG_CAPPELLO                    CHAR(1 BYTE),
  FLG_CHIUSURA                    CHAR(1 BYTE),
  TESTO_CORPO1_ATTO               VARCHAR2(4000 BYTE),
  TESTO_CORPO2_ATTO               VARCHAR2(4000 BYTE),
  ID_SOGGETTO_DEFINITO            NUMBER,
  FLG_PARTO_PLURIMO               CHAR(1 BYTE),
  ID_DICHIARANTE                  NUMBER,
  MIG_ID                          NUMBER,
  FLG_ART_35_36                   VARCHAR2(1 BYTE),
  FLG_DICH_TARDIVA                CHAR(1 BYTE),
  MOTIVO_DICH_TARDIVA             VARCHAR2(4000 BYTE),
  DT_MOTIVO_RITARDO               VARCHAR2(40 BYTE),
  DT_TRIBUNALE_COMUNE             NUMBER,
  DT_NUMERO_PROVVEDIMENTO         VARCHAR2(40 BYTE),
  RICON_FLG_ASSENSO_FIGLIO        CHAR(1 BYTE),
  FLG_MAGGIORE_SCEGLIECOGNOME     CHAR(1 BYTE),
  FLG_ART33                       CHAR(1 BYTE),
  ID_CHECKBOX_COGNOME             NUMBER,
  FLG_DISCONOSCIMENTO             CHAR(1 BYTE),
  DATA_DECRETO_TRIBUNALE          DATE,
  INC_NUMERO_PROVV_TRIBUNALE      VARCHAR2(20 BYTE),
  INC_ID_COMUNE_TRIBUNALE         NUMBER,
  COGNOME_NUOVO                   VARCHAR2(100 BYTE),
  SCELTA_TRIBUNALE                NUMBER,
  ID_ATTO_CONSENSO_RICON          NUMBER,
  DATA_PROTOCOLLO_COMUNICAZIONE   DATE,
  FLG_INCESTUOSO                  CHAR(1 BYTE),
  ID_ATTO_PRERICON_MADRE          NUMBER,
  ID_ATTO_PRERICON_PADRE          NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.ST_ATTO_NASCITA IS 'Tabella per tracciatura ATTI di Nascita';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_SOGGETTO_GEN1 IS 'ID soggetto Genitore 1 - Padre';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_SOGGETTO_GEN2 IS 'ID soggetto Genitore 2 - Madre';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_SOGGETTO_DICH IS 'ID soggetto Dichiarante';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.MADRE_NOME IS 'MADRE - Nome ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.MADRE_COGNOME IS 'MADRE - Cognome ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.PADRE_NOME IS 'PADRE - Nome ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.PADRE_COGNOME IS 'PADRE - Cognome ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_RICONOSCIMENTO_DA IS 'Tipo di riconoscimento di un figlio nato fuori dal matrimonio';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_ISTITUTO_PENA_RICH IS 'Istituto di Pena richiedente';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_ISTITUTO_PENA IS 'Se richiessta da Istituto di Pena ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DATA_RICEZIONE_RICHIESTA IS 'Consenso sull''ATTO di Riconoscimento/Nascita - Data Ricezione Richiesta';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.IN_QUALITA_DI IS 'Indicare in qualità di ("dichiarante" o "interessato")';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TRASCR_DECRETO_EMESSO_DA IS 'Decreto emesso da (Prefetto, Ministero)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TRASCR_ID_COMUNE_PREFETTO_EMIT IS 'Comune del Prefetto emittente';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TRASCR_ID_RICHIESTO_DA IS 'DEPRECATO DA RICHIESTA_TRASCRIZIONE NON USARE- Richiesto da';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TRASCR_RICH_PERSFIS_AUTORITA IS 'DEPRECATO DA RICHIESTA_TRASCRIZIONE NON USARE- Richiesta da PersonaFisica o Autorità';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TRASCR_ID_CONSOLATO IS 'DEPRECATO DA RICHIESTA_TRASCRIZIONE NON USARE- Richiesto da Consolato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TRASCR_ID_STATO_ESTERO IS 'DEPRECATO DA RICHIESTA_TRASCRIZIONE NON USARE- Stato del richiedente';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DIR_ISTITUTO_COGNOME IS 'Direttore Istituto - Cognome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DIR_ISTITUTO_NOME IS 'Direttore Istituto - Nome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ISTITUTO_NOME IS 'Nome Istituto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TESTO_CAPPELLO_ATTO IS 'DEPRECATO DA ATTO_EXTENDED- Testo del cappello dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TESTO_CHIUSURA_ATTO IS 'DEPRECATO DA ATTO_EXTENDED - Testo della chiusura dell''atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_CAPPELLO IS 'DEPRECATO DA ATTO_EXTENDED - Flag Cappello prevalorizzato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_CHIUSURA IS 'DEPRECATO DA ATTO_EXTENDED - Flag Chiusura prevalorizzata';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TESTO_CORPO1_ATTO IS 'DEPRECATO DA ATTO_EXTENDED - Testo per la prima parte del corpo dell''atto libero';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.TESTO_CORPO2_ATTO IS 'DEPRECATO DA ATTO_EXTENDED - Testo per la seconda parte del corpo dell''atto libero';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_SOGGETTO_DEFINITO IS 'In fase di DEFINIZIONE dell''ATTO conterrà l''ID_SOGGETTO creato e clonato (da anagrafe) su STATO_CIVILE. nel caso di nascituri per il quale non ho un soggetto a priori';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_PARTO_PLURIMO IS 'Flag che segnala se il PARTO è stato plurimo o meno. default a NULL fino allo splitting. se vi sono più figli viene impostato a ''S'' altrimenti a ''N''';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_DICHIARANTE IS 'Tipologia di dichiarante per tipizzare il sottotipo di ATTO di NASCITA nonchÃ¨ modello da utilizzare per il formulario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_ART_35_36 IS 'Check Box Art. 35-36 a comparsa sulle maschere dichiarazioni e trascrizioni in caso di genitori entrambi non ITALIANI.
Valori ammessi:
 0 o Null -  default non selezionato
 1 – applicazione art 35-36 (i genitori stranieri si avvalgono della propria legge nazionale per la scelta del cognome)
 2 – doppio cognome (cognome padre + cognome madre)
 3 – “libero” (editabile dall’ufficiale di stato civile) 
';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_DICH_TARDIVA IS 'Dichiarazione Tardiva ([S]i o [N]o) - se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.MOTIVO_DICH_TARDIVA IS 'Motivo della dichiarazione tardiva';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DT_MOTIVO_RITARDO IS 'tipo del motivo del ritardo Tribunale-Altro';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DT_TRIBUNALE_COMUNE IS 'Identificativo del comune del tribunale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DT_NUMERO_PROVVEDIMENTO IS 'numero provvedimento del Tribunale per dichiarazione tardiva';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.RICON_FLG_ASSENSO_FIGLIO IS 'Assenso del figlio al riconoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_MAGGIORE_SCEGLIECOGNOME IS 'Figlio Maggiorenne sceglie Cognome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_ART33 IS 'Art.33';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_CHECKBOX_COGNOME IS 'Scelta sul Cognome (1. Mantiene Cognome, 2. Aggiunge Cognome, 3. Sostituisce Cognome, 4. Antepone Cognome)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_DISCONOSCIMENTO IS 'Disconoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DATA_DECRETO_TRIBUNALE IS 'Data decreto emmesso dal tribunale per il cognome del riconosciuto nei casi di figli incestuosi';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.INC_NUMERO_PROVV_TRIBUNALE IS 'Numero provvedimento decreto emmesso dal tribunale per il cognome del riconosciuto nei casi di figli incestuosi';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.INC_ID_COMUNE_TRIBUNALE IS 'Comune del Tribunale emittente del provvedimento per riconoscimenti incestuosi';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.COGNOME_NUOVO IS 'Cognome Nuovo per riconoscimenti';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.SCELTA_TRIBUNALE IS 'Scelta decreto emmesso dal tribunale per il cognome del riconosciuto nei casi di figli incestuosi';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_ATTO_CONSENSO_RICON IS 'ID_ATTO_CORRELATO per atto di consenso al riconoscimento o di consenso al prericonoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.DATA_PROTOCOLLO_COMUNICAZIONE IS 'Data protocollo comunicazione, se flg comunicazione è S si deve popolare la data protocollo';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.FLG_INCESTUOSO IS 'Bambino incestuoso ([S]i o [N]o)- se iscrizione da Pubblico Ufficiale, se Trascrizione altro comune da Pubblico Ufficiale, se Prericonoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_ATTO_PRERICON_MADRE IS 'ID_ATTO_CORRELATO per atto di prericonoscimento madre';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA.ID_ATTO_PRERICON_PADRE IS 'ID_ATTO_CORRELATO per atto di prericonoscimento padre';



CREATE UNIQUE INDEX MIGR_USR.ATTO_NASCITA_PK ON MIGR_USR.ST_ATTO_NASCITA
(ID_ATTO_NASCITA)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.ST_ATTO_NASCITA ADD (
  CONSTRAINT ATTO_NASCITA_PK
  PRIMARY KEY
  (ID_ATTO_NASCITA)
  USING INDEX MIGR_USR.ATTO_NASCITA_PK
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.ST_ATTO_NASCITA_SOGGETTO
(
  ID                              NUMBER        DEFAULT "MIGR_USR"."M_ATTO_NASCITA_SOGGETTO_SEQ"."NEXTVAL" NOT NULL,
  ID_ATTO_NASCITA                 NUMBER        NOT NULL,
  COGNOME                         VARCHAR2(100 BYTE),
  NOME                            VARCHAR2(100 BYTE),
  DATAORARIO_NASCITA              DATE,
  SESSO                           CHAR(1 BYTE),
  ID_COMUNE_NASCITA               NUMBER,
  FLG_IMPOSTA_NOME_COGNOME        CHAR(1 BYTE),
  ID_ATTO_CORRENTE                NUMBER,
  ID_ATTO_ESTERO                  NUMBER,
  ID_ATTO_RICON                   NUMBER,
  ID_ATTO_PRERICON                NUMBER,
  ID_ATTO_NASCITA_CORR            NUMBER,
  ID_ATTO_ADOZIONE                NUMBER,
  ID_ATTO_MATRIMONIO              NUMBER,
  FLG_NATO_MORTO                  CHAR(1 BYTE),
  FLG_DICH_TARDIVA                CHAR(1 BYTE),
  FLG_MORTO_PREDENUNCIA           CHAR(1 BYTE),
  FLG_LUOGONASCITA_DIVERSO        CHAR(1 BYTE),
  FLG_FUORI_OSPEDALE              CHAR(1 BYTE),
  DATAORARIO_DENUNCIA_DAOSPEDALE  DATE,
  DATA_PROTOCOLLO_DAOSPEDALE      DATE,
  DATA_CERTIFICATO                DATE,
  NOMINATIVO_DOTTORE              VARCHAR2(100 BYTE),
  ID_OSPEDALE                     NUMBER,
  ISTITUTO_AFFIDAMENTO            VARCHAR2(256 BYTE),
  MOTIVO_MANCATO_RICONOSC         VARCHAR2(4000 BYTE),
  FLG_PRIMO_FIGLIO                CHAR(1 BYTE),
  ID_SOGGETTO_INTERESSATO         NUMBER,
  CODICE_FAMIGLIA                 VARCHAR2(20 BYTE),
  ID_CODICE_LEGAME                NUMBER,
  FLG_ART29                       CHAR(1 BYTE),
  FLG_CONTEGGIO_GRAVIDANZA        CHAR(1 BYTE),
  CONTEGGIO_NUMERO                NUMBER,
  ID_CONSENSO_GENITORE            NUMBER,
  ID_TIPO_PRERICONOSCIMENTO       NUMBER,
  ID_MOTIVO_SCELTACOGNOME         NUMBER,
  QUANTITA_PROVV                  NUMBER,
  DATA_PROTOCOLLO_PROV1           DATE,
  DATA_PROVVEDIMENTO1             DATE,
  DATA_PROTOCOLLO_PROV2           DATE,
  DATA_PROVVEDIMENTO2             DATE,
  ID_COMUNE_TRIBUNALE             NUMBER,
  TIPO_TRIBUNALE                  VARCHAR2(20 BYTE),
  ID_TRIBUNALE                    NUMBER,
  ID_LEGGE                        NUMBER,
  ID_ARTICOLO_DILEGGE             NUMBER,
  ID_TIPO_OPER_REVOCA             NUMBER,
  NOTE_AGGIUNTIVE                 VARCHAR2(4000 BYTE),
  STRANIERO_DATA_PROVVEDIMENTO    DATE,
  STRANIERO_ENTE_EMITTENTE_PROVV  VARCHAR2(1000 BYTE),
  STRANIERO_PROPRIETA_PROVV       VARCHAR2(50 BYTE),
  COGNOME_NUOVO                   VARCHAR2(100 BYTE),
  NOME_NUOVO                      VARCHAR2(100 BYTE),
  SESSO_NUOVO                     CHAR(1 BYTE),
  DATA_NASCITA_NUOVO              DATE,
  ID_COMUNE_NASCITA_NUOVO         NUMBER,
  ID_CITTADINANZA                 NUMBER,
  FLG_CITTADINANZA_ANTEPRIMA      CHAR(1 BYTE),
  OPZ2_NUM_SENTENZA_TRIBUNALE     VARCHAR2(20 BYTE),
  OPZ2_DATA_PROVVEDIMENTO         DATE,
  OPZ2_ID_COMUNE_PROVV            NUMBER,
  OPZ3_FLG_CAMBIATO_COGNOME       CHAR(1 BYTE),
  OPZ3_COGNOME_PRECEDENTE         VARCHAR2(100 BYTE),
  OPZ3_ENTE_PROVVEDIMENTO         VARCHAR2(100 BYTE),
  OPZ3_DATA_PROVVEDIMENTO         DATE,
  OPZ3_ID_COMUNE_PROVV            NUMBER,
  OPZ4_ATTO_RICON_PADRE           VARCHAR2(1000 BYTE),
  OPZ4_ATTO_RICON_MADRE           VARCHAR2(1000 BYTE),
  OPZ5_NUM_SENTENZA_TRIBUNALE     VARCHAR2(20 BYTE),
  OPZ5_DATA_SENTENZA              DATE,
  OPZ5_ID_COMUNE_SENTENZA         NUMBER,
  OPZ5_TIPO_TRIBUNALE             VARCHAR2(20 BYTE),
  ID_SCELTACOGNOME_TRIB_A         NUMBER,
  ID_SCELTACOGNOME_TRIB_DA        NUMBER,
  FLG_MODIFICA_NOMINATIVO         CHAR(1 BYTE),
  MOTIVO_DICH_TARDIVA             VARCHAR2(4000 BYTE),
  MIG_ID                          NUMBER,
  ID_TITOLO_DOTTORE               NUMBER,
  ID_PROVINCIA_OSPEDALE           NUMBER,
  ID_COMUNE_OSPEDALE              NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.ST_ATTO_NASCITA_SOGGETTO IS 'Tabella per tracciatura Singoli neonati in caso di parti gemellari';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID IS 'ID del DETTAGLIO NASCITURO che in caso di DEFINISCI ATTO e pratica plurigemellare, costituirà il nuovo ID_ATTO dell''atto clonato per ogni singolo gemello, senza staccare altra sequence';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_NASCITA IS 'Alla definisci atto per un Gemello non primogenito switcherà sul nuovo atto con ID_ATTO_NASCITA= ID';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.COGNOME IS 'Cognome del neonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.NOME IS 'Nome del neonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATAORARIO_NASCITA IS 'Data e orario del neonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.SESSO IS 'Sesso del neonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_COMUNE_NASCITA IS 'ID del Comune di Nascita';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_IMPOSTA_NOME_COGNOME IS 'Flag Imposta Cognome e Nome ([S]i o [N]o)- Art.38 Abbandoni';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_CORRENTE IS 'Riferimento per ATTO CORRENTE';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_ESTERO IS 'Riferimento per ATTO ESTERO';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_RICON IS 'Riferimento per Assenso/Consenso sull''ATTO di Riconoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_PRERICON IS 'Riferimento per Assenso/Consenso sull''ATTO di PreRicon';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_NASCITA_CORR IS 'Riferimento all''ATTO di nascita per l''adozione/o correlato per altre operazioni';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_ADOZIONE IS 'Riferimento all''ATTO di Adozione per la revoca';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ATTO_MATRIMONIO IS 'Riferimento all''ATTO di MAtrimonio per il cambio di cognome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_NATO_MORTO IS 'Nato Morto ([S]i o [N]o) - se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_DICH_TARDIVA IS 'Dichiarazione Tardiva ([S]i o [N]o) - se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_MORTO_PREDENUNCIA IS 'Morto prima della denuncia ([S]i o [N]o)- se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_LUOGONASCITA_DIVERSO IS 'Luogo di Nascita Diverso ([S]i o [N]o)- se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_FUORI_OSPEDALE IS 'Nascita Fuori Ospedale ([S]i o [N]o)- se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATAORARIO_DENUNCIA_DAOSPEDALE IS 'Data e ORario Denuncia - per trascrizione da Ospedale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_PROTOCOLLO_DAOSPEDALE IS 'Data Protocollo - per trascrizione da Ospedale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_CERTIFICATO IS 'Data Certificato - se iscrizione da Pubblico Ufficiale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.NOMINATIVO_DOTTORE IS 'Nominativo dottore/medico curante';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_OSPEDALE IS 'ID Ospedale di nascita';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ISTITUTO_AFFIDAMENTO IS 'Istituto di affidamento - Figlio abbandonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.MOTIVO_MANCATO_RICONOSC IS 'Motivazione mancato riconoscimento della madre - Figlio abbandonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_PRIMO_FIGLIO IS 'Segnala se primo figlio per parto plurigemellare';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_SOGGETTO_INTERESSATO IS 'Soggetto interessato che ha richiesto trascrizione del proprio atto di nascita / Oppure Soggetto Riconsciuto/ Oppure Soggetto Comparente per SCelta Cognome.
QUANDO VIENE DEFINITO L''ATTO, IL NUOVO SOGGETTO CREATO NEL CASO PLURIGEMELLARE ASSUMERA'' CLONE DI QUANTO CREATO IN ANAGRAFE';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.CODICE_FAMIGLIA IS 'Codice Famiglia sleezionato per il Rapporto di parentela del Neonato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_CODICE_LEGAME IS 'Legame di parentela del neonato con il Capofamiglia/Intestatario';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_CONTEGGIO_GRAVIDANZA IS 'Come viene riportato il conteggio della gravidanza - [M]esi o [S]ettimane';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.CONTEGGIO_NUMERO IS 'Conteggio della gravidanza in Mesi/Settimane in base al flag FLG_CONTEGGIO_GRAVIDANZA';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_CONSENSO_GENITORE IS 'Consenso genitore: "Madre che consente", "Padre che consente" o per prericonoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_TIPO_PRERICONOSCIMENTO IS 'Dichiarazione di Prericonoscimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_MOTIVO_SCELTACOGNOME IS 'Motivo Scelta del Cambio Cognome ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.QUANTITA_PROVV IS 'Quantità di provvedimenti (1 o 2)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_PROTOCOLLO_PROV1 IS 'Data Protocollo - Provvedimento 1';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_PROVVEDIMENTO1 IS 'Data provvedimento 1';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_PROTOCOLLO_PROV2 IS 'Data Protocollo - Provvedimento 2';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_PROVVEDIMENTO2 IS 'Data provvedimento 2';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_COMUNE_TRIBUNALE IS 'Comune del Tribunale emittente del provvedimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.TIPO_TRIBUNALE IS 'Tipologia Tribunale emittente provvedimento di adozione (Minore o Civile)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_TRIBUNALE IS 'Radio button SCELTA TRIBUNALE da TBD';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_LEGGE IS 'Radio button SCELTA LEGGE da TBD';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_ARTICOLO_DILEGGE IS 'Articolo di Legge utilizzato per i provvedimenti di adozione';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_TIPO_OPER_REVOCA IS 'TIpologia di OPerazione di Revoca dell''adozione.';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.NOTE_AGGIUNTIVE IS 'Note aggiuntive (per REVOCA)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.STRANIERO_DATA_PROVVEDIMENTO IS 'STRANIERO Provvedimento - Data Provvedimento';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.STRANIERO_ENTE_EMITTENTE_PROVV IS 'STRANIERO Provvedimento - Ente emittente';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.STRANIERO_PROPRIETA_PROVV IS 'STRANIERO Provvedimento - Conformità o Efficacità (valori "Conferme" o "Efficace" per la checkbox)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.COGNOME_NUOVO IS 'Cognome Nuovo per Attribuzione del cognome/Adozione';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.NOME_NUOVO IS 'Nome Nuovo per Attribuzione del cognome/Adozione';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.SESSO_NUOVO IS 'Sesso Nuovo per Attribuzione del cognome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.DATA_NASCITA_NUOVO IS 'Data Nascita Nuova per Attribuzione del cognome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_COMUNE_NASCITA_NUOVO IS 'Comune Nascita Nuovo per Attribuzione del cognome';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_CITTADINANZA IS 'Cittadinanza del bambino';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_CITTADINANZA_ANTEPRIMA IS 'Mostrare o meno la cittadinanza sull''anteprima ([S]i o [N]o)';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.OPZ3_FLG_CAMBIATO_COGNOME IS '''M'' - Modificato, ''C'' - Cambiato';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_SCELTACOGNOME_TRIB_A IS 'Atto Corrente per Attributzione Cognome - Scelta Cognome A';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_SCELTACOGNOME_TRIB_DA IS 'Atto Corrente per Attributzione Cognome - Scelta Cognome DA';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.FLG_MODIFICA_NOMINATIVO IS 'Modifica del "C"ognome, "N"ome, "E"ntrambi';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.MOTIVO_DICH_TARDIVA IS 'Motivo della dichiarazione tardiva';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_TITOLO_DOTTORE IS 'Titolo del DOTTORE';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_PROVINCIA_OSPEDALE IS 'Id provincia ospedale';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_NASCITA_SOGGETTO.ID_COMUNE_OSPEDALE IS 'Id comune ospedale';



CREATE UNIQUE INDEX MIGR_USR.ATTO_NASCITA_SOGGETTO_PK ON MIGR_USR.ST_ATTO_NASCITA_SOGGETTO
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.ST_ATTO_NASCITA_SOGGETTO ADD (
  CONSTRAINT ATTO_NASCITA_SOGGETTO_PK
  PRIMARY KEY
  (ID)
  USING INDEX MIGR_USR.ATTO_NASCITA_SOGGETTO_PK
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.M_CFG_TIPO_ATTO
(
  ID_CONF_TIPO_ATTO  NUMBER,
  DESCRIZIONE        VARCHAR2(1000 BYTE),
  ID_MODELLO_ATTO    VARCHAR2(3 BYTE),
  ART_PRO_ADO        VARCHAR2(3 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.FT_INDICI
(
  NUM_ATTO       VARCHAR2(10 BYTE),
  ANNO_ATTO      VARCHAR2(4 BYTE),
  PROGR_ATTO     VARCHAR2(2 BYTE),
  COD_IND        VARCHAR2(7 BYTE),
  SEX            VARCHAR2(1 BYTE),
  COG_CMP        VARCHAR2(30 BYTE),
  NOME_CMP       VARCHAR2(20 BYTE),
  AA_NSC         VARCHAR2(4 BYTE),
  MM_NSC         VARCHAR2(2 BYTE),
  GG_NSC         VARCHAR2(2 BYTE),
  NOM_TAB_ATT    VARCHAR2(20 BYTE),
  OCCHIO         VARCHAR2(1 BYTE),
  ATT_ANNU       VARCHAR2(1 BYTE),
  DTA_ANNU       VARCHAR2(8 BYTE),
  FLG_SCAN       VARCHAR2(1 BYTE),
  TIP_EVE        VARCHAR2(1 BYTE),
  UTE_OPE        VARCHAR2(11 BYTE),
  PGM_OPE        VARCHAR2(11 BYTE),
  DTA_OPE        VARCHAR2(8 BYTE),
  ORA_OPE        VARCHAR2(5 BYTE),
  MIG_ID         NUMBER,
  MIG_STEP       VARCHAR2(200 BYTE),
  MIG_STATUS     VARCHAR2(200 BYTE),
  MIG_COD_ERROR  VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT__TRAPUBBLICO
(
  NUM_ATTO      VARCHAR2(9 BYTE),
  AA_ATTO       VARCHAR2(4 BYTE),
  MM_ATTO       VARCHAR2(2 BYTE),
  GG_ATTO       VARCHAR2(2 BYTE),
  ORA_ATTO      VARCHAR2(5 BYTE),
  OPERATORE     VARCHAR2(11 BYTE),
  DTA_ATT_ISC   VARCHAR2(8 BYTE),
  ORA_ATT_ISC   VARCHAR2(5 BYTE),
  UFF_ATT_ISC   VARCHAR2(100 BYTE),
  COM_ATT_ISC   VARCHAR2(5 BYTE),
  DTA_PRO       VARCHAR2(8 BYTE),
  COD_IND       VARCHAR2(7 BYTE),
  DTA_NAS       VARCHAR2(8 BYTE),
  ORA_NAS       VARCHAR2(5 BYTE),
  SEX           VARCHAR2(1 BYTE),
  COG_NAS       VARCHAR2(90 BYTE),
  NOM_NAS       VARCHAR2(90 BYTE),
  POS_GEM       VARCHAR2(1 BYTE),
  NUM_PRO_GEM   VARCHAR2(6 BYTE),
  COD_OSP       VARCHAR2(5 BYTE),
  NOM_OST_CER   VARCHAR2(100 BYTE),
  FLG_TIP_DOT   VARCHAR2(1 BYTE),
  DTA_CER       VARCHAR2(8 BYTE),
  COD_IND_MAT   VARCHAR2(7 BYTE),
  COG_MAT       VARCHAR2(90 BYTE),
  NOM_MAT       VARCHAR2(90 BYTE),
  DTA_NAS_MAT   VARCHAR2(8 BYTE),
  COM_NAS_MAT   VARCHAR2(5 BYTE),
  COM_RES_MAT   VARCHAR2(5 BYTE),
  CTD_MAT       VARCHAR2(1 BYTE),
  COD_NAZ_MAT   VARCHAR2(3 BYTE),
  ATT_PRE_MAT   VARCHAR2(9 BYTE),
  ANNO_PRE_MAT  VARCHAR2(4 BYTE),
  COM_PRE_MAT   VARCHAR2(5 BYTE),
  FLG_PRE_MAT   VARCHAR2(1 BYTE),
  FLG_ATT_CON   VARCHAR2(1 BYTE),
  COD_IND_PAT   VARCHAR2(7 BYTE),
  COG_PAT       VARCHAR2(90 BYTE),
  NOM_PAT       VARCHAR2(90 BYTE),
  DTA_NAS_PAT   VARCHAR2(8 BYTE),
  COM_NAS_PAT   VARCHAR2(5 BYTE),
  COM_RES_PAT   VARCHAR2(5 BYTE),
  CTD_PAT       VARCHAR2(1 BYTE),
  COD_NAZ_PAT   VARCHAR2(3 BYTE),
  ATT_PRE_PAT   VARCHAR2(9 BYTE),
  ANNO_PRE_PAT  VARCHAR2(4 BYTE),
  COM_PRE_PAT   VARCHAR2(5 BYTE),
  FLG_PRE_PAT   VARCHAR2(1 BYTE),
  DES_DIC       VARCHAR2(30 BYTE),
  DAT_PRO       VARCHAR2(100 BYTE),
  SEX_DIC       VARCHAR2(1 BYTE),
  COG_DIC       VARCHAR2(90 BYTE),
  NOM_DIC       VARCHAR2(90 BYTE),
  DTA_NAS_DIC   VARCHAR2(8 BYTE),
  COM_NAS_DIC   VARCHAR2(5 BYTE),
  COM_RES_DIC   VARCHAR2(5 BYTE),
  CTD_DIC       VARCHAR2(1 BYTE),
  COD_NAZ_DIC   VARCHAR2(3 BYTE),
  DTA_ATT_NOM   VARCHAR2(50 BYTE),
  FLG_STA_ATT   VARCHAR2(1 BYTE),
  FLG_DOC       VARCHAR2(1 BYTE),
  FLG_ART_COG   VARCHAR2(1 BYTE),
  COD_TIP_IND   VARCHAR2(1 BYTE),
  FLG_DIC_TAR   VARCHAR2(1 BYTE),
  FLG_FIG_INC   VARCHAR2(1 BYTE),
  FLG_DIF_DIC   VARCHAR2(1 BYTE),
  FLG_DIF_FIR   VARCHAR2(1 BYTE),
  FLG_LUO_NAS   VARCHAR2(1 BYTE),
  NUM_MOD       VARCHAR2(2 BYTE),
  UTE_OPE       VARCHAR2(11 BYTE),
  PGM_OPE       VARCHAR2(11 BYTE),
  DTA_OPE       VARCHAR2(8 BYTE),
  ORA_OPE       VARCHAR2(5 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT_ABBANDONI
(
  NUM_ATTO     VARCHAR2(9 BYTE),
  AA_ATTO      VARCHAR2(4 BYTE),
  MM_ATTO      VARCHAR2(2 BYTE),
  GG_ATTO      VARCHAR2(2 BYTE),
  ORA_ATTO     VARCHAR2(5 BYTE),
  OPERATORE    VARCHAR2(6 BYTE),
  DTA_PRO      VARCHAR2(8 BYTE),
  DTA_DEN_OSP  VARCHAR2(8 BYTE),
  ORA_DEN_OSP  VARCHAR2(5 BYTE),
  COD_IND      VARCHAR2(7 BYTE),
  DTA_NAS      VARCHAR2(8 BYTE),
  ORA_NAS      VARCHAR2(5 BYTE),
  GIO_NAS      VARCHAR2(3 BYTE),
  SEX          VARCHAR2(1 BYTE),
  COG_NAS      VARCHAR2(90 BYTE),
  NOM_NAS      VARCHAR2(90 BYTE),
  POS_GEM      VARCHAR2(1 BYTE),
  NUM_PRO_GEM  VARCHAR2(6 BYTE),
  COD_OSP      VARCHAR2(5 BYTE),
  NOM_DIR_SAN  VARCHAR2(100 BYTE),
  FLG_DEL      VARCHAR2(1 BYTE),
  DTA_CER      VARCHAR2(8 BYTE),
  DES_PUB_IST  VARCHAR2(100 BYTE),
  DES_DIC      VARCHAR2(30 BYTE),
  SEX_DIC      VARCHAR2(1 BYTE),
  COG_DIC      VARCHAR2(90 BYTE),
  NOM_DIC      VARCHAR2(90 BYTE),
  DTA_NAS_DIC  VARCHAR2(8 BYTE),
  COM_NAS_DIC  VARCHAR2(5 BYTE),
  COM_RES_DIC  VARCHAR2(5 BYTE),
  CTD_DIC      VARCHAR2(1 BYTE),
  COD_NAZ_DIC  VARCHAR2(3 BYTE),
  FLG_STA_ATT  VARCHAR2(1 BYTE),
  FLG_TIP_ATT  VARCHAR2(1 BYTE),
  COD_TIP_IND  VARCHAR2(1 BYTE),
  FLG_DIC_TAR  VARCHAR2(1 BYTE),
  DES_VES_RIT  VARCHAR2(200 BYTE),
  DTA_RIT      VARCHAR2(8 BYTE),
  ORA_RIT      VARCHAR2(5 BYTE),
  DET_POS_MAT  VARCHAR2(401 BYTE),
  FLG_CON      VARCHAR2(1 BYTE),
  TIP_ATT      VARCHAR2(1 BYTE),
  NUM_MOD      VARCHAR2(2 BYTE),
  UTE_OPE      VARCHAR2(11 BYTE),
  PGM_OPE      VARCHAR2(11 BYTE),
  DTA_OPE      VARCHAR2(8 BYTE),
  ORA_OPE      VARCHAR2(5 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT_ESTERO
(
  NUM_ATTO     VARCHAR2(9 BYTE),
  AA_ATTO      VARCHAR2(4 BYTE),
  MM_ATTO      VARCHAR2(2 BYTE),
  GG_ATTO      VARCHAR2(2 BYTE),
  ORA_ATTO     VARCHAR2(5 BYTE),
  OPERATORE    VARCHAR2(11 BYTE),
  ENT_RIC      VARCHAR2(1 BYTE),
  COD_COM_CON  VARCHAR2(5 BYTE),
  DTA_RIC      VARCHAR2(8 BYTE),
  COG_RIC      VARCHAR2(90 BYTE),
  NOM_RIC      VARCHAR2(90 BYTE),
  SIG_NAZ      VARCHAR2(3 BYTE),
  ATT_EST      VARCHAR2(20 BYTE),
  COD_IND      VARCHAR2(7 BYTE),
  DTA_NAS      VARCHAR2(8 BYTE),
  COM_NAS      VARCHAR2(5 BYTE),
  ORA_NAS      VARCHAR2(5 BYTE),
  SEX          VARCHAR2(1 BYTE),
  COG_NAS      VARCHAR2(90 BYTE),
  NOM_NAS      VARCHAR2(90 BYTE),
  COG_MAT      VARCHAR2(90 BYTE),
  NOM_MAT      VARCHAR2(90 BYTE),
  COG_PAT      VARCHAR2(90 BYTE),
  NOM_PAT      VARCHAR2(90 BYTE),
  PRE_LEG      VARCHAR2(1 BYTE),
  FLG_ANN      VARCHAR2(1 BYTE),
  NUM_MOD      VARCHAR2(2 BYTE),
  FIRMA        VARCHAR2(100 BYTE),
  LINGUA       VARCHAR2(20 BYTE),
  DTA_RIL      VARCHAR2(8 BYTE),
  STA_NAS      VARCHAR2(100 BYTE),
  LEG_PAD      VARCHAR2(1 BYTE),
  UTE_OPE      VARCHAR2(11 BYTE),
  PGM_OPE      VARCHAR2(11 BYTE),
  DTA_OPE      VARCHAR2(8 BYTE),
  ORA_OPE      VARCHAR2(5 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT_OSPEDALE
(
  NUM_ATTO      VARCHAR2(9 BYTE),
  AA_ATTO       VARCHAR2(4 BYTE),
  MM_ATTO       VARCHAR2(2 BYTE),
  GG_ATTO       VARCHAR2(2 BYTE),
  ORA_ATTO      VARCHAR2(5 BYTE),
  OPERATORE     VARCHAR2(11 BYTE),
  DTA_PRO       VARCHAR2(8 BYTE),
  DTA_DEN_OSP   VARCHAR2(8 BYTE),
  ORA_DEN_OSP   VARCHAR2(5 BYTE),
  COD_IND       VARCHAR2(7 BYTE),
  DTA_NAS       VARCHAR2(8 BYTE),
  ORA_NAS       VARCHAR2(5 BYTE),
  SEX           VARCHAR2(1 BYTE),
  COG_NAS       VARCHAR2(90 BYTE),
  NOM_NAS       VARCHAR2(90 BYTE),
  POS_GEM       VARCHAR2(1 BYTE),
  NUM_PRO_GEM   VARCHAR2(6 BYTE),
  COD_OSP       VARCHAR2(5 BYTE),
  NOM_DIR_SAN   VARCHAR2(100 BYTE),
  FLG_DEL       VARCHAR2(1 BYTE),
  COD_IND_MAT   VARCHAR2(7 BYTE),
  COG_MAT       VARCHAR2(90 BYTE),
  NOM_MAT       VARCHAR2(90 BYTE),
  DTA_NAS_MAT   VARCHAR2(8 BYTE),
  COM_NAS_MAT   VARCHAR2(5 BYTE),
  COM_RES_MAT   VARCHAR2(5 BYTE),
  CTD_MAT       VARCHAR2(1 BYTE),
  COD_NAZ_MAT   VARCHAR2(3 BYTE),
  ATT_PRE_MAT   VARCHAR2(9 BYTE),
  ANNO_PRE_MAT  VARCHAR2(4 BYTE),
  COM_PRE_MAT   VARCHAR2(5 BYTE),
  FLG_PRE_MAT   VARCHAR2(1 BYTE),
  FLG_ATT_CON   VARCHAR2(1 BYTE),
  COD_IND_PAT   VARCHAR2(7 BYTE),
  COG_PAT       VARCHAR2(90 BYTE),
  NOM_PAT       VARCHAR2(90 BYTE),
  DTA_NAS_PAT   VARCHAR2(8 BYTE),
  COM_NAS_PAT   VARCHAR2(5 BYTE),
  COM_RES_PAT   VARCHAR2(5 BYTE),
  CTD_PAT       VARCHAR2(1 BYTE),
  COD_NAZ_PAT   VARCHAR2(3 BYTE),
  ATT_PRE_PAT   VARCHAR2(9 BYTE),
  ANNO_PRE_PAT  VARCHAR2(4 BYTE),
  COM_PRE_PAT   VARCHAR2(5 BYTE),
  FLG_PRE_PAT   VARCHAR2(1 BYTE),
  DES_DIC       VARCHAR2(30 BYTE),
  DAT_PRO       VARCHAR2(100 BYTE),
  SEX_DIC       VARCHAR2(1 BYTE),
  COG_DIC       VARCHAR2(90 BYTE),
  NOM_DIC       VARCHAR2(90 BYTE),
  DTA_NAS_DIC   VARCHAR2(8 BYTE),
  COM_NAS_DIC   VARCHAR2(5 BYTE),
  COM_RES_DIC   VARCHAR2(5 BYTE),
  CTD_DIC       VARCHAR2(1 BYTE),
  COD_NAZ_DIC   VARCHAR2(3 BYTE),
  DTA_ATT_NOM   VARCHAR2(50 BYTE),
  FLG_STA_ATT   VARCHAR2(1 BYTE),
  FLG_DOC       VARCHAR2(1 BYTE),
  FLG_ART_COG   VARCHAR2(1 BYTE),
  FLG_FIG_INC   VARCHAR2(1 BYTE),
  FLG_DIF_DIC   VARCHAR2(1 BYTE),
  FLG_DIF_FIR   VARCHAR2(1 BYTE),
  NUM_MOD       VARCHAR2(2 BYTE),
  UTE_OPE       VARCHAR2(11 BYTE),
  PGM_OPE       VARCHAR2(11 BYTE),
  DTA_OPE       VARCHAR2(8 BYTE),
  ORA_OPE       VARCHAR2(5 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT_PUBBLICO
(
  NUM_ATTO      VARCHAR2(9 BYTE),
  AA_ATTO       VARCHAR2(4 BYTE),
  MM_ATTO       VARCHAR2(2 BYTE),
  GG_ATTO       VARCHAR2(2 BYTE),
  ORA_ATTO      VARCHAR2(5 BYTE),
  OPERATORE     VARCHAR2(11 BYTE),
  COD_IND       VARCHAR2(7 BYTE),
  DTA_NAS       VARCHAR2(8 BYTE),
  ORA_NAS       VARCHAR2(5 BYTE),
  SEX           VARCHAR2(1 BYTE),
  COG_NAS       VARCHAR2(90 BYTE),
  NOM_NAS       VARCHAR2(90 BYTE),
  POS_GEM       VARCHAR2(1 BYTE),
  NUM_PRO_GEM   VARCHAR2(6 BYTE),
  COD_OSP       VARCHAR2(5 BYTE),
  NOM_OST_CER   VARCHAR2(100 BYTE),
  FLG_TIP_DOT   VARCHAR2(17 BYTE),
  DTA_CER       VARCHAR2(18 BYTE),
  COD_IND_MAT   VARCHAR2(7 BYTE),
  COG_MAT       VARCHAR2(90 BYTE),
  NOM_MAT       VARCHAR2(90 BYTE),
  DTA_NAS_MAT   VARCHAR2(8 BYTE),
  COM_NAS_MAT   VARCHAR2(5 BYTE),
  COM_RES_MAT   VARCHAR2(5 BYTE),
  CTD_MAT       VARCHAR2(1 BYTE),
  COD_NAZ_MAT   VARCHAR2(3 BYTE),
  ATT_PRE_MAT   VARCHAR2(9 BYTE),
  ANNO_PRE_MAT  VARCHAR2(4 BYTE),
  COM_PRE_MAT   VARCHAR2(5 BYTE),
  FLG_PRE_MAT   VARCHAR2(1 BYTE),
  FLG_ATT_CON   VARCHAR2(1 BYTE),
  COD_IND_PAT   VARCHAR2(7 BYTE),
  COG_PAT       VARCHAR2(90 BYTE),
  NOM_PAT       VARCHAR2(90 BYTE),
  DTA_NAS_PAT   VARCHAR2(8 BYTE),
  COM_NAS_PAT   VARCHAR2(5 BYTE),
  COM_RES_PAT   VARCHAR2(5 BYTE),
  CTD_PAT       VARCHAR2(1 BYTE),
  COD_NAZ_PAT   VARCHAR2(3 BYTE),
  ATT_PRE_PAT   VARCHAR2(9 BYTE),
  ANNO_PRE_PAT  VARCHAR2(4 BYTE),
  COM_PRE_PAT   VARCHAR2(5 BYTE),
  FLG_PRE_PAT   VARCHAR2(1 BYTE),
  DES_DIC       VARCHAR2(30 BYTE),
  DAT_PRO       VARCHAR2(100 BYTE),
  SEX_DIC       VARCHAR2(1 BYTE),
  COG_DIC       VARCHAR2(90 BYTE),
  NOM_DIC       VARCHAR2(90 BYTE),
  DTA_NAS_DIC   VARCHAR2(8 BYTE),
  COM_NAS_DIC   VARCHAR2(5 BYTE),
  COM_RES_DIC   VARCHAR2(5 BYTE),
  CTD_DIC       VARCHAR2(1 BYTE),
  COD_NAZ_DIC   VARCHAR2(3 BYTE),
  DTA_ATT_NOM   VARCHAR2(50 BYTE),
  FLG_STA_ATT   VARCHAR2(1 BYTE),
  FLG_DOC       VARCHAR2(1 BYTE),
  FLG_ART_COG   VARCHAR2(1 BYTE),
  COD_TIP_IND   VARCHAR2(1 BYTE),
  FLG_DIC_TAR   VARCHAR2(1 BYTE),
  FLG_FIG_INC   VARCHAR2(1 BYTE),
  FLG_DIF_DIC   VARCHAR2(1 BYTE),
  FLG_DIF_FIR   VARCHAR2(1 BYTE),
  FLG_LUO_NAS   VARCHAR2(1 BYTE),
  NUM_MOD       VARCHAR2(2 BYTE),
  UTE_OPE       VARCHAR2(11 BYTE),
  PGM_OPE       VARCHAR2(11 BYTE),
  DTA_OPE       VARCHAR2(8 BYTE),
  ORA_OPE       VARCHAR2(5 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT_TRAOSPEDALE
(
  NUM_ATTO      VARCHAR2(9 BYTE),
  AA_ATTO       VARCHAR2(4 BYTE),
  MM_ATTO       VARCHAR2(2 BYTE),
  GG_ATTO       VARCHAR2(2 BYTE),
  ORA_ATTO      VARCHAR2(5 BYTE),
  OPERATORE     VARCHAR2(11 BYTE),
  DTA_ATT_ISC   VARCHAR2(8 BYTE),
  ORA_ATTO_ISC  VARCHAR2(5 BYTE),
  UFF_ATT_ISC   VARCHAR2(100 BYTE),
  COM_ATT_ISC   VARCHAR2(5 BYTE),
  DTA_PRO_ISC   VARCHAR2(8 BYTE),
  DTA_PRO       VARCHAR2(8 BYTE),
  DTA_DEN_OSP   VARCHAR2(8 BYTE),
  ORA_DEN_OSP   VARCHAR2(5 BYTE),
  COD_IND       VARCHAR2(7 BYTE),
  DTA_NAS       VARCHAR2(8 BYTE),
  ORA_NAS       VARCHAR2(5 BYTE),
  SEX           VARCHAR2(1 BYTE),
  COG_NAS       VARCHAR2(90 BYTE),
  NOM_NAS       VARCHAR2(90 BYTE),
  POS_GEM       VARCHAR2(1 BYTE),
  NUM_PRO_GEM   VARCHAR2(6 BYTE),
  COD_OSP       VARCHAR2(5 BYTE),
  NOM_DIR_SAN   VARCHAR2(100 BYTE),
  FLG_DEL       VARCHAR2(1 BYTE),
  COD_IND_MAT   VARCHAR2(7 BYTE),
  COG_MAT       VARCHAR2(90 BYTE),
  NOM_MAT       VARCHAR2(90 BYTE),
  DTA_NAS_MAT   VARCHAR2(8 BYTE),
  COM_NAS_MAT   VARCHAR2(5 BYTE),
  COM_RES_MAT   VARCHAR2(5 BYTE),
  CTD_MAT       VARCHAR2(1 BYTE),
  COD_NAZ_MAT   VARCHAR2(3 BYTE),
  ATT_PRE_MAT   VARCHAR2(9 BYTE),
  ANNO_PRE_MAT  VARCHAR2(4 BYTE),
  COM_PRE_MAT   VARCHAR2(5 BYTE),
  FLG_PRE_MAT   VARCHAR2(1 BYTE),
  FLG_ATT_CON   VARCHAR2(1 BYTE),
  COD_IND_PAT   VARCHAR2(7 BYTE),
  COG_PAT       VARCHAR2(90 BYTE),
  NOM_PAT       VARCHAR2(90 BYTE),
  DTA_NAS_PAT   VARCHAR2(8 BYTE),
  COM_NAS_PAT   VARCHAR2(5 BYTE),
  COM_RES_PAT   VARCHAR2(5 BYTE),
  CTD_PAT       VARCHAR2(1 BYTE),
  COD_NAZ_PAT   VARCHAR2(3 BYTE),
  ATT_PRE_PAT   VARCHAR2(9 BYTE),
  ANNO_PRE_PAT  VARCHAR2(4 BYTE),
  COM_PRE_PAT   VARCHAR2(5 BYTE),
  FLG_PRE_PAT   VARCHAR2(1 BYTE),
  DES_DIC       VARCHAR2(30 BYTE),
  DAT_PRO       VARCHAR2(100 BYTE),
  SEX_DIC       VARCHAR2(1 BYTE),
  COG_DIC       VARCHAR2(90 BYTE),
  NOM_DIC       VARCHAR2(90 BYTE),
  DTA_NAS_DIC   VARCHAR2(8 BYTE),
  COM_NAS_DIC   VARCHAR2(5 BYTE),
  COM_RES_DIC   VARCHAR2(5 BYTE),
  CTD_DIC       VARCHAR2(1 BYTE),
  COD_NAZ_DIC   VARCHAR2(3 BYTE),
  DTA_ATT_NOM   VARCHAR2(50 BYTE),
  FLG_STA_ATT   VARCHAR2(1 BYTE),
  FLG_DOC       VARCHAR2(1 BYTE),
  FLG_ART_COG   VARCHAR2(1 BYTE),
  FLG_FIG_INC   VARCHAR2(1 BYTE),
  FLG_DIF_DIC   VARCHAR2(1 BYTE),
  FLG_DIF_FIR   VARCHAR2(1 BYTE),
  NUM_MOD       VARCHAR2(2 BYTE),
  UTE_OPE       VARCHAR2(11 BYTE),
  PGM_OPE       VARCHAR2(11 BYTE),
  DTA_OPE       VARCHAR2(8 BYTE),
  ORA_OPE       VARCHAR2(5 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_FT_INDICI
(
  NUM_ATTO       VARCHAR2(10 BYTE),
  ANNO_ATTO      VARCHAR2(4 BYTE),
  PROGR_ATTO     VARCHAR2(2 BYTE),
  COD_IND        VARCHAR2(7 BYTE),
  SEX            VARCHAR2(1 BYTE),
  COG_CMP        VARCHAR2(20 BYTE),
  NOME_CMP       VARCHAR2(20 BYTE),
  AA_NSC         VARCHAR2(4 BYTE),
  MM_NSC         VARCHAR2(2 BYTE),
  GG_NSC         VARCHAR2(2 BYTE),
  NOM_TAB_ATT    VARCHAR2(20 BYTE),
  OCCHIO         VARCHAR2(1 BYTE),
  ATT_ANNU       VARCHAR2(1 BYTE),
  DTA_ANNU       VARCHAR2(8 BYTE),
  FLG_SCAN       VARCHAR2(1 BYTE),
  TIP_EVE        VARCHAR2(1 BYTE),
  UTE_OPE        VARCHAR2(11 BYTE),
  PGM_OPE        VARCHAR2(11 BYTE),
  DTA_OPE        VARCHAR2(8 BYTE),
  ORA_OPE        VARCHAR2(5 BYTE),
  MIG_ID         NUMBER,
  MIG_STEP       VARCHAR2(200 BYTE),
  MIG_STATUS     VARCHAR2(200 BYTE),
  MIG_COD_ERROR  VARCHAR2(20 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.ST_ATTO_CORRELATO
(
  ID                          NUMBER            DEFAULT "MIGR_USR"."M_ATTO_CORRELATO_SEQ"."NEXTVAL" NOT NULL,
  DATAORARIO_ATTO             DATE,
  DATA_PROTOCOLLO             DATE,
  DATAORARIO_ATTO_ISCRIZIONE  DATE,
  DATA_PROTOCOLLO_ISCRIZIONE  DATE,
  USC_ISCRIZIONE              VARCHAR2(100 BYTE),
  ID_RICHIESTA_DA             NUMBER,
  ID_COMUNE_ATTO              NUMBER,
  NUMERO_ATTO                 VARCHAR2(20 BYTE),
  PARTE                       VARCHAR2(5 BYTE),
  SERIE                       VARCHAR2(10 BYTE),
  ANNO                        NUMBER(4),
  DESCRIZIONE                 VARCHAR2(4000 BYTE),
  ESTERO_ID_STATOESTERO       NUMBER,
  ESTERO_AUTORITA_EMITTENTE   VARCHAR2(120 BYTE),
  ESTERO_REDATTO_IDLINGUA     NUMBER,
  ESTERO_LEGALIZZAZIONE       CHAR(1 BYTE),
  ESTERO_LEGITTIMAZIONE       CHAR(1 BYTE),
  ID_STATO_ESTERO_DA          NUMBER,
  ID_CONSOLATO_DA             NUMBER,
  NUMERO_PROVV                NUMBER,
  DATA_PROVVEDIMENTO          DATE,
  DATA_SECONDO_INVIO          DATE,
  ID_COMUNE_TRIBUNALE         NUMBER,
  TIPO_TRIBUNALE              VARCHAR2(50 BYTE),
  FLG_TRASCRITTO              CHAR(1 BYTE),
  DATA_EVENTO                 DATE,
  DATA_UPD                    TIMESTAMP(6)      DEFAULT SYSTIMESTAMP          NOT NULL,
  ID_TIPO_FILIAZIONE          NUMBER,
  ID_ARTICOLO_ADOZIONE        NUMBER,
  ESTERO_TIPO_ATTO            NUMBER,
  ID_COMUNE_RICON_DA          NUMBER,
  ID_PROV_RICON_DA            NUMBER,
  ID_PROV_TRIBUNALE           NUMBER,
  ID_TIPO_RICHIEDENTE         NUMBER,
  MIG_ID                      NUMBER,
  ID_STATO_ATTO               NUMBER,
  ID_PROVINCIA_ATTO           NUMBER,
  ESPONENTE                   VARCHAR2(2 BYTE),
  FLG_PRODOTTO_ACQUISITO      CHAR(1 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.ST_ATTO_CORRELATO IS 'Tabella per tracciare eventuali ATTI correlati alla pratica di creazione del nuovo atto';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_CORRELATO.ID_STATO_ATTO IS 'Stato dell''ATTO o ISCRIZIONE ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_CORRELATO.ID_PROVINCIA_ATTO IS 'Provincia dell''ATTO o ISCRIZIONE ';

COMMENT ON COLUMN MIGR_USR.ST_ATTO_CORRELATO.FLG_PRODOTTO_ACQUISITO IS 'Flag che identifica se l''atto di prericonosciment è Prodotto ''P'' o Acquisito ''A'' o Visionato ''V''';



CREATE UNIQUE INDEX MIGR_USR.ATTO_CORRELATO_PK ON MIGR_USR.ST_ATTO_CORRELATO
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.ST_ATTO_CORRELATO ADD (
  CONSTRAINT ATTO_CORRELATO_PK
  PRIMARY KEY
  (ID)
  USING INDEX MIGR_USR.ATTO_CORRELATO_PK
  ENABLE VALIDATE);
CREATE GLOBAL TEMPORARY TABLE MIGR_USR.GTT_ATTO_EXTEND
(
  ID_ATTO       NUMBER                          NOT NULL,
  ID_EXT_FIELD  VARCHAR2(50 BYTE)               NOT NULL,
  VALUE         VARCHAR2(100 BYTE),
  DATA_UPD      DATE                            DEFAULT SYSDATE,
  MIG_ID        NUMBER
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

COMMENT ON TABLE MIGR_USR.GTT_ATTO_EXTEND IS 'Tabella temp per estendere field della tabella master ATTO';

COMMENT ON COLUMN MIGR_USR.GTT_ATTO_EXTEND.ID_ATTO IS 'ID ATTO a cui sono correlati gli EXTENDED FIELDS';

COMMENT ON COLUMN MIGR_USR.GTT_ATTO_EXTEND.ID_EXT_FIELD IS 'ID dell''EXTENDED FIELD';

COMMENT ON COLUMN MIGR_USR.GTT_ATTO_EXTEND.VALUE IS 'Valore del campo';

COMMENT ON COLUMN MIGR_USR.GTT_ATTO_EXTEND.DATA_UPD IS 'Ultimo aggiornamento del campo';
CREATE TABLE MIGR_USR.M_CFG_EXTENDED_FIELDS
(
  ID              VARCHAR2(50 BYTE)             NOT NULL,
  AREA_SOTTOAREA  VARCHAR2(50 BYTE)             NOT NULL,
  TABLE_NAME      VARCHAR2(50 BYTE)             NOT NULL,
  FIELD_NAME      VARCHAR2(50 BYTE)             NOT NULL,
  FIELD_TYPE      VARCHAR2(50 BYTE)             NOT NULL,
  NOTE            VARCHAR2(1000 BYTE)           NOT NULL,
  OPZIONE1        VARCHAR2(100 BYTE),
  OPZIONE2        VARCHAR2(100 BYTE),
  DATA_UPD        DATE                          DEFAULT SYSDATE               NOT NULL,
  M_TABLE_FT      VARCHAR2(50 BYTE),
  M_COLUMN        VARCHAR2(50 BYTE),
  ORIG_TABLE      VARCHAR2(30 BYTE)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIGR_USR.M_CFG_EXTENDED_FIELDS IS 'Tabella per censimento degli EXTENDED FIELDS';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.ID IS 'ID';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.AREA_SOTTOAREA IS 'Area(e sottoarea ex. MATRIMONI_DIVORZI oppure MATRIMONI) dello stato civile a cui è associato il campo extended';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.FIELD_NAME IS 'Nome field aggiuntivo in EXTENDED FIELDS della tabella relativa';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.FIELD_TYPE IS 'Tipologia del fields: STRING, NUMBER, LIST /*list of value*/';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.NOTE IS 'Nota descrittiva per il campo per renderlo parlante';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.OPZIONE1 IS 'Campo per scopi futuri';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.OPZIONE2 IS 'Campo per scopi futuri';

COMMENT ON COLUMN MIGR_USR.M_CFG_EXTENDED_FIELDS.DATA_UPD IS 'Ultimo aggiornamento del campo';



CREATE UNIQUE INDEX MIGR_USR.ST_CFG_EXTENDED_FIELDS_PK ON MIGR_USR.M_CFG_EXTENDED_FIELDS
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX MIGR_USR.ST_CFG_EXTENDED_FIELDS_UX1 ON MIGR_USR.M_CFG_EXTENDED_FIELDS
(AREA_SOTTOAREA, TABLE_NAME, FIELD_NAME)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.M_CFG_EXTENDED_FIELDS ADD (
  CONSTRAINT ST_CFG_EXTENDED_FIELDS_PK
  PRIMARY KEY
  (ID)
  USING INDEX MIGR_USR.ST_CFG_EXTENDED_FIELDS_PK
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.TMP_OSP
(
  COD_OSP      VARCHAR2(5 CHAR),
  DEN_OSP      VARCHAR2(100 CHAR),
  IND_OSP      VARCHAR2(100 CHAR),
  NOM_DIR_SAN  VARCHAR2(100 CHAR),
  COD_COM_OSP  VARCHAR2(5 CHAR),
  FLG_DEL      VARCHAR2(1 CHAR),
  TIP_OSP      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR),
  ID_COMUNE    NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE MIGR_USR.TMP_CONF_OSPEDALE
(
  ID                      NUMBER                NOT NULL,
  DENOMINAZIONE           VARCHAR2(1000 BYTE)   NOT NULL,
  TIPO_OSPEDALE           VARCHAR2(50 BYTE)     NOT NULL,
  INDIRIZZO_OSPEDALE      VARCHAR2(1000 BYTE)   NOT NULL,
  ID_COMUNE               NUMBER                NOT NULL,
  DATA                    DATE                  NOT NULL,
  RESPONSABILE_SANITARIO  VARCHAR2(256 BYTE)    NOT NULL,
  FLG_DELEGATO            CHAR(1 BYTE)          NOT NULL,
  DATA_UPD                TIMESTAMP(6)          DEFAULT SYSTIMESTAMP          NOT NULL,
  COD_OSP                 VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MIGR_USR.CONF_OSPEDALE_PK ON MIGR_USR.TMP_CONF_OSPEDALE
(ID)
LOGGING
TABLESPACE ANAG_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIGR_USR.TMP_CONF_OSPEDALE ADD (
  CONSTRAINT CONF_OSPEDALE_PK
  PRIMARY KEY
  (ID)
  USING INDEX MIGR_USR.CONF_OSPEDALE_PK
  ENABLE VALIDATE);
CREATE TABLE MIGR_USR.M_CFG_MODELLI
(
  MODELLO                 VARCHAR2(50 BYTE),
  TABELLA                 VARCHAR2(50 BYTE),
  DESCRIZIONE             VARCHAR2(300 BYTE),
  FIGLIO                  VARCHAR2(100 BYTE),
  DICHIARANTE             VARCHAR2(100 BYTE),
  FIGURE_RICHIESTE        VARCHAR2(100 BYTE),
  ID_TIPO_RICONOSCIMENTO  NUMBER
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
