CREATE TABLE SC_MIGR.ATTINAS_ABBANDOAGG
(
  NUM_ATTO   VARCHAR2(9 CHAR),
  ANNO_ATTO  VARCHAR2(4 CHAR),
  NUM_PRO    VARCHAR2(1 CHAR),
  TESTO      VARCHAR2(400 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ABBANDONI
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  DTA_DEN_OSP  VARCHAR2(8 CHAR),
  ORA_DEN_OSP  VARCHAR2(5 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  ORA_NAS      VARCHAR2(5 CHAR),
  GIO_NAS      VARCHAR2(3 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  POS_GEM      VARCHAR2(1 CHAR),
  NUM_PRO_GEM  VARCHAR2(6 CHAR),
  COD_OSP      VARCHAR2(5 CHAR),
  NOM_DIR_SAN  VARCHAR2(100 CHAR),
  FLG_DEL      VARCHAR2(1 CHAR),
  DTA_CER      VARCHAR2(8 CHAR),
  DES_PUB_IST  VARCHAR2(100 CHAR),
  DES_DIC      VARCHAR2(30 CHAR),
  SEX_DIC      VARCHAR2(1 CHAR),
  COG_DIC      VARCHAR2(90 CHAR),
  NOM_DIC      VARCHAR2(90 CHAR),
  DTA_NAS_DIC  VARCHAR2(8 CHAR),
  COM_NAS_DIC  VARCHAR2(5 CHAR),
  COM_RES_DIC  VARCHAR2(5 CHAR),
  CTD_DIC      VARCHAR2(1 CHAR),
  COD_NAZ_DIC  VARCHAR2(3 CHAR),
  FLG_STA_ATT  VARCHAR2(1 CHAR),
  FLG_TIP_ATT  VARCHAR2(1 CHAR),
  COD_TIP_IND  VARCHAR2(1 CHAR),
  FLG_DIC_TAR  VARCHAR2(1 CHAR),
  DES_VES_RIT  VARCHAR2(200 CHAR),
  DTA_RIT      VARCHAR2(8 CHAR),
  ORA_RIT      VARCHAR2(5 CHAR),
  DET_POS_MAT  VARCHAR2(4000 CHAR),
  FLG_CON      VARCHAR2(1 CHAR),
  TIP_ATT      VARCHAR2(1 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ADOREV
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  NUM_PRO      VARCHAR2(2 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  ATT_NAS      VARCHAR2(9 CHAR),
  ANN_ATT_NAS  VARCHAR2(4 CHAR),
  CTD_NAS      VARCHAR2(1 CHAR),
  COD_NAZ      VARCHAR2(3 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  COG_NEW      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  TIP_TRI      VARCHAR2(1 CHAR),
  COD_COM_TRI  VARCHAR2(5 CHAR),
  DTA_EMI_PRO  VARCHAR2(8 CHAR),
  DTA_EMI_BIS  VARCHAR2(8 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  DTA_PRO_BIS  VARCHAR2(8 CHAR),
  SCELTA_STR   VARCHAR2(150 CHAR),
  COD_IND_MAT  VARCHAR2(7 CHAR),
  COG_MAT      VARCHAR2(90 CHAR),
  NOM_MAT      VARCHAR2(90 CHAR),
  DTA_NAS_MAT  VARCHAR2(8 CHAR),
  COM_NAS_MAT  VARCHAR2(5 CHAR),
  COM_RES_MAT  VARCHAR2(5 CHAR),
  CTD_MAT      VARCHAR2(1 CHAR),
  COD_NAZ_MAT  VARCHAR2(3 CHAR),
  COD_IND_PAT  VARCHAR2(7 CHAR),
  COG_PAT      VARCHAR2(90 CHAR),
  NOM_PAT      VARCHAR2(90 CHAR),
  DTA_NAS_PAT  VARCHAR2(8 CHAR),
  COM_NAS_PAT  VARCHAR2(5 CHAR),
  COM_RES_PAT  VARCHAR2(5 CHAR),
  CTD_PAT      VARCHAR2(1 CHAR),
  COD_NAZ_PAT  VARCHAR2(3 CHAR),
  FLG_ANR      VARCHAR2(1 CHAR),
  COG_NOM_DEL  VARCHAR2(90 CHAR),
  DTA_NAS_DEL  VARCHAR2(8 CHAR),
  COM_NAS_DEL  VARCHAR2(5 CHAR),
  TIP_TRI_ADO  VARCHAR2(1 CHAR),
  COD_COM_ADO  VARCHAR2(5 CHAR),
  DTA_PRO_ADO  VARCHAR2(8 CHAR),
  DTA_BIS_ADO  VARCHAR2(8 CHAR),
  ATT_ADO      VARCHAR2(9 CHAR),
  ANN_ATT_ADO  VARCHAR2(4 CHAR),
  FLG_RET      VARCHAR2(1 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ADOZIONI
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  DTA_PRO_BIS  VARCHAR2(8 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  ATT_NAS      VARCHAR2(9 CHAR),
  ANN_ATT_NAS  VARCHAR2(4 CHAR),
  CTD_NAS      VARCHAR2(1 CHAR),
  COD_NAZ      VARCHAR2(3 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  COG_NEW      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  TIP_TRI      VARCHAR2(1 CHAR),
  COD_COM_TRI  VARCHAR2(5 CHAR),
  DTA_EMI_PRO  VARCHAR2(8 CHAR),
  DTA_EMI_BIS  VARCHAR2(8 CHAR),
  FLG_TRI_LEG  VARCHAR2(1 CHAR),
  ENT_STR      VARCHAR2(150 CHAR),
  DTA_STR      VARCHAR2(8 CHAR),
  FLG_CON_EFF  VARCHAR2(1 CHAR),
  COD_IND_MAT  VARCHAR2(7 CHAR),
  COG_MAT      VARCHAR2(90 CHAR),
  NOM_MAT      VARCHAR2(90 CHAR),
  DTA_NAS_MAT  VARCHAR2(8 CHAR),
  COM_NAS_MAT  VARCHAR2(5 CHAR),
  COM_RES_MAT  VARCHAR2(5 CHAR),
  CTD_MAT      VARCHAR2(1 CHAR),
  COD_NAZ_MAT  VARCHAR2(3 CHAR),
  COD_IND_PAT  VARCHAR2(7 CHAR),
  COG_PAT      VARCHAR2(90 CHAR),
  NOM_PAT      VARCHAR2(90 CHAR),
  DTA_NAS_PAT  VARCHAR2(8 CHAR),
  COM_NAS_PAT  VARCHAR2(5 CHAR),
  COM_RES_PAT  VARCHAR2(5 CHAR),
  CTD_PAT      VARCHAR2(1 CHAR),
  COD_NAZ_PAT  VARCHAR2(3 CHAR),
  ART_PRO_ADO  VARCHAR2(3 CHAR),
  FLG_STA_ATT  VARCHAR2(1 CHAR),
  ADO_MUL      VARCHAR2(1 CHAR),
  FLG_RET      VARCHAR2(1 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ANNOESTERO
(
  NUM_ATTO   VARCHAR2(9 CHAR),
  ANNO_ATTO  VARCHAR2(4 CHAR),
  POS_ANN    VARCHAR2(1 CHAR),
  NUM_PRO    VARCHAR2(2 CHAR),
  DES_ANN    VARCHAR2(400 CHAR),
  UTE_OPE    VARCHAR2(11 CHAR),
  PGM_OPE    VARCHAR2(11 CHAR),
  DTA_OPE    VARCHAR2(8 CHAR),
  ORA_OPE    VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ANNOTADESC
(
  NUM_ATTO    VARCHAR2(10 CHAR),
  ANNO_ATTO   VARCHAR2(4 CHAR),
  PROGR_ATTO  VARCHAR2(2 CHAR),
  NUM_PRO     VARCHAR2(3 CHAR),
  PRO_RIG     VARCHAR2(2 CHAR),
  POS_ANNOT   VARCHAR2(1 CHAR),
  DES_ANNOT   VARCHAR2(400 CHAR),
  DES_ESTR    VARCHAR2(70 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ANNOTADESCS
(
  NUM_ATTO    VARCHAR2(10 CHAR),
  ANNO_ATTO   VARCHAR2(4 CHAR),
  PROGR_ATTO  VARCHAR2(2 CHAR),
  NUM_PRO     VARCHAR2(3 CHAR),
  PRO_RIG     VARCHAR2(2 CHAR),
  POS_ANNOT   VARCHAR2(1 CHAR),
  DES_ANNOT   VARCHAR2(400 CHAR),
  DES_ESTR    VARCHAR2(70 CHAR),
  UTE_OPE     VARCHAR2(11 CHAR),
  PGM_OPE     VARCHAR2(11 CHAR),
  DTA_OPE     VARCHAR2(8 CHAR),
  ORA_OPE     VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ANNOTANAS
(
  NUM_ATTO       VARCHAR2(10 CHAR),
  ANNO_ATTO      VARCHAR2(4 CHAR),
  PROGR_ATTO     VARCHAR2(2 CHAR),
  NUM_PRO        VARCHAR2(3 CHAR),
  NUM_FORM       VARCHAR2(3 CHAR),
  AGG_FORM       VARCHAR2(2 CHAR),
  FLG_SCR_ANN    VARCHAR2(1 CHAR),
  DTA_SCR_ANN    VARCHAR2(8 CHAR),
  UTE_SCR_ANN    VARCHAR2(11 CHAR),
  FLG_AUT_MAN    VARCHAR2(1 CHAR),
  DES_MOT_ANN    VARCHAR2(200 CHAR),
  NUM_ATTO_ANN   VARCHAR2(10 CHAR),
  ANNO_ATTO_ANN  VARCHAR2(4 CHAR),
  COD_IND        VARCHAR2(7 CHAR),
  FLG_RET        VARCHAR2(1 CHAR),
  TIPO_ATTO_ANN  VARCHAR2(2 CHAR),
  UTE_OPE_INS    VARCHAR2(11 CHAR),
  PGM_OPE_INS    VARCHAR2(11 CHAR),
  DTA_OPE_INS    VARCHAR2(8 CHAR),
  ORA_OPE_INS    VARCHAR2(5 CHAR),
  UTE_OPE_AGG    VARCHAR2(11 CHAR),
  PGM_OPE_AGG    VARCHAR2(11 CHAR),
  DTA_OPE_AGG    VARCHAR2(8 CHAR),
  ORA_OPE_AGG    VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ANNOTANASS
(
  NUM_ATTO       VARCHAR2(10 CHAR),
  ANNO_ATTO      VARCHAR2(4 CHAR),
  PROGR_ATTO     VARCHAR2(2 CHAR),
  NUM_PRO        VARCHAR2(3 CHAR),
  NUM_FORM       VARCHAR2(3 CHAR),
  AGG_FORM       VARCHAR2(2 CHAR),
  FLG_SCR_ANN    VARCHAR2(1 CHAR),
  DTA_SCR_ANN    VARCHAR2(8 CHAR),
  UTE_SCR_ANN    VARCHAR2(11 CHAR),
  FLG_AUT_MAN    VARCHAR2(1 CHAR),
  DES_MOT_ANN    VARCHAR2(200 CHAR),
  NUM_ATTO_ANN   VARCHAR2(10 CHAR),
  ANNO_ATTO_ANN  VARCHAR2(4 CHAR),
  COD_IND        VARCHAR2(7 CHAR),
  FLG_RET        VARCHAR2(1 CHAR),
  TIPO_ATTO_ANN  VARCHAR2(2 CHAR),
  UTE_OPE_INS    VARCHAR2(11 CHAR),
  PGM_OPE_INS    VARCHAR2(11 CHAR),
  DTA_OPE_INS    VARCHAR2(8 CHAR),
  ORA_OPE_INS    VARCHAR2(5 CHAR),
  UTE_OPE_AGG    VARCHAR2(11 CHAR),
  PGM_OPE_AGG    VARCHAR2(11 CHAR),
  DTA_OPE_AGG    VARCHAR2(8 CHAR),
  ORA_OPE_AGG    VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ANNOTARET
(
  NUM_ATTO    VARCHAR2(10 CHAR),
  ANNO_ATTO   VARCHAR2(4 CHAR),
  PROGR_ATTO  VARCHAR2(2 CHAR),
  NUM_PRO     VARCHAR2(3 CHAR),
  COD_IND     VARCHAR2(7 CHAR),
  PROGR_STR   VARCHAR2(1 CHAR),
  STR         VARCHAR2(400 CHAR),
  PGM_UTE     VARCHAR2(11 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_BUSTE
(
  FLG_STA  VARCHAR2(2 CHAR),
  TES_PRE  VARCHAR2(80 CHAR),
  COD_COM  VARCHAR2(5 CHAR),
  CAP_IND  VARCHAR2(5 CHAR),
  IND_PRE  VARCHAR2(100 CHAR),
  UTE_OPE  VARCHAR2(11 CHAR),
  PGM_OPE  VARCHAR2(11 CHAR),
  DTA_OPE  VARCHAR2(8 CHAR),
  ORA_OPE  VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_COMUNICAZIONI
(
  NUM_ATTO   VARCHAR2(9 CHAR),
  ANNO_ATTO  VARCHAR2(4 CHAR),
  FLG_PRE    VARCHAR2(1 CHAR),
  TES_PRE    VARCHAR2(100 CHAR),
  COD_COM    VARCHAR2(5 CHAR),
  CAP_IND    VARCHAR2(5 CHAR),
  IND_PRE    VARCHAR2(100 CHAR),
  UTE_OPE    VARCHAR2(11 CHAR),
  PGM_OPE    VARCHAR2(11 CHAR),
  DTA_OPE    VARCHAR2(8 CHAR),
  ORA_OPE    VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_CONASSRICO
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  NUM_PRO      VARCHAR2(2 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  SEX          VARCHAR2(1 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COD_COM      VARCHAR2(5 CHAR),
  FLG_CTD      VARCHAR2(1 CHAR),
  SIG_NAZ      VARCHAR2(3 CHAR),
  COD_COM_RES  VARCHAR2(5 CHAR),
  NUM_ATT_FIG  VARCHAR2(9 CHAR),
  DTA_ATT_FIG  VARCHAR2(8 CHAR),
  COM_ATT_FIG  VARCHAR2(5 CHAR),
  DTA_RIC_FIG  VARCHAR2(8 CHAR),
  COD_IND_PAT  VARCHAR2(7 CHAR),
  COG_PAT      VARCHAR2(90 CHAR),
  NOM_PAT      VARCHAR2(90 CHAR),
  DTA_NAS_PAT  VARCHAR2(8 CHAR),
  COM_NAS_PAT  VARCHAR2(5 CHAR),
  CTD_PAT      VARCHAR2(1 CHAR),
  NAZ_PAT      VARCHAR2(3 CHAR),
  COM_RES_PAT  VARCHAR2(5 CHAR),
  COD_IND_MAT  VARCHAR2(7 CHAR),
  COG_MAT      VARCHAR2(90 CHAR),
  NOM_MAT      VARCHAR2(90 CHAR),
  DTA_NAS_MAT  VARCHAR2(8 CHAR),
  COM_NAS_MAT  VARCHAR2(5 CHAR),
  CTD_MAT      VARCHAR2(1 CHAR),
  NAZ_MAT      VARCHAR2(3 CHAR),
  COM_RES_MAT  VARCHAR2(5 CHAR),
  COG_PRE      VARCHAR2(90 CHAR),
  FLG_COG_SCE  VARCHAR2(1 CHAR),
  FLG_PAT_MAT  VARCHAR2(1 CHAR),
  FLG_DIF_DIC  VARCHAR2(1 CHAR),
  FLG_DIF_FIR  VARCHAR2(1 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  TXT_ATT_RIC  VARCHAR2(300 CHAR),
  FLG_CAR      VARCHAR2(2 CHAR),
  FLG_RET      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_CONSENSI
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  ANNO_ATTO    VARCHAR2(4 CHAR),
  NUM_ATT_CON  VARCHAR2(9 CHAR),
  DTA_ATT_CON  VARCHAR2(8 CHAR),
  COM_ATT_CON  VARCHAR2(5 CHAR),
  FLG_ATT_CON  VARCHAR2(1 CHAR),
  NUM_ATT_PUB  VARCHAR2(100 CHAR),
  DES_PUB_UFF  VARCHAR2(100 CHAR),
  NUM_ATT_PRO  VARCHAR2(20 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  COM_PRO      VARCHAR2(5 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_DICHIARA
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  ANNO_ATTO    VARCHAR2(4 CHAR),
  FLG_TIP_DIC  VARCHAR2(1 CHAR),
  DES_MOT_DIC  VARCHAR2(200 CHAR),
  DES_MEZ_DIC  VARCHAR2(200 CHAR),
  COG_INT      VARCHAR2(90 CHAR),
  NOM_INT      VARCHAR2(90 CHAR),
  DTA_NAS_INT  VARCHAR2(8 CHAR),
  COM_NAS_INT  VARCHAR2(5 CHAR),
  COM_RES_INT  VARCHAR2(5 CHAR),
  CTD_INT      VARCHAR2(1 CHAR),
  COD_NAZ_INT  VARCHAR2(3 CHAR),
  SEX_INT      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_DOCUMENTI
(
  NUM_ATTO  VARCHAR2(9 CHAR),
  AA_ATTO   VARCHAR2(4 CHAR),
  TIP_DOC   VARCHAR2(1 CHAR),
  LIS_DOC   VARCHAR2(300 CHAR),
  UTE_OPE   VARCHAR2(11 CHAR),
  PGM_OPE   VARCHAR2(11 CHAR),
  DTA_OPE   VARCHAR2(8 CHAR),
  ORA_OPE   VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_ESTERO
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  ENT_RIC      VARCHAR2(1 CHAR),
  COD_COM_CON  VARCHAR2(5 CHAR),
  DTA_RIC      VARCHAR2(8 CHAR),
  COG_RIC      VARCHAR2(90 CHAR),
  NOM_RIC      VARCHAR2(90 CHAR),
  SIG_NAZ      VARCHAR2(3 CHAR),
  ATT_EST      VARCHAR2(20 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  ORA_NAS      VARCHAR2(5 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  COG_MAT      VARCHAR2(90 CHAR),
  NOM_MAT      VARCHAR2(90 CHAR),
  COG_PAT      VARCHAR2(90 CHAR),
  NOM_PAT      VARCHAR2(90 CHAR),
  PRE_LEG      VARCHAR2(1 CHAR),
  FLG_ANN      VARCHAR2(1 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  FIRMA        VARCHAR2(100 CHAR),
  LINGUA       VARCHAR2(20 CHAR),
  DTA_RIL      VARCHAR2(8 CHAR),
  STA_NAS      VARCHAR2(100 CHAR),
  LEG_PAD      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_FIRME
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  ANNO_ATTO    VARCHAR2(4 CHAR),
  NUM_PRO      VARCHAR2(1 CHAR),
  FLG_PAT_MAT  VARCHAR2(1 CHAR),
  MOT_NON_FIR  VARCHAR2(400 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_FORMAZIAGG
(
  NUM_ATTO  VARCHAR2(9 CHAR),
  AA_ATTO   VARCHAR2(4 CHAR),
  NUM_PRO   VARCHAR2(1 CHAR),
  NOT_AGG   VARCHAR2(400 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_FORMAZIONE
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  ORA_NAS      VARCHAR2(5 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  FLG_CTD      VARCHAR2(1 CHAR),
  COD_NAZ      VARCHAR2(3 CHAR),
  COG_MAT      VARCHAR2(90 CHAR),
  NOM_MAT      VARCHAR2(90 CHAR),
  COG_PAT      VARCHAR2(90 CHAR),
  NOM_PAT      VARCHAR2(90 CHAR),
  NUM_PROV     VARCHAR2(20 CHAR),
  ENT_RIC      VARCHAR2(1 CHAR),
  COD_COM_CON  VARCHAR2(5 CHAR),
  DTA_SEN      VARCHAR2(8 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  FLG_AGG      VARCHAR2(1 CHAR),
  FLG_COG      VARCHAR2(1 CHAR),
  FLG_GIR      VARCHAR2(1 CHAR),
  FLG_NMOR     VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_FORMULE
(
  NUM_FOR   VARCHAR2(3 CHAR),
  TESTO     VARCHAR2(499 CHAR),
  DIV_FOR   VARCHAR2(8 CHAR),
  DFV_FOR   VARCHAR2(8 CHAR),
  FLG_AGG1  VARCHAR2(2 CHAR),
  FLG_AGG2  VARCHAR2(2 CHAR),
  FLG_AGG3  VARCHAR2(2 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_GENMORTI
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  DTA_DEC_PAT  VARCHAR2(8 CHAR),
  COM_DEC_PAT  VARCHAR2(5 CHAR),
  DTA_DEC_MAT  VARCHAR2(8 CHAR),
  COM_DEC_MAT  VARCHAR2(5 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_INCESTUOSO
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  COD_COM_TRI  VARCHAR2(5 CHAR),
  DTA_DEC_TRI  VARCHAR2(8 CHAR),
  NUM_DEC_TRI  VARCHAR2(20 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_INDANN
(
  NUM_ATTO     VARCHAR2(10 CHAR),
  ANNO_ATTO    VARCHAR2(4 CHAR),
  PROGR_ATTO   VARCHAR2(2 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_CMP      VARCHAR2(30 CHAR),
  NOME_CMP     VARCHAR2(20 CHAR),
  AA_NSC       VARCHAR2(4 CHAR),
  MM_NSC       VARCHAR2(2 CHAR),
  GG_NSC       VARCHAR2(2 CHAR),
  NOM_TAB_ATT  VARCHAR2(20 CHAR),
  OCCHIO       VARCHAR2(1 CHAR),
  ATT_ANNU     VARCHAR2(1 CHAR),
  DTA_ANNU     VARCHAR2(8 CHAR),
  FLG_SCAN     VARCHAR2(1 CHAR),
  TIP_EVE      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_INDICI
(
  NUM_ATTO     VARCHAR2(10 CHAR),
  ANNO_ATTO    VARCHAR2(4 CHAR),
  PROGR_ATTO   VARCHAR2(2 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_CMP      VARCHAR2(30 CHAR),
  NOME_CMP     VARCHAR2(20 CHAR),
  AA_NSC       VARCHAR2(4 CHAR),
  MM_NSC       VARCHAR2(2 CHAR),
  GG_NSC       VARCHAR2(2 CHAR),
  NOM_TAB_ATT  VARCHAR2(20 CHAR),
  OCCHIO       VARCHAR2(1 CHAR),
  ATT_ANNU     VARCHAR2(1 CHAR),
  DTA_ANNU     VARCHAR2(8 CHAR),
  FLG_SCAN     VARCHAR2(1 CHAR),
  TIP_EVE      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_LUOGOPUB
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  DES_VIA_NAS  VARCHAR2(200 CHAR),
  COD_COM_NAS  VARCHAR2(5 CHAR),
  FLG_CER      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_MODELLI
(
  NUM_FOR  VARCHAR2(3 CHAR),
  MOD_01   VARCHAR2(2 CHAR),
  MOD_02   VARCHAR2(2 CHAR),
  MOD_03   VARCHAR2(2 CHAR),
  MOD_04   VARCHAR2(2 CHAR),
  MOD_05   VARCHAR2(2 CHAR),
  MOD_06   VARCHAR2(2 CHAR),
  MOD_07   VARCHAR2(2 CHAR),
  MOD_08   VARCHAR2(2 CHAR),
  MOD_09   VARCHAR2(2 CHAR),
  MOD_10   VARCHAR2(2 CHAR),
  MOD_11   VARCHAR2(2 CHAR),
  MOD_12   VARCHAR2(2 CHAR),
  MOD_13   VARCHAR2(2 CHAR),
  MOD_14   VARCHAR2(2 CHAR),
  MOD_15   VARCHAR2(2 CHAR),
  MOD_16   VARCHAR2(2 CHAR),
  MOD_17   VARCHAR2(2 CHAR),
  MOD_18   VARCHAR2(2 CHAR),
  MOD_19   VARCHAR2(2 CHAR),
  MOD_20   VARCHAR2(2 CHAR),
  MOD_21   VARCHAR2(2 CHAR),
  MOD_22   VARCHAR2(2 CHAR),
  MOD_23   VARCHAR2(2 CHAR),
  MOD_24   VARCHAR2(2 CHAR),
  MOD_25   VARCHAR2(2 CHAR),
  MOD_26   VARCHAR2(2 CHAR),
  MOD_27   VARCHAR2(2 CHAR),
  MOD_28   VARCHAR2(2 CHAR),
  MOD_29   VARCHAR2(2 CHAR),
  MOD_30   VARCHAR2(2 CHAR),
  MOD_31   VARCHAR2(2 CHAR),
  MOD_32   VARCHAR2(2 CHAR),
  MOD_33   VARCHAR2(2 CHAR),
  MOD_34   VARCHAR2(2 CHAR),
  MOD_35   VARCHAR2(2 CHAR),
  MOD_36   VARCHAR2(2 CHAR),
  MOD_37   VARCHAR2(2 CHAR),
  MOD_38   VARCHAR2(2 CHAR),
  MOD_39   VARCHAR2(2 CHAR),
  MOD_40   VARCHAR2(2 CHAR),
  MOD_41   VARCHAR2(2 CHAR),
  MOD_42   VARCHAR2(2 CHAR),
  MOD_43   VARCHAR2(2 CHAR),
  MOD_44   VARCHAR2(2 CHAR),
  MOD_45   VARCHAR2(2 CHAR),
  MOD_46   VARCHAR2(2 CHAR),
  MOD_47   VARCHAR2(2 CHAR),
  MOD_48   VARCHAR2(2 CHAR),
  MOD_49   VARCHAR2(2 CHAR),
  MOD_50   VARCHAR2(2 CHAR),
  MOD_51   VARCHAR2(2 CHAR),
  MOD_52   VARCHAR2(2 CHAR),
  MOD_53   VARCHAR2(2 CHAR),
  MOD_54   VARCHAR2(2 CHAR),
  MOD_55   VARCHAR2(2 CHAR),
  MOD_56   VARCHAR2(2 CHAR),
  MOD_57   VARCHAR2(2 CHAR),
  MOD_58   VARCHAR2(2 CHAR),
  MOD_59   VARCHAR2(2 CHAR),
  MOD_60   VARCHAR2(2 CHAR),
  MOD_61   VARCHAR2(2 CHAR),
  MOD_62   VARCHAR2(2 CHAR),
  MOD_63   VARCHAR2(2 CHAR),
  MOD_64   VARCHAR2(2 CHAR),
  MOD_65   VARCHAR2(2 CHAR),
  MOD_66   VARCHAR2(2 CHAR),
  MOD_67   VARCHAR2(2 CHAR),
  MOD_68   VARCHAR2(2 CHAR),
  MOD_69   VARCHAR2(2 CHAR),
  MOD_70   VARCHAR2(2 CHAR),
  MOD_71   VARCHAR2(2 CHAR),
  MOD_72   VARCHAR2(2 CHAR),
  MOD_73   VARCHAR2(2 CHAR),
  MOD_74   VARCHAR2(2 CHAR),
  MOD_75   VARCHAR2(2 CHAR),
  MOD_76   VARCHAR2(2 CHAR),
  MOD_77   VARCHAR2(2 CHAR),
  MOD_78   VARCHAR2(2 CHAR),
  MOD_79   VARCHAR2(2 CHAR),
  MOD_80   VARCHAR2(2 CHAR),
  MOD_81   VARCHAR2(2 CHAR),
  MOD_82   VARCHAR2(2 CHAR),
  MOD_83   VARCHAR2(2 CHAR),
  MOD_84   VARCHAR2(2 CHAR),
  MOD_85   VARCHAR2(2 CHAR),
  MOD_86   VARCHAR2(2 CHAR),
  MOD_87   VARCHAR2(2 CHAR),
  MOD_88   VARCHAR2(2 CHAR),
  MOD_89   VARCHAR2(2 CHAR),
  MOD_90   VARCHAR2(2 CHAR),
  MOD_91   VARCHAR2(2 CHAR),
  MOD_92   VARCHAR2(2 CHAR),
  MOD_93   VARCHAR2(2 CHAR),
  MOD_94   VARCHAR2(2 CHAR),
  MOD_95   VARCHAR2(2 CHAR),
  MOD_96   VARCHAR2(2 CHAR),
  MOD_97   VARCHAR2(2 CHAR),
  MOD_98   VARCHAR2(2 CHAR),
  MOD_99   VARCHAR2(2 CHAR),
  MOD_1A   VARCHAR2(2 CHAR),
  MOD_1B   VARCHAR2(2 CHAR),
  MOD_1C   VARCHAR2(2 CHAR),
  MOD_1D   VARCHAR2(2 CHAR),
  MOD_1E   VARCHAR2(2 CHAR),
  MOD_1F   VARCHAR2(2 CHAR),
  MOD_1G   VARCHAR2(2 CHAR),
  MOD_1H   VARCHAR2(2 CHAR),
  MOD_1I   VARCHAR2(2 CHAR),
  MOD_1L   VARCHAR2(2 CHAR),
  MOD_1M   VARCHAR2(2 CHAR),
  MOD_1N   VARCHAR2(2 CHAR),
  MOD_1O   VARCHAR2(2 CHAR),
  MOD_1P   VARCHAR2(2 CHAR),
  MOD_1Q   VARCHAR2(2 CHAR),
  MOD_1R   VARCHAR2(2 CHAR),
  MOD_1S   VARCHAR2(2 CHAR),
  MOD_1T   VARCHAR2(2 CHAR),
  MOD_1U   VARCHAR2(2 CHAR),
  MOD_1V   VARCHAR2(2 CHAR),
  MOD_1Z   VARCHAR2(2 CHAR),
  MOD_2A   VARCHAR2(2 CHAR),
  MOD_2B   VARCHAR2(2 CHAR),
  MOD_2C   VARCHAR2(2 CHAR),
  MOD_2D   VARCHAR2(2 CHAR),
  MOD_2E   VARCHAR2(2 CHAR),
  MOD_2F   VARCHAR2(2 CHAR),
  MOD_2G   VARCHAR2(2 CHAR),
  MOD_2H   VARCHAR2(2 CHAR),
  MOD_2I   VARCHAR2(2 CHAR),
  MOD_2L   VARCHAR2(2 CHAR),
  MOD_2M   VARCHAR2(2 CHAR),
  MOD_2N   VARCHAR2(2 CHAR),
  MOD_2O   VARCHAR2(2 CHAR),
  MOD_2P   VARCHAR2(2 CHAR),
  MOD_2Q   VARCHAR2(2 CHAR),
  MOD_2R   VARCHAR2(2 CHAR),
  MOD_2S   VARCHAR2(2 CHAR),
  MOD_2T   VARCHAR2(2 CHAR),
  MOD_2U   VARCHAR2(2 CHAR),
  MOD_2V   VARCHAR2(2 CHAR),
  MOD_2Z   VARCHAR2(2 CHAR),
  MOD_3A   VARCHAR2(2 CHAR),
  MOD_3B   VARCHAR2(2 CHAR),
  MOD_3C   VARCHAR2(2 CHAR),
  MOD_3D   VARCHAR2(2 CHAR),
  MOD_3E   VARCHAR2(2 CHAR),
  MOD_3F   VARCHAR2(2 CHAR),
  MOD_3G   VARCHAR2(2 CHAR),
  MOD_3H   VARCHAR2(2 CHAR),
  MOD_3I   VARCHAR2(2 CHAR),
  MOD_3L   VARCHAR2(2 CHAR),
  MOD_3M   VARCHAR2(2 CHAR),
  MOD_3N   VARCHAR2(2 CHAR),
  MOD_3O   VARCHAR2(2 CHAR),
  MOD_3P   VARCHAR2(2 CHAR),
  MOD_3Q   VARCHAR2(2 CHAR),
  MOD_3R   VARCHAR2(2 CHAR),
  MOD_3S   VARCHAR2(2 CHAR),
  MOD_3T   VARCHAR2(2 CHAR),
  MOD_3U   VARCHAR2(2 CHAR),
  MOD_3V   VARCHAR2(2 CHAR),
  MOD_3Z   VARCHAR2(2 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_MULTIPLA
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  CTD_NAS      VARCHAR2(1 CHAR),
  ATT_NAS      VARCHAR2(9 CHAR),
  ANN_ATT_NAS  VARCHAR2(4 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  COG_NEW      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  FLG_RET      VARCHAR2(1 CHAR),
  ENT_STR      VARCHAR2(150 CHAR),
  DTA_STR      VARCHAR2(8 CHAR),
  FLG_CON_EFF  VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NALTRIDATI
(
  ANNO_ATTO    VARCHAR2(4 CHAR),
  NUM_ATTO     VARCHAR2(9 CHAR),
  PROGR_ATTO   VARCHAR2(2 CHAR),
  ANN_PRO      VARCHAR2(4 CHAR),
  NUM_PRO      VARCHAR2(7 CHAR),
  ANN_PRA_RIF  VARCHAR2(4 CHAR),
  NUM_PRA_RIF  VARCHAR2(6 CHAR),
  COD_FAM      VARCHAR2(7 CHAR),
  COG_NEW      VARCHAR2(90 CHAR),
  FLG_CTD      VARCHAR2(1 CHAR),
  SIG_NAZ      VARCHAR2(3 CHAR),
  BIO_PAT      VARCHAR2(40 CHAR),
  BIO_MAT      VARCHAR2(60 CHAR),
  ATTO_ANN     VARCHAR2(10 CHAR),
  ANNO_ANN     VARCHAR2(4 CHAR),
  COD_SOSP     VARCHAR2(6 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NCOMUNICA
(
  NUM_ATTO   VARCHAR2(9 CHAR),
  AA_ATTO    VARCHAR2(4 CHAR),
  PRO_COM    VARCHAR2(4 CHAR),
  PRO_IND    VARCHAR2(3 CHAR),
  COD_COM    VARCHAR2(3 CHAR),
  ANN_PRO    VARCHAR2(4 CHAR),
  NUM_PRO    VARCHAR2(7 CHAR),
  TIP_PRO    VARCHAR2(1 CHAR),
  STA_COM    VARCHAR2(2 CHAR),
  OPERATORE  VARCHAR2(11 CHAR),
  NUM_MOD    VARCHAR2(3 CHAR),
  FLG_GEN    VARCHAR2(1 CHAR),
  TPU_COD    VARCHAR2(3 CHAR),
  TPU_VER    VARCHAR2(3 CHAR),
  UTE_OPE    VARCHAR2(11 CHAR),
  PGM_OPE    VARCHAR2(11 CHAR),
  DTA_OPE    VARCHAR2(8 CHAR),
  ORA_OPE    VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NCONSOL
(
  NUM_ATTO  VARCHAR2(9 CHAR),
  AA_ATTO   VARCHAR2(4 CHAR),
  COD_CONS  VARCHAR2(7 CHAR),
  DES_CONS  VARCHAR2(200 CHAR),
  UTE_OPE   VARCHAR2(11 CHAR),
  PGM_OPE   VARCHAR2(11 CHAR),
  DTA_OPE   VARCHAR2(8 CHAR),
  ORA_OPE   VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NDESTINATARI
(
  NUM_ATTO   VARCHAR2(9 CHAR),
  ANNO_ATTO  VARCHAR2(4 CHAR),
  PRO_COM    VARCHAR2(4 CHAR),
  COD_DES    VARCHAR2(7 CHAR),
  TIP_DES    VARCHAR2(2 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NREGISTRI
(
  PAR_SER_VOL  VARCHAR2(2 CHAR),
  COD_ESP_VOL  VARCHAR2(2 CHAR),
  ANNO_VOL     VARCHAR2(4 CHAR),
  NR_REG       VARCHAR2(2 CHAR),
  NR_ATTI      VARCHAR2(5 CHAR),
  UTE_FIRMA    VARCHAR2(11 CHAR),
  DTA_INI      VARCHAR2(8 CHAR),
  DTA_FINE     VARCHAR2(8 CHAR),
  DTA_CHI      VARCHAR2(8 CHAR),
  DAL          VARCHAR2(5 CHAR),
  AL           VARCHAR2(5 CHAR),
  FLG_CHI      VARCHAR2(1 CHAR),
  DTA_RITIRO   VARCHAR2(8 CHAR),
  ORA_RITIRO   VARCHAR2(5 CHAR),
  UTE_RITIRO   VARCHAR2(11 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NRIFCOMUNICA
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  ANNO_ATTO    VARCHAR2(4 CHAR),
  ANN_PRO_RIC  VARCHAR2(4 CHAR),
  NUM_PRO_RIC  VARCHAR2(7 CHAR),
  RIFERIMENTI  VARCHAR2(100 CHAR),
  STR_PRO      VARCHAR2(10 CHAR),
  TIP_INV      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_NSOSPESI
(
  NUM_ATTO       VARCHAR2(9 CHAR),
  ANNO_ATTO      VARCHAR2(4 CHAR),
  COD_SOSP       VARCHAR2(6 CHAR),
  DTA_FINE_SOSP  VARCHAR2(8 CHAR),
  FLG_TAB_ATT    VARCHAR2(2 CHAR),
  OPE_INS_SOSP   VARCHAR2(11 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_OSPEDALE
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  DTA_PRO       VARCHAR2(8 CHAR),
  DTA_DEN_OSP   VARCHAR2(8 CHAR),
  ORA_DEN_OSP   VARCHAR2(5 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  DTA_NAS       VARCHAR2(8 CHAR),
  ORA_NAS       VARCHAR2(5 CHAR),
  SEX           VARCHAR2(1 CHAR),
  COG_NAS       VARCHAR2(90 CHAR),
  NOM_NAS       VARCHAR2(90 CHAR),
  POS_GEM       VARCHAR2(1 CHAR),
  NUM_PRO_GEM   VARCHAR2(6 CHAR),
  COD_OSP       VARCHAR2(5 CHAR),
  NOM_DIR_SAN   VARCHAR2(100 CHAR),
  FLG_DEL       VARCHAR2(1 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  ATT_PRE_MAT   VARCHAR2(9 CHAR),
  ANNO_PRE_MAT  VARCHAR2(4 CHAR),
  COM_PRE_MAT   VARCHAR2(5 CHAR),
  FLG_PRE_MAT   VARCHAR2(1 CHAR),
  FLG_ATT_CON   VARCHAR2(1 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  ATT_PRE_PAT   VARCHAR2(9 CHAR),
  ANNO_PRE_PAT  VARCHAR2(4 CHAR),
  COM_PRE_PAT   VARCHAR2(5 CHAR),
  FLG_PRE_PAT   VARCHAR2(1 CHAR),
  DES_DIC       VARCHAR2(30 CHAR),
  DAT_PRO       VARCHAR2(100 CHAR),
  SEX_DIC       VARCHAR2(1 CHAR),
  COG_DIC       VARCHAR2(90 CHAR),
  NOM_DIC       VARCHAR2(90 CHAR),
  DTA_NAS_DIC   VARCHAR2(8 CHAR),
  COM_NAS_DIC   VARCHAR2(5 CHAR),
  COM_RES_DIC   VARCHAR2(5 CHAR),
  CTD_DIC       VARCHAR2(1 CHAR),
  COD_NAZ_DIC   VARCHAR2(3 CHAR),
  DTA_ATT_NOM   VARCHAR2(50 CHAR),
  FLG_STA_ATT   VARCHAR2(1 CHAR),
  FLG_DOC       VARCHAR2(1 CHAR),
  FLG_ART_COG   VARCHAR2(1 CHAR),
  FLG_FIG_INC   VARCHAR2(1 CHAR),
  FLG_DIF_DIC   VARCHAR2(1 CHAR),
  FLG_DIF_FIR   VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_PRERICONOSC
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  NUM_ATT_MAT   VARCHAR2(9 CHAR),
  ANNO_ATT_MAT  VARCHAR2(4 CHAR),
  COM_ATT_MAT   VARCHAR2(5 CHAR),
  TIP_ATT_MAT   VARCHAR2(1 CHAR),
  FLG_CON_MAT   VARCHAR2(1 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  MM_FETO       VARCHAR2(2 CHAR),
  NOM_MED_CER   VARCHAR2(100 CHAR),
  DTA_CER       VARCHAR2(8 CHAR),
  FLG_FIG_INC   VARCHAR2(1 CHAR),
  FLG_DIF_DIC   VARCHAR2(1 CHAR),
  FLG_DIF_FIR   VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  FLG_CAR       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_PROTOCOLLO
(
  ANN_PRA_RIF   VARCHAR2(4 CHAR),
  NUM_PRA_RIF   VARCHAR2(6 CHAR),
  ANN_PRO_OUT   VARCHAR2(4 CHAR),
  NUM_PRO_OUT   VARCHAR2(7 CHAR),
  NUM_ATT_NSC   VARCHAR2(9 CHAR),
  ANN_ATT_NSC   VARCHAR2(4 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  DTA_MEM_ATT   VARCHAR2(8 CHAR),
  UTE_MEM_ATTO  VARCHAR2(11 CHAR),
  ORA_MEM_ATTO  VARCHAR2(5 CHAR),
  DTA_PRO       VARCHAR2(8 CHAR),
  UTE_PRO       VARCHAR2(11 CHAR),
  ORA_PRO       VARCHAR2(5 CHAR),
  ENT_RIC       VARCHAR2(1 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_PROVVSTRA
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  TIP_DIC       VARCHAR2(2 CHAR),
  ENT_RIC       VARCHAR2(1 CHAR),
  ENT_PROVV     VARCHAR2(90 CHAR),
  COD_COM_CON   VARCHAR2(5 CHAR),
  DTA_PRO       VARCHAR2(8 CHAR),
  COG_RIC       VARCHAR2(90 CHAR),
  NOM_RIC       VARCHAR2(90 CHAR),
  SIG_NAZ_CON   VARCHAR2(3 CHAR),
  LINGUA        VARCHAR2(20 CHAR),
  DTA_PROVV     VARCHAR2(8 CHAR),
  FLG_TRI_LEG   VARCHAR2(1 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  SEX           VARCHAR2(1 CHAR),
  DTA_NAS       VARCHAR2(8 CHAR),
  COD_COM_NAS   VARCHAR2(5 CHAR),
  NUM_ATT_NAS   VARCHAR2(9 CHAR),
  ANNO_ATT_NAS  VARCHAR2(4 CHAR),
  COM_ATT_NAS   VARCHAR2(5 CHAR),
  COG_NAS       VARCHAR2(90 CHAR),
  NOM_NAS       VARCHAR2(90 CHAR),
  COM_RES_NAS   VARCHAR2(5 CHAR),
  CTD_NAS       VARCHAR2(1 CHAR),
  COD_NAZ_NAS   VARCHAR2(3 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  COG_NEW       VARCHAR2(90 CHAR),
  NOM_NEW       VARCHAR2(90 CHAR),
  SEX_NEW       VARCHAR2(1 CHAR),
  DTA_NAS_NEW   VARCHAR2(8 CHAR),
  COD_COM_NEW   VARCHAR2(5 CHAR),
  FLG_RET       VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_PUBBLICO
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  DTA_NAS       VARCHAR2(8 CHAR),
  ORA_NAS       VARCHAR2(5 CHAR),
  SEX           VARCHAR2(1 CHAR),
  COG_NAS       VARCHAR2(90 CHAR),
  NOM_NAS       VARCHAR2(90 CHAR),
  POS_GEM       VARCHAR2(1 CHAR),
  NUM_PRO_GEM   VARCHAR2(6 CHAR),
  COD_OSP       VARCHAR2(5 CHAR),
  NOM_OST_CER   VARCHAR2(100 CHAR),
  FLG_TIP_DOT   VARCHAR2(1 CHAR),
  DTA_CER       VARCHAR2(8 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  ATT_PRE_MAT   VARCHAR2(9 CHAR),
  ANNO_PRE_MAT  VARCHAR2(4 CHAR),
  COM_PRE_MAT   VARCHAR2(5 CHAR),
  FLG_PRE_MAT   VARCHAR2(1 CHAR),
  FLG_ATT_CON   VARCHAR2(1 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  ATT_PRE_PAT   VARCHAR2(9 CHAR),
  ANNO_PRE_PAT  VARCHAR2(4 CHAR),
  COM_PRE_PAT   VARCHAR2(5 CHAR),
  FLG_PRE_PAT   VARCHAR2(1 CHAR),
  DES_DIC       VARCHAR2(30 CHAR),
  DAT_PRO       VARCHAR2(100 CHAR),
  SEX_DIC       VARCHAR2(1 CHAR),
  COG_DIC       VARCHAR2(90 CHAR),
  NOM_DIC       VARCHAR2(90 CHAR),
  DTA_NAS_DIC   VARCHAR2(8 CHAR),
  COM_NAS_DIC   VARCHAR2(5 CHAR),
  COM_RES_DIC   VARCHAR2(5 CHAR),
  CTD_DIC       VARCHAR2(1 CHAR),
  COD_NAZ_DIC   VARCHAR2(3 CHAR),
  DTA_ATT_NOM   VARCHAR2(50 CHAR),
  FLG_STA_ATT   VARCHAR2(1 CHAR),
  FLG_DOC       VARCHAR2(1 CHAR),
  FLG_ART_COG   VARCHAR2(1 CHAR),
  COD_TIP_IND   VARCHAR2(1 CHAR),
  FLG_DIC_TAR   VARCHAR2(1 CHAR),
  FLG_FIG_INC   VARCHAR2(1 CHAR),
  FLG_DIF_DIC   VARCHAR2(1 CHAR),
  FLG_DIF_FIR   VARCHAR2(1 CHAR),
  FLG_LUO_NAS   VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON SC_MIGR.ATTINAS_PUBBLICO TO MIGR_USR;
CREATE TABLE SC_MIGR.ATTINAS_RICONFIGLI
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  COG_RIC       VARCHAR2(90 CHAR),
  NOM_RIC       VARCHAR2(90 CHAR),
  DTA_NSC       VARCHAR2(8 CHAR),
  NUM_ATT_NSC   VARCHAR2(9 CHAR),
  ANNO_ATT_NSC  VARCHAR2(4 CHAR),
  COM_ATT_NSC   VARCHAR2(5 CHAR),
  SEX           VARCHAR2(1 CHAR),
  COM_NSC       VARCHAR2(5 CHAR),
  COM_RES       VARCHAR2(5 CHAR),
  FLG_CTD       VARCHAR2(1 CHAR),
  SIG_NAZ       VARCHAR2(3 CHAR),
  FLG_TIP_RIC   VARCHAR2(1 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_RICONOSC
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  NUM_PRO       VARCHAR2(2 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  SEX           VARCHAR2(1 CHAR),
  DTA_NAS       VARCHAR2(8 CHAR),
  COD_COM_NAS   VARCHAR2(5 CHAR),
  NUM_ATT_NAS   VARCHAR2(9 CHAR),
  ANNO_ATT_NAS  VARCHAR2(4 CHAR),
  COM_ATT_NAS   VARCHAR2(5 CHAR),
  COG_NAS       VARCHAR2(90 CHAR),
  NOM_NAS       VARCHAR2(90 CHAR),
  COM_RES_NAS   VARCHAR2(5 CHAR),
  CTD_NAS       VARCHAR2(1 CHAR),
  COD_NAZ_NAS   VARCHAR2(3 CHAR),
  DTA_DEC_NAS   VARCHAR2(8 CHAR),
  COM_DEC_NAS   VARCHAR2(5 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  FLG_PRE_MOR   VARCHAR2(1 CHAR),
  FLG_ASS_FIG   VARCHAR2(1 CHAR),
  FLG_SCE_COG   VARCHAR2(1 CHAR),
  COG_NEW       VARCHAR2(90 CHAR),
  FLG_CON_GEN   VARCHAR2(1 CHAR),
  FLG_FIG_INC   VARCHAR2(2 CHAR),
  FLG_DIF_DIC   VARCHAR2(1 CHAR),
  FLG_DIF_FIR   VARCHAR2(1 CHAR),
  FLG_ART_33    VARCHAR2(2 CHAR),
  FLG_RET       VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  FLG_LEG       VARCHAR2(1 CHAR),
  FLG_CAR       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_SCELTACOG
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  SEX          VARCHAR2(1 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  COD_COM_RES  VARCHAR2(5 CHAR),
  FLG_CTD      VARCHAR2(1 CHAR),
  SIG_NAZ      VARCHAR2(3 CHAR),
  COG_MAT      VARCHAR2(90 CHAR),
  NOM_MAT      VARCHAR2(90 CHAR),
  COG_PAT      VARCHAR2(90 CHAR),
  NOM_PAT      VARCHAR2(90 CHAR),
  COG_PRE      VARCHAR2(90 CHAR),
  FLG_COG_SCE  VARCHAR2(1 CHAR),
  ATT_MAT_GEN  VARCHAR2(9 CHAR),
  ANN_MAT_GEN  VARCHAR2(4 CHAR),
  COM_TRI_MAT  VARCHAR2(5 CHAR),
  DTA_TRA_MAT  VARCHAR2(8 CHAR),
  FLG_ISC_TRA  VARCHAR2(1 CHAR),
  NUM_PRO_TRI  VARCHAR2(20 CHAR),
  ENTE_PRO     VARCHAR2(100 CHAR),
  ATT_MAT      VARCHAR2(20 CHAR),
  ENTE_MAT     VARCHAR2(180 CHAR),
  DTA_ATT_MAT  VARCHAR2(8 CHAR),
  ATT_PAT      VARCHAR2(20 CHAR),
  ENTE_PAT     VARCHAR2(180 CHAR),
  DTA_ATT_PAT  VARCHAR2(8 CHAR),
  CAM_MOD_GEN  VARCHAR2(1 CHAR),
  FLG_DIF_DIC  VARCHAR2(1 CHAR),
  FLG_DIF_FIR  VARCHAR2(1 CHAR),
  FLG_MOD      VARCHAR2(2 CHAR),
  FLG_RET      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_TARDIVI
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  TIP_PER_TAR  VARCHAR2(1 CHAR),
  COD_COM_TRI  VARCHAR2(5 CHAR),
  DTA_DEC_TRI  VARCHAR2(8 CHAR),
  NUM_DEC_TRI  VARCHAR2(20 CHAR),
  DES_MOT_RIT  VARCHAR2(400 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_TESTO
(
  NUM_ATTO  VARCHAR2(9 CHAR),
  AA_ATTO   VARCHAR2(4 CHAR),
  NUM_PRO   VARCHAR2(2 CHAR),
  TESTO     VARCHAR2(400 CHAR),
  UTE_OPE   VARCHAR2(11 CHAR),
  PGM_OPE   VARCHAR2(11 CHAR),
  DTA_OPE   VARCHAR2(8 CHAR),
  ORA_OPE   VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_TRAOSPEDALE
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  DTA_ATT_ISC   VARCHAR2(8 CHAR),
  ORA_ATTO_ISC  VARCHAR2(5 CHAR),
  UFF_ATT_ISC   VARCHAR2(100 CHAR),
  COM_ATT_ISC   VARCHAR2(5 CHAR),
  DTA_PRO_ISC   VARCHAR2(8 CHAR),
  DTA_PRO       VARCHAR2(8 CHAR),
  DTA_DEN_OSP   VARCHAR2(8 CHAR),
  ORA_DEN_OSP   VARCHAR2(5 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  DTA_NAS       VARCHAR2(8 CHAR),
  ORA_NAS       VARCHAR2(5 CHAR),
  SEX           VARCHAR2(1 CHAR),
  COG_NAS       VARCHAR2(90 CHAR),
  NOM_NAS       VARCHAR2(90 CHAR),
  POS_GEM       VARCHAR2(1 CHAR),
  NUM_PRO_GEM   VARCHAR2(6 CHAR),
  COD_OSP       VARCHAR2(5 CHAR),
  NOM_DIR_SAN   VARCHAR2(100 CHAR),
  FLG_DEL       VARCHAR2(1 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  ATT_PRE_MAT   VARCHAR2(9 CHAR),
  ANNO_PRE_MAT  VARCHAR2(4 CHAR),
  COM_PRE_MAT   VARCHAR2(5 CHAR),
  FLG_PRE_MAT   VARCHAR2(1 CHAR),
  FLG_ATT_CON   VARCHAR2(1 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  ATT_PRE_PAT   VARCHAR2(9 CHAR),
  ANNO_PRE_PAT  VARCHAR2(4 CHAR),
  COM_PRE_PAT   VARCHAR2(5 CHAR),
  FLG_PRE_PAT   VARCHAR2(1 CHAR),
  DES_DIC       VARCHAR2(30 CHAR),
  DAT_PRO       VARCHAR2(100 CHAR),
  SEX_DIC       VARCHAR2(1 CHAR),
  COG_DIC       VARCHAR2(90 CHAR),
  NOM_DIC       VARCHAR2(90 CHAR),
  DTA_NAS_DIC   VARCHAR2(8 CHAR),
  COM_NAS_DIC   VARCHAR2(5 CHAR),
  COM_RES_DIC   VARCHAR2(5 CHAR),
  CTD_DIC       VARCHAR2(1 CHAR),
  COD_NAZ_DIC   VARCHAR2(3 CHAR),
  DTA_ATT_NOM   VARCHAR2(50 CHAR),
  FLG_STA_ATT   VARCHAR2(1 CHAR),
  FLG_DOC       VARCHAR2(1 CHAR),
  FLG_ART_COG   VARCHAR2(1 CHAR),
  FLG_FIG_INC   VARCHAR2(1 CHAR),
  FLG_DIF_DIC   VARCHAR2(1 CHAR),
  FLG_DIF_FIR   VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_TRAPUBBLICO
(
  NUM_ATTO      VARCHAR2(9 CHAR),
  AA_ATTO       VARCHAR2(4 CHAR),
  MM_ATTO       VARCHAR2(2 CHAR),
  GG_ATTO       VARCHAR2(2 CHAR),
  ORA_ATTO      VARCHAR2(5 CHAR),
  OPERATORE     VARCHAR2(11 CHAR),
  DTA_ATT_ISC   VARCHAR2(8 CHAR),
  ORA_ATT_ISC   VARCHAR2(5 CHAR),
  UFF_ATT_ISC   VARCHAR2(100 CHAR),
  COM_ATT_ISC   VARCHAR2(5 CHAR),
  DTA_PRO       VARCHAR2(8 CHAR),
  COD_IND       VARCHAR2(7 CHAR),
  DTA_NAS       VARCHAR2(8 CHAR),
  ORA_NAS       VARCHAR2(5 CHAR),
  SEX           VARCHAR2(1 CHAR),
  COG_NAS       VARCHAR2(90 CHAR),
  NOM_NAS       VARCHAR2(90 CHAR),
  POS_GEM       VARCHAR2(1 CHAR),
  NUM_PRO_GEM   VARCHAR2(6 CHAR),
  COD_OSP       VARCHAR2(5 CHAR),
  NOM_OST_CER   VARCHAR2(100 CHAR),
  FLG_TIP_DOT   VARCHAR2(1 CHAR),
  DTA_CER       VARCHAR2(8 CHAR),
  COD_IND_MAT   VARCHAR2(7 CHAR),
  COG_MAT       VARCHAR2(90 CHAR),
  NOM_MAT       VARCHAR2(90 CHAR),
  DTA_NAS_MAT   VARCHAR2(8 CHAR),
  COM_NAS_MAT   VARCHAR2(5 CHAR),
  COM_RES_MAT   VARCHAR2(5 CHAR),
  CTD_MAT       VARCHAR2(1 CHAR),
  COD_NAZ_MAT   VARCHAR2(3 CHAR),
  ATT_PRE_MAT   VARCHAR2(9 CHAR),
  ANNO_PRE_MAT  VARCHAR2(4 CHAR),
  COM_PRE_MAT   VARCHAR2(5 CHAR),
  FLG_PRE_MAT   VARCHAR2(1 CHAR),
  FLG_ATT_CON   VARCHAR2(1 CHAR),
  COD_IND_PAT   VARCHAR2(7 CHAR),
  COG_PAT       VARCHAR2(90 CHAR),
  NOM_PAT       VARCHAR2(90 CHAR),
  DTA_NAS_PAT   VARCHAR2(8 CHAR),
  COM_NAS_PAT   VARCHAR2(5 CHAR),
  COM_RES_PAT   VARCHAR2(5 CHAR),
  CTD_PAT       VARCHAR2(1 CHAR),
  COD_NAZ_PAT   VARCHAR2(3 CHAR),
  ATT_PRE_PAT   VARCHAR2(9 CHAR),
  ANNO_PRE_PAT  VARCHAR2(4 CHAR),
  COM_PRE_PAT   VARCHAR2(5 CHAR),
  FLG_PRE_PAT   VARCHAR2(1 CHAR),
  DES_DIC       VARCHAR2(30 CHAR),
  DAT_PRO       VARCHAR2(100 CHAR),
  SEX_DIC       VARCHAR2(1 CHAR),
  COG_DIC       VARCHAR2(90 CHAR),
  NOM_DIC       VARCHAR2(90 CHAR),
  DTA_NAS_DIC   VARCHAR2(8 CHAR),
  COM_NAS_DIC   VARCHAR2(5 CHAR),
  COM_RES_DIC   VARCHAR2(5 CHAR),
  CTD_DIC       VARCHAR2(1 CHAR),
  COD_NAZ_DIC   VARCHAR2(3 CHAR),
  DTA_ATT_NOM   VARCHAR2(50 CHAR),
  FLG_STA_ATT   VARCHAR2(1 CHAR),
  FLG_DOC       VARCHAR2(1 CHAR),
  FLG_ART_COG   VARCHAR2(1 CHAR),
  COD_TIP_IND   VARCHAR2(1 CHAR),
  FLG_DIC_TAR   VARCHAR2(1 CHAR),
  FLG_FIG_INC   VARCHAR2(1 CHAR),
  FLG_DIF_DIC   VARCHAR2(1 CHAR),
  FLG_DIF_FIR   VARCHAR2(1 CHAR),
  FLG_LUO_NAS   VARCHAR2(1 CHAR),
  NUM_MOD       VARCHAR2(2 CHAR),
  UTE_OPE       VARCHAR2(11 CHAR),
  PGM_OPE       VARCHAR2(11 CHAR),
  DTA_OPE       VARCHAR2(8 CHAR),
  ORA_OPE       VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_VARANA
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  NUM_PRO      VARCHAR2(2 CHAR),
  MM_ATTO      VARCHAR2(2 CHAR),
  GG_ATTO      VARCHAR2(2 CHAR),
  ORA_ATTO     VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  DTA_DEC      VARCHAR2(8 CHAR),
  COD_IND      VARCHAR2(7 CHAR),
  DTA_NAS      VARCHAR2(8 CHAR),
  COM_NAS      VARCHAR2(5 CHAR),
  ATT_NAS      VARCHAR2(9 CHAR),
  ANN_ATT_NAS  VARCHAR2(4 CHAR),
  COM_ATT_NAS  VARCHAR2(5 CHAR),
  SEX          VARCHAR2(1 CHAR),
  COG_NAS      VARCHAR2(90 CHAR),
  NOM_NAS      VARCHAR2(90 CHAR),
  COG_NEW      VARCHAR2(90 CHAR),
  NOM_NEW      VARCHAR2(90 CHAR),
  COM_RES      VARCHAR2(5 CHAR),
  CTD_INT      VARCHAR2(1 CHAR),
  COD_NAZ      VARCHAR2(3 CHAR),
  COD_IND_DIC  VARCHAR2(7 CHAR),
  SEX_DIC      VARCHAR2(1 CHAR),
  COG_DIC      VARCHAR2(90 CHAR),
  NOM_DIC      VARCHAR2(90 CHAR),
  DTA_NAS_DIC  VARCHAR2(8 CHAR),
  COM_NAS_DIC  VARCHAR2(5 CHAR),
  COM_RES_DIC  VARCHAR2(5 CHAR),
  CTD_DIC      VARCHAR2(1 CHAR),
  COD_NAZ_DIC  VARCHAR2(3 CHAR),
  TXT_QUA      VARCHAR2(50 CHAR),
  COM_PRE      VARCHAR2(5 CHAR),
  FLG_MIN_PRE  VARCHAR2(1 CHAR),
  FLG_STA_ATT  VARCHAR2(1 CHAR),
  FLG_RET      VARCHAR2(1 CHAR),
  NUM_MOD      VARCHAR2(2 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_VARGEN
(
  NUM_ATTO     VARCHAR2(9 CHAR),
  AA_ATTO      VARCHAR2(4 CHAR),
  COG_NEW      VARCHAR2(90 CHAR),
  COG_OLD      VARCHAR2(90 CHAR),
  NOM_NEW      VARCHAR2(90 CHAR),
  NOM_OLD      VARCHAR2(90 CHAR),
  DTA_NAS_NEW  VARCHAR2(8 CHAR),
  DTA_NAS_OLD  VARCHAR2(8 CHAR),
  COM_NAS_NEW  VARCHAR2(5 CHAR),
  COM_NAS_OLD  VARCHAR2(5 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.ATTINAS_VOLUMI
(
  PAR_SER_VOL  VARCHAR2(2 CHAR),
  COD_ESP_VOL  VARCHAR2(2 CHAR),
  ANNO_VOL     VARCHAR2(4 CHAR),
  ULT_NUM_VOL  VARCHAR2(5 CHAR),
  OPERATORE    VARCHAR2(11 CHAR),
  NUM_MUN      VARCHAR2(2 CHAR),
  SED_MUN      VARCHAR2(1 CHAR),
  COD_OSP      VARCHAR2(5 CHAR),
  OCCHIO       VARCHAR2(1 CHAR),
  DTA_PRO      VARCHAR2(8 CHAR),
  FLG_VAL      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_AUTORITA
(
  NUM_AUT  VARCHAR2(3 CHAR),
  DESCR    VARCHAR2(100 CHAR),
  UTE_OPE  VARCHAR2(11 CHAR),
  PGM_OPE  VARCHAR2(11 CHAR),
  DTA_OPE  VARCHAR2(8 CHAR),
  ORA_OPE  VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_DESTCONF
(
  AREA         VARCHAR2(3 CHAR),
  NUM_MOD      VARCHAR2(3 CHAR),
  COD_COMUNIC  VARCHAR2(3 CHAR),
  COD_DES      VARCHAR2(7 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_ESPONENTE
(
  PAR_SER   VARCHAR2(2 CHAR),
  COD_ESP   VARCHAR2(2 CHAR),
  ANNO_ATT  VARCHAR2(4 CHAR),
  NUM_ATT   VARCHAR2(5 CHAR),
  UTE_CIV   VARCHAR2(11 CHAR),
  COD_OSP   VARCHAR2(5 CHAR),
  OCCHIO    VARCHAR2(1 CHAR),
  DTA_PRO   VARCHAR2(8 CHAR),
  UTE_OPE   VARCHAR2(11 CHAR),
  PGM_OPE   VARCHAR2(11 CHAR),
  DTA_OPE   VARCHAR2(8 CHAR),
  ORA_OPE   VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_OSPEDALI
(
  COD_OSP      VARCHAR2(5 CHAR),
  DEN_OSP      VARCHAR2(100 CHAR),
  IND_OSP      VARCHAR2(100 CHAR),
  NOM_DIR_SAN  VARCHAR2(100 CHAR),
  COD_COM_OSP  VARCHAR2(5 CHAR),
  FLG_DEL      VARCHAR2(1 CHAR),
  TIP_OSP      VARCHAR2(1 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_STAMPECONF
(
  AREA      VARCHAR2(3 CHAR),
  NUM_MOD   VARCHAR2(3 CHAR),
  COD_STA   VARCHAR2(3 CHAR),
  DES_STA   VARCHAR2(100 CHAR),
  ROU_STA   VARCHAR2(20 CHAR),
  FLG_PAR   VARCHAR2(1 CHAR),
  FLG_DEST  VARCHAR2(3 CHAR),
  FLG_MAIL  VARCHAR2(1 CHAR),
  FLG_ANNU  VARCHAR2(1 CHAR),
  FLG_PRO   VARCHAR2(1 CHAR),
  FLG_ORD   VARCHAR2(2 CHAR),
  TIP_DOC   VARCHAR2(1 CHAR),
  TIP_MAIL  VARCHAR2(1 CHAR),
  TPU_COD   VARCHAR2(3 CHAR),
  TPU_VER   VARCHAR2(3 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_UTENTI
(
  OPERATORE    VARCHAR2(11 CHAR),
  COGN_UTE     VARCHAR2(90 CHAR),
  NOME_UTE     VARCHAR2(90 CHAR),
  SEX          VARCHAR2(1 CHAR),
  TIP_ABI_NAS  VARCHAR2(1 CHAR),
  TIP_ABI_MAT  VARCHAR2(1 CHAR),
  TIP_ABI_DEC  VARCHAR2(1 CHAR),
  TIP_ABI_CIT  VARCHAR2(1 CHAR),
  TIP_ABI_ANN  VARCHAR2(1 CHAR),
  TIP_ABI_BAS  VARCHAR2(1 CHAR),
  TIP_ABI_PUB  VARCHAR2(1 CHAR),
  NUM_MUN      VARCHAR2(2 CHAR),
  SED_MUN      VARCHAR2(1 CHAR),
  UTE_FIRMA    VARCHAR2(11 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SC_MIGR.STCIV_UTENTIS
(
  OPERATORE    VARCHAR2(11 CHAR),
  COGN_UTE     VARCHAR2(90 CHAR),
  NOME_UTE     VARCHAR2(90 CHAR),
  SEX          VARCHAR2(1 CHAR),
  TIP_ABI_NAS  VARCHAR2(1 CHAR),
  TIP_ABI_MAT  VARCHAR2(1 CHAR),
  TIP_ABI_DEC  VARCHAR2(1 CHAR),
  TIP_ABI_CIT  VARCHAR2(1 CHAR),
  TIP_ABI_ANN  VARCHAR2(1 CHAR),
  TIP_ABI_BAS  VARCHAR2(1 CHAR),
  TIP_ABI_PUB  VARCHAR2(1 CHAR),
  NUM_MUN      VARCHAR2(2 CHAR),
  SED_MUN      VARCHAR2(1 CHAR),
  UTE_FIRMA    VARCHAR2(11 CHAR),
  UTE_OPE      VARCHAR2(11 CHAR),
  PGM_OPE      VARCHAR2(11 CHAR),
  DTA_OPE      VARCHAR2(8 CHAR),
  ORA_OPE      VARCHAR2(5 CHAR)
)
TABLESPACE ANAG_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
