CREATE TABLE SCANAT_USR.TABLE1
(
  COLUMN1  VARCHAR2(20 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SCANAT_USR.SCANATTO
(
  ID                   NUMBER                   NOT NULL,
  COD_IND              VARCHAR2(7 CHAR),
  TIP_ATT              VARCHAR2(3 CHAR),
  ANNO_ATTO            NUMBER(4),
  NUM_ATTO             VARCHAR2(9 CHAR),
  DTA_EVE              DATE,
  COD_COM_EVE          VARCHAR2(6 CHAR),
  DTA_RICH             DATE,
  DTA_SCAN             DATE,
  DTA_ANNOT            DATE,
  FLG_ANN              CHAR(1 BYTE),
  MOTIVO               VARCHAR2(1000 CHAR),
  E_MAIL               VARCHAR2(200 CHAR),
  RICHIEDENTE          VARCHAR2(200 CHAR),
  UTE_OPE              VARCHAR2(200 CHAR),
  PGM_OPE              VARCHAR2(200 CHAR),
  DTA_ORA_OPE          TIMESTAMP(6),
  ID_SOGGETTO          NUMBER,
  ID_USER_RICHIEDENTE  NUMBER,
  ID_USER_OPERATORE    NUMBER,
  ID_COMUNE            NUMBER
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCANAT_USR.SCANATTO_PK ON SCANAT_USR.SCANATTO
(ID)
LOGGING
TABLESPACE SCANAT_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SCANAT_USR.SCANATTO_UX ON SCANAT_USR.SCANATTO
(ANNO_ATTO, NUM_ATTO, TIP_ATT)
LOGGING
TABLESPACE SCANAT_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER SCANAT_USR.TRG_SCANATTO_PK 
   before insert on "SCANAT_USR"."SCANATTO" 
   for each row
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select SEQ_SCANATTO_ID.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;
/


ALTER TABLE SCANAT_USR.SCANATTO ADD (
  CONSTRAINT SCANATTO_PK
  PRIMARY KEY
  (ID)
  USING INDEX SCANAT_USR.SCANATTO_PK
  ENABLE VALIDATE);
CREATE TABLE SCANAT_USR.PROFILO
(
  PROFILO_ID   NUMBER                           NOT NULL,
  DESCRIZIONE  VARCHAR2(20 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCANAT_USR.PROFILO_PK ON SCANAT_USR.PROFILO
(PROFILO_ID)
LOGGING
TABLESPACE SCANAT_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SCANAT_USR.PROFILO ADD (
  CONSTRAINT PROFILO_PK
  PRIMARY KEY
  (PROFILO_ID)
  USING INDEX SCANAT_USR.PROFILO_PK
  ENABLE VALIDATE);
CREATE TABLE SCANAT_USR.UTENTE
(
  UTENTE_ID           NUMBER                    NOT NULL,
  NOME_UTENTE         VARCHAR2(100 BYTE)        NOT NULL,
  NOME_UTENTE_AGGIOR  VARCHAR2(100 BYTE),
  IS_TUTELA           CHAR(1 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCANAT_USR.UTENTE_PK ON SCANAT_USR.UTENTE
(UTENTE_ID)
LOGGING
TABLESPACE SCANAT_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SCANAT_USR.UTENTE ADD (
  CONSTRAINT UTENTE_PK
  PRIMARY KEY
  (UTENTE_ID)
  USING INDEX SCANAT_USR.UTENTE_PK
  ENABLE VALIDATE);
CREATE TABLE SCANAT_USR.UTENTE_PROFILO
(
  UTENTE_ID   NUMBER,
  PROFILO_ID  NUMBER,
  LIVELLO     NUMBER
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SCANAT_USR.UTENTE_PROFILO_UK1 ON SCANAT_USR.UTENTE_PROFILO
(UTENTE_ID, PROFILO_ID, LIVELLO)
LOGGING
TABLESPACE SCANAT_USR
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SCANAT_USR.UTENTE_PROFILO ADD (
  CONSTRAINT UTENTE_PROFILO_UK1
  UNIQUE (UTENTE_ID, PROFILO_ID, LIVELLO)
  USING INDEX SCANAT_USR.UTENTE_PROFILO_UK1
  ENABLE VALIDATE);

ALTER TABLE SCANAT_USR.UTENTE_PROFILO ADD (
  CONSTRAINT UTENTE_PROFILO_FK1 
  FOREIGN KEY (PROFILO_ID) 
  REFERENCES SCANAT_USR.PROFILO (PROFILO_ID)
  ENABLE VALIDATE,
  CONSTRAINT UTENTE_PROFILO_FK2 
  FOREIGN KEY (UTENTE_ID) 
  REFERENCES SCANAT_USR.UTENTE (UTENTE_ID)
  ENABLE VALIDATE);
CREATE TABLE SCANAT_USR.SCANATTO_SCANATTOS
(
  COD_IND          VARCHAR2(7 BYTE),
  TIP_ATT          VARCHAR2(3 BYTE),
  ANNO_ATTO        VARCHAR2(4 BYTE),
  NUM_ATTO         VARCHAR2(10 BYTE),
  DTA_EVE          VARCHAR2(8 BYTE),
  COD_COM_EVE      VARCHAR2(5 BYTE),
  DTA_RICH         VARCHAR2(8 BYTE),
  DTA_SCAN         VARCHAR2(8 BYTE),
  DTA_ANNOT        VARCHAR2(8 BYTE),
  FLG_ANN          VARCHAR2(1 BYTE),
  MOTIVO           VARCHAR2(120 BYTE),
  E_MAIL           VARCHAR2(45 BYTE),
  RICHIEDENTE      VARCHAR2(11 BYTE),
  UTE_OPE_OLD      VARCHAR2(11 BYTE),
  PGM_OPE_OLD      VARCHAR2(11 BYTE),
  DTA_ORA_OPE_OLD  VARCHAR2(26 BYTE),
  UTE_OPE          VARCHAR2(11 BYTE),
  PGM_OPE          VARCHAR2(11 BYTE),
  DTA_ORA_OPE      VARCHAR2(26 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SCANAT_USR.SCANATTO_ETICHAUTOS
(
  COD_IND          VARCHAR2(7 BYTE),
  TIP_ATTO         VARCHAR2(3 BYTE),
  ANNO_ATTO        VARCHAR2(4 BYTE),
  NUM_ATTO         VARCHAR2(10 BYTE),
  PRG_ANN          VARCHAR2(3 BYTE),
  TIP_ANN          VARCHAR2(1 BYTE),
  DTA_RICH         VARCHAR2(8 BYTE),
  FLG_STATUS       VARCHAR2(2 BYTE),
  TESTO_ANN        VARCHAR2(500 BYTE),
  UTE_OPE_OLD      VARCHAR2(11 BYTE),
  PGM_OPE_OLD      VARCHAR2(11 BYTE),
  DTA_ORA_OPE_OLD  VARCHAR2(26 BYTE),
  UTE_OPE          VARCHAR2(11 BYTE),
  PGM_OPE          VARCHAR2(11 BYTE),
  DTA_ORA_OPE      VARCHAR2(26 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SCANAT_USR.SCANATTO_ETICHAUTO
(
  COD_IND      VARCHAR2(7 BYTE),
  TIP_ATTO     VARCHAR2(3 BYTE),
  ANNO_ATTO    VARCHAR2(4 BYTE),
  NUM_ATTO     VARCHAR2(10 BYTE),
  PRG_ANN      VARCHAR2(3 BYTE),
  TIP_ANN      VARCHAR2(1 BYTE),
  DTA_RICH     VARCHAR2(8 BYTE),
  FLG_STATUS   VARCHAR2(2 BYTE),
  TESTO_ANN    VARCHAR2(500 BYTE),
  UTE_OPE      VARCHAR2(11 BYTE),
  PGM_OPE      VARCHAR2(11 BYTE),
  DTA_ORA_OPE  VARCHAR2(26 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SCANAT_USR.SCANATTO_RICHATTO
(
  COD_IND       VARCHAR2(7 BYTE),
  DIV_REC_POP   VARCHAR2(8 BYTE),
  SEX           VARCHAR2(1 BYTE),
  COG_NOM       VARCHAR2(120 BYTE),
  LUN_COG       VARCHAR2(2 BYTE),
  DTA_NSC       VARCHAR2(8 BYTE),
  COM_NSC       VARCHAR2(5 BYTE),
  ANNO_ATT_NSC  VARCHAR2(4 BYTE),
  ATT_NSC       VARCHAR2(9 BYTE),
  COD_STA_CIV   VARCHAR2(1 BYTE),
  COD_TIP_IND   VARCHAR2(1 BYTE),
  FLG_CTD       VARCHAR2(1 BYTE),
  SIG_NAZ       VARCHAR2(3 BYTE),
  NME_PAD       VARCHAR2(40 BYTE),
  COG_NME_MAD   VARCHAR2(60 BYTE),
  COG_NME_COG   VARCHAR2(120 BYTE),
  MOTIVO        VARCHAR2(18 BYTE),
  UTE_OPE       VARCHAR2(11 BYTE),
  PGM_OPE       VARCHAR2(11 BYTE),
  DTA_ORA_OPE   VARCHAR2(26 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
CREATE TABLE SCANAT_USR.SCANATTO_SCANATTO
(
  COD_IND      VARCHAR2(7 BYTE),
  TIP_ATT      VARCHAR2(3 BYTE),
  ANNO_ATTO    VARCHAR2(4 BYTE),
  NUM_ATTO     VARCHAR2(10 BYTE),
  DTA_EVE      VARCHAR2(8 BYTE),
  COD_COM_EVE  VARCHAR2(5 BYTE),
  DTA_RICH     VARCHAR2(8 BYTE),
  DTA_SCAN     VARCHAR2(8 BYTE),
  DTA_ANNOT    VARCHAR2(8 BYTE),
  FLG_ANN      VARCHAR2(1 BYTE),
  MOTIVO       VARCHAR2(120 BYTE),
  E_MAIL       VARCHAR2(45 BYTE),
  RICHIEDENTE  VARCHAR2(11 BYTE),
  UTE_OPE      VARCHAR2(11 BYTE),
  PGM_OPE      VARCHAR2(11 BYTE),
  DTA_ORA_OPE  VARCHAR2(26 BYTE)
)
TABLESPACE SCANAT_USR
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
